import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%MCODE_AGENT_HOOK_PORT%"=="" if defined MCODE_AGENT_HOOK_ENDPOINT if exist "%MCODE_AGENT_HOOK_ENDPOINT%" call "%MCODE_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%MCODE_AGENT_HOOK_TOKEN%"=="" if not "%MCODE_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\mcode-dev\\agent-hooks" for /r "%APPDATA%\\mcode-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%MCODE_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\mcode\\agent-hooks" for /r "%APPDATA%\\mcode\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%MCODE_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set MCODE_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%MCODE_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    '__mcode_read_ancestor_var() {',
    '  __mcode_name="$1"',
    '  __mcode_pid="${PPID:-}"',
    '  while [ -n "$__mcode_pid" ] && [ "$__mcode_pid" != "0" ] && [ "$__mcode_pid" != "1" ]; do',
    '    __mcode_value=""',
    '    if [ -r "/proc/$__mcode_pid/environ" ]; then',
    '      __mcode_value=$(tr "\\000" "\\n" < "/proc/$__mcode_pid/environ" 2>/dev/null | sed -n "s/^${__mcode_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__mcode_value" ]; then',
    '      __mcode_value=$(ps eww -p "$__mcode_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__mcode_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__mcode_value" ]; then',
    '      printf "%s\\n" "$__mcode_value"',
    '      return 0',
    '    fi',
    '    __mcode_pid=$(ps -o ppid= -p "$__mcode_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__mcode_fill_from_ancestor() {',
    '  __mcode_name="$1"',
    '  case "$__mcode_name" in',
    '    MCODE_AGENT_HOOK_ENDPOINT) [ -z "${MCODE_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    MCODE_AGENT_HOOK_PORT) [ -z "${MCODE_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    MCODE_AGENT_HOOK_TOKEN) [ -z "${MCODE_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    MCODE_AGENT_HOOK_ENV) [ -z "${MCODE_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    MCODE_AGENT_HOOK_VERSION) [ -z "${MCODE_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    MCODE_PANE_KEY) [ -z "${MCODE_PANE_KEY:-}" ] || return 0 ;;',
    '    MCODE_TAB_ID) [ -z "${MCODE_TAB_ID:-}" ] || return 0 ;;',
    '    MCODE_WORKTREE_ID) [ -z "${MCODE_WORKTREE_ID:-}" ] || return 0 ;;',
    '    MCODE_AGENT_LAUNCH_TOKEN) [ -z "${MCODE_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __mcode_value=$(__mcode_read_ancestor_var "$__mcode_name") || return 0',
    '  [ -n "$__mcode_value" ] && export "$__mcode_name=$__mcode_value"',
    '}',
    '__mcode_endpoint_value() {',
    '  __mcode_endpoint_name="$1"',
    '  __mcode_endpoint_path="$2"',
    '  sed -n "s/^${__mcode_endpoint_name}=//p" "$__mcode_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__mcode_fill_from_endpoint_file() {',
    '  __mcode_endpoint_path="$1"',
    '  [ -r "$__mcode_endpoint_path" ] || return 0',
    '  __mcode_endpoint_port=$(__mcode_endpoint_value MCODE_AGENT_HOOK_PORT "$__mcode_endpoint_path")',
    '  if [ -n "${MCODE_AGENT_HOOK_PORT:-}" ] && [ -n "$__mcode_endpoint_port" ] && [ "$__mcode_endpoint_port" != "$MCODE_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __mcode_endpoint_name in MCODE_AGENT_HOOK_PORT MCODE_AGENT_HOOK_TOKEN MCODE_AGENT_HOOK_ENV MCODE_AGENT_HOOK_VERSION; do',
    '    eval "__mcode_current=\\${$__mcode_endpoint_name:-}"',
    '    [ -z "$__mcode_current" ] || continue',
    '    __mcode_endpoint_value=$(__mcode_endpoint_value "$__mcode_endpoint_name" "$__mcode_endpoint_path")',
    '    [ -n "$__mcode_endpoint_value" ] && export "$__mcode_endpoint_name=$__mcode_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has MCode pane/hook metadata, so recover it before posting.',
    'for __mcode_name in MCODE_AGENT_HOOK_ENDPOINT MCODE_AGENT_HOOK_PORT MCODE_AGENT_HOOK_TOKEN MCODE_AGENT_HOOK_ENV MCODE_AGENT_HOOK_VERSION MCODE_PANE_KEY MCODE_TAB_ID MCODE_WORKTREE_ID MCODE_AGENT_LAUNCH_TOKEN; do',
    '  __mcode_fill_from_ancestor "$__mcode_name"',
    'done',
    'if [ -n "$MCODE_AGENT_HOOK_ENDPOINT" ] && [ -r "$MCODE_AGENT_HOOK_ENDPOINT" ]; then',
    '  __mcode_fill_from_endpoint_file "$MCODE_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# MCODE_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$MCODE_AGENT_HOOK_TOKEN" ] && [ -n "$MCODE_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/mcode-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/mcode-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/mcode-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/mcode-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/mcode/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/mcode/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^MCODE_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$MCODE_AGENT_HOOK_PORT" ]; then',
    '      __mcode_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$MCODE_AGENT_HOOK_PORT" ] || [ -z "$MCODE_AGENT_HOOK_TOKEN" ] || [ -z "$MCODE_PANE_KEY" ]; then',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${MCODE_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-MCode-Agent-Hook-Token: ${MCODE_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${MCODE_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${MCODE_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${MCODE_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${MCODE_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${MCODE_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${MCODE_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || true',
    'exit 0',
    ''
  ].join('\n')
}
