import type { StateCreator } from 'zustand';
import type { AppState } from '../types';
import type { ChangelogData, PersistedUIState, StatusBarItem, TuiAgent, UpdateStatus, WorktreeCardProperty } from '../../../../shared/types';
export type UISlice = {
    sidebarOpen: boolean;
    sidebarWidth: number;
    toggleSidebar: () => void;
    setSidebarOpen: (open: boolean) => void;
    setSidebarWidth: (width: number) => void;
    activeView: 'terminal' | 'settings' | 'new-workspace';
    previousViewBeforeNewWorkspace: 'terminal' | 'settings';
    previousViewBeforeSettings: 'terminal' | 'new-workspace';
    setActiveView: (view: UISlice['activeView']) => void;
    newWorkspacePageData: {
        preselectedRepoId?: string;
        prefilledName?: string;
    };
    newWorkspaceDraft: {
        repoId: string | null;
        name: string;
        prompt: string;
        note: string;
        attachments: string[];
        linkedWorkItem: {
            type: 'issue' | 'pr';
            number: number;
            title: string;
            url: string;
        } | null;
        agent: TuiAgent;
        linkedIssue: string;
        linkedPR: number | null;
    } | null;
    openNewWorkspacePage: (data?: UISlice['newWorkspacePageData']) => void;
    closeNewWorkspacePage: () => void;
    setNewWorkspaceDraft: (draft: NonNullable<UISlice['newWorkspaceDraft']>) => void;
    clearNewWorkspaceDraft: () => void;
    openSettingsPage: () => void;
    closeSettingsPage: () => void;
    settingsNavigationTarget: {
        pane: 'general' | 'browser' | 'appearance' | 'terminal' | 'shortcuts' | 'repo' | 'agents';
        repoId: string | null;
        sectionId?: string;
    } | null;
    openSettingsTarget: (target: NonNullable<UISlice['settingsNavigationTarget']>) => void;
    clearSettingsTarget: () => void;
    activeModal: 'none' | 'create-worktree' | 'edit-meta' | 'delete-worktree' | 'confirm-non-git-folder' | 'confirm-remove-folder' | 'add-repo' | 'quick-open' | 'worktree-palette' | 'new-workspace-composer';
    modalData: Record<string, unknown>;
    openModal: (modal: UISlice['activeModal'], data?: Record<string, unknown>) => void;
    closeModal: () => void;
    searchQuery: string;
    setSearchQuery: (q: string) => void;
    groupBy: 'none' | 'repo' | 'pr-status';
    setGroupBy: (g: UISlice['groupBy']) => void;
    sortBy: 'name' | 'smart' | 'recent' | 'repo';
    setSortBy: (s: UISlice['sortBy']) => void;
    showActiveOnly: boolean;
    setShowActiveOnly: (v: boolean) => void;
    filterRepoIds: string[];
    setFilterRepoIds: (ids: string[]) => void;
    worktreeCardProperties: WorktreeCardProperty[];
    toggleWorktreeCardProperty: (prop: WorktreeCardProperty) => void;
    statusBarItems: StatusBarItem[];
    toggleStatusBarItem: (item: StatusBarItem) => void;
    statusBarVisible: boolean;
    setStatusBarVisible: (v: boolean) => void;
    pendingRevealWorktreeId: string | null;
    revealWorktreeInSidebar: (worktreeId: string) => void;
    clearPendingRevealWorktreeId: () => void;
    persistedUIReady: boolean;
    uiZoomLevel: number;
    setUIZoomLevel: (level: number) => void;
    editorFontZoomLevel: number;
    setEditorFontZoomLevel: (level: number) => void;
    hydratePersistedUI: (ui: PersistedUIState) => void;
    updateStatus: UpdateStatus;
    setUpdateStatus: (status: UpdateStatus) => void;
    updateChangelog: ChangelogData | null;
    dismissedUpdateVersion: string | null;
    dismissUpdate: (versionOverride?: string) => void;
    clearDismissedUpdateVersion: () => void;
    updateReassuranceSeen: boolean;
    markUpdateReassuranceSeen: () => void;
    isFullScreen: boolean;
    setIsFullScreen: (v: boolean) => void;
    /** URL opened when a new browser tab is created. Null = blank tab (default). */
    browserDefaultUrl: string | null;
    setBrowserDefaultUrl: (url: string | null) => void;
};
export declare const createUISlice: StateCreator<AppState, [], [], UISlice>;
