import type { ReactNode } from 'react';
import type { OpenFile } from '@/store/slices/editor';
import type { TerminalTab, Worktree } from '../../../../shared/types';
type TerminalShellProps = {
    activeWorktreeId: string | null;
    activeView: string;
    tabs: TerminalTab[];
    activeTabId: string | null;
    activeFileId: string | null;
    activeTabType: 'terminal' | 'editor';
    expandedPaneByTabId: Record<string, boolean>;
    worktreeFiles: OpenFile[];
    mountedWorktrees: Worktree[];
    tabsByWorktree: Record<string, TerminalTab[]>;
    onActivateTab: (tabId: string) => void;
    onCloseTab: (tabId: string) => void;
    onCloseOthers: (tabId: string) => void;
    onCloseTabsToRight: (tabId: string) => void;
    onNewTerminalTab: () => void;
    onNewBrowserTab: () => void;
    onNewFileTab?: () => void;
    onSetCustomTitle: (tabId: string, title: string | null) => void;
    onSetTabColor: (tabId: string, color: string | null) => void;
    onTogglePaneExpand: (tabId: string) => void;
    onActivateFile: (fileId: string) => void;
    onCloseFile: (fileId: string) => void;
    onCloseAllFiles: () => void;
    onPinFile: (fileId: string) => void;
    onPtyExit: (tabId: string, ptyId: string) => void;
    tabBarOrder?: string[];
    editorPanel: ReactNode;
    saveDialogFileId: string | null;
    saveDialogFile: OpenFile | null;
    onSaveDialogOpenChange: (open: boolean) => void;
    onSaveDialogCancel: () => void;
    onSaveDialogDiscard: () => void;
    onSaveDialogSave: () => void;
};
export declare function TerminalShell({ activeWorktreeId, activeView, tabs, activeTabId, activeFileId, activeTabType, expandedPaneByTabId, worktreeFiles, mountedWorktrees, tabsByWorktree, onActivateTab, onCloseTab, onCloseOthers, onCloseTabsToRight, onNewTerminalTab, onNewBrowserTab, onNewFileTab, onSetCustomTitle, onSetTabColor, onTogglePaneExpand, onActivateFile, onCloseFile, onCloseAllFiles, onPinFile, onPtyExit, tabBarOrder, editorPanel, saveDialogFileId, saveDialogFile, onSaveDialogOpenChange, onSaveDialogCancel, onSaveDialogDiscard, onSaveDialogSave }: TerminalShellProps): React.JSX.Element;
export {};
