import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import TabBar from '../tab-bar/TabBar';
import TerminalPane from '../terminal-pane/TerminalPane';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
export function TerminalShell({ activeWorktreeId, activeView, tabs, activeTabId, activeFileId, activeTabType, expandedPaneByTabId, worktreeFiles, mountedWorktrees, tabsByWorktree, onActivateTab, onCloseTab, onCloseOthers, onCloseTabsToRight, onNewTerminalTab, onNewBrowserTab, onNewFileTab, onSetCustomTitle, onSetTabColor, onTogglePaneExpand, onActivateFile, onCloseFile, onCloseAllFiles, onPinFile, onPtyExit, tabBarOrder, editorPanel, saveDialogFileId, saveDialogFile, onSaveDialogOpenChange, onSaveDialogCancel, onSaveDialogDiscard, onSaveDialogSave }) {
    return (_jsxs("div", { className: `flex flex-col flex-1 min-w-0 min-h-0 overflow-hidden${activeWorktreeId ? '' : ' hidden'}`, children: [_jsx("div", { className: "grid transition-[grid-template-rows] duration-200 ease-in-out", style: { gridTemplateRows: activeWorktreeId ? '1fr' : '0fr' }, children: _jsx("div", { className: "overflow-hidden", children: activeWorktreeId && (_jsx(TabBar, { tabs: tabs, activeTabId: activeTabId, worktreeId: activeWorktreeId, onActivate: onActivateTab, onClose: onCloseTab, onCloseOthers: onCloseOthers, onCloseToRight: onCloseTabsToRight, onNewTerminalTab: onNewTerminalTab, onNewBrowserTab: onNewBrowserTab, onNewFileTab: onNewFileTab, onSetCustomTitle: onSetCustomTitle, onSetTabColor: onSetTabColor, expandedPaneByTabId: expandedPaneByTabId, onTogglePaneExpand: onTogglePaneExpand, editorFiles: worktreeFiles, activeFileId: activeFileId, activeTabType: activeTabType, onActivateFile: onActivateFile, onCloseFile: onCloseFile, onCloseAllFiles: onCloseAllFiles, onPinFile: onPinFile, tabBarOrder: tabBarOrder })) }) }), _jsx("div", { className: `relative flex-1 min-h-0 overflow-hidden ${activeTabType === 'editor' && worktreeFiles.length > 0 ? 'hidden' : ''}`, children: mountedWorktrees.map((worktree) => {
                    const worktreeTabs = tabsByWorktree[worktree.id] ?? [];
                    const isVisible = activeView === 'terminal' && worktree.id === activeWorktreeId;
                    return (_jsx("div", { className: isVisible ? 'absolute inset-0' : 'absolute inset-0 hidden', "aria-hidden": !isVisible, children: worktreeTabs.map((tab) => (_jsx(TerminalPane, { tabId: tab.id, worktreeId: worktree.id, cwd: worktree.path, isActive: isVisible && tab.id === activeTabId, onPtyExit: (ptyId) => onPtyExit(tab.id, ptyId), onCloseTab: () => onCloseTab(tab.id) }, `${tab.id}-${tab.generation ?? 0}`))) }, worktree.id));
                }) }), activeWorktreeId && activeTabType === 'editor' && worktreeFiles.length > 0 && editorPanel, _jsx(Dialog, { open: saveDialogFileId !== null, onOpenChange: onSaveDialogOpenChange, children: _jsxs(DialogContent, { className: "max-w-sm", children: [_jsxs(DialogHeader, { children: [_jsx(DialogTitle, { className: "text-sm", children: "Unsaved Changes" }), _jsx(DialogDescription, { className: "text-xs", children: saveDialogFile
                                        ? `"${saveDialogFile.relativePath.split('/').pop()}" has unsaved changes. Do you want to save before closing?`
                                        : 'This file has unsaved changes.' })] }), _jsxs(DialogFooter, { className: "gap-2", children: [_jsx(Button, { type: "button", variant: "outline", size: "sm", onClick: onSaveDialogCancel, children: "Cancel" }), _jsx(Button, { type: "button", variant: "outline", size: "sm", onClick: onSaveDialogDiscard, children: "Don't Save" }), _jsx(Button, { type: "button", size: "sm", onClick: onSaveDialogSave, children: "Save" })] })] }) })] }));
}
