import { closeTerminalTab, activateTerminalTab, activateEditorFile, toggleTerminalPaneExpand } from './terminal-tab-actions';
export type UnifiedTerminalItem = {
    type: 'terminal' | 'editor';
    id: string;
};
export declare function useTerminalTabs(): {
    activeWorktreeId: string | null;
    activeView: "terminal" | "settings" | "new-workspace";
    tabsByWorktree: Record<string, import("../../../../shared/types").TerminalTab[]>;
    tabs: import("../../../../shared/types").TerminalTab[];
    mountedWorktrees: import("../../../../shared/types").Worktree[];
    worktreeFiles: import("../../store/slices/editor").OpenFile[];
    totalTabs: number;
    unifiedTabs: UnifiedTerminalItem[];
    activeTabId: string | null;
    activeFileId: string | null;
    activeTabType: import("../../../../shared/types").WorkspaceVisibleTabType;
    expandedPaneByTabId: Record<string, boolean>;
    tabBarOrder: string[] | undefined;
    setTabBarOrder: (worktreeId: string, order: string[]) => void;
    setTabCustomTitle: (tabId: string, title: string | null) => void;
    setTabColor: (tabId: string, color: string | null) => void;
    closeAllFiles: () => void;
    handleNewTab: () => void;
    handleCloseTab: typeof closeTerminalTab;
    handlePtyExit: (tabId: string, ptyId: string) => void;
    handleCloseOthers: (tabId: string) => void;
    handleCloseTabsToRight: (tabId: string) => void;
    handleActivateTab: typeof activateTerminalTab;
    handleActivateFile: typeof activateEditorFile;
    handleTogglePaneExpand: typeof toggleTerminalPaneExpand;
};
