/* eslint-disable max-lines -- Why: this module ships a long but flat table of
   (extension → colored icon) wrappers; splitting it would scatter the palette
   across files without adding clarity. */
import {
  Database,
  File,
  FileArchive,
  FileAxis3D,
  FileBox,
  FileBraces,
  FileChartColumn,
  FileCode,
  FileCog,
  FileDiff,
  FileImage,
  FileJson,
  FileKey,
  FileLock,
  FileMusic,
  FileSliders,
  FileSpreadsheet,
  FileTerminal,
  FileText,
  FileType,
  FileVideo,
  Folder,
  FolderOpen,
  type LucideIcon
} from 'lucide-react'
import type { IconNode, IconTheme, IconThemeFileRule } from './types'

/**
 * Wrap a lucide icon so it renders with a fixed inline color. Used to give the
 * "Color Classic" theme its semantic palette without shipping new SVG assets.
 * The wrapper still respects an external `className` so size/animation classes
 * continue to flow through; only `color` is fixed.
 */
function withColor(Icon: LucideIcon, color: string): IconNode {
  const Wrapped: IconNode = ({ className, style, ...rest }) => (
    <Icon className={className} style={{ color, ...style }} {...rest} />
  )
  Wrapped.displayName = `Colored(${Icon.displayName ?? Icon.name ?? 'Icon'})`
  return Wrapped
}

// Palette — loosely inspired by Material Icon Theme's accent colors.
const C = {
  ts: '#3178c6',
  js: '#f7df1e',
  json: '#cbcb41',
  react: '#61dafb',
  vue: '#41b883',
  svelte: '#ff3e00',
  html: '#e34c26',
  css: '#563d7c',
  sass: '#cc6699',
  python: '#ffd43b',
  rust: '#dea584',
  go: '#00add8',
  java: '#b07219',
  kotlin: '#7f52ff',
  ruby: '#cc342d',
  php: '#777bb4',
  swift: '#ffac45',
  c: '#a8b9cc',
  csharp: '#178600',
  shell: '#89e051',
  yaml: '#cb171e',
  toml: '#9c4221',
  markdown: '#9ca3af',
  image: '#a78bfa',
  audio: '#f472b6',
  video: '#fb7185',
  archive: '#fbbf24',
  font: '#c084fc',
  config: '#94a3b8',
  lock: '#64748b',
  key: '#facc15',
  diff: '#10b981',
  database: '#4ade80',
  spreadsheet: '#16a34a',
  binary: '#a16207',
  text: '#9ca3af',
  folder: '#facc15',
  folderOpen: '#fde047',
  defaultFile: '#94a3b8'
}

const fileRules: IconThemeFileRule[] = [
  // Filename matches (more specific) ─────────────────────────────────────
  { filename: 'package.json', icon: withColor(FileBox, C.js) },
  { filename: 'package-lock.json', icon: withColor(FileBox, C.lock) },
  { filename: 'pnpm-lock.yaml', icon: withColor(FileBox, C.lock) },
  { filename: 'yarn.lock', icon: withColor(FileBox, C.lock) },
  { filename: 'bun.lock', icon: withColor(FileBox, C.lock) },
  { filename: 'bun.lockb', icon: withColor(FileBox, C.lock) },
  { filename: 'cargo.toml', icon: withColor(FileBox, C.rust) },
  { filename: 'cargo.lock', icon: withColor(FileBox, C.lock) },
  { filename: 'composer.json', icon: withColor(FileBox, C.php) },
  { filename: 'composer.lock', icon: withColor(FileBox, C.lock) },
  { filename: 'gemfile', icon: withColor(FileBox, C.ruby) },
  { filename: 'go.mod', icon: withColor(FileBox, C.go) },
  { filename: 'go.sum', icon: withColor(FileBox, C.go) },
  { filename: 'pipfile', icon: withColor(FileBox, C.python) },
  { filename: 'poetry.lock', icon: withColor(FileBox, C.lock) },
  { filename: 'pyproject.toml', icon: withColor(FileBox, C.python) },
  { filename: 'requirements.txt', icon: withColor(FileBox, C.python) },
  { filename: 'requirements-dev.txt', icon: withColor(FileBox, C.python) },
  { filename: 'tsconfig.json', icon: withColor(FileSliders, C.ts) },
  { filename: 'vite.config.ts', icon: withColor(FileSliders, C.ts) },
  { filename: 'vite.config.js', icon: withColor(FileSliders, C.js) },
  { filename: 'vite.config.mjs', icon: withColor(FileSliders, C.js) },
  { filename: 'vitest.config.ts', icon: withColor(FileSliders, C.ts) },
  { filename: 'tailwind.config.ts', icon: withColor(FileSliders, C.ts) },
  { filename: 'tailwind.config.js', icon: withColor(FileSliders, C.js) },
  { filename: 'tailwind.config.mjs', icon: withColor(FileSliders, C.js) },
  { filename: 'postcss.config.ts', icon: withColor(FileSliders, C.ts) },
  { filename: 'postcss.config.js', icon: withColor(FileSliders, C.js) },
  { filename: 'postcss.config.cjs', icon: withColor(FileSliders, C.js) },
  { filename: 'postcss.config.mjs', icon: withColor(FileSliders, C.js) },
  { filename: 'components.json', icon: withColor(FileSliders, C.config) },
  { filename: 'cmakelists.txt', icon: withColor(FileCog, C.c) },
  { filename: 'makefile', icon: withColor(FileTerminal, C.shell) },
  { filename: 'dockerfile', icon: withColor(FileCog, C.config) },
  { filename: '.dockerignore', icon: withColor(FileSliders, C.config) },
  { filename: '.gitignore', icon: withColor(FileSliders, C.config) },
  { filename: '.gitattributes', icon: withColor(FileSliders, C.config) },
  { filename: '.editorconfig', icon: withColor(FileSliders, C.config) },
  { filename: '.eslintrc', icon: withColor(FileSliders, C.config) },
  { filename: '.eslintrc.cjs', icon: withColor(FileSliders, C.js) },
  { filename: '.eslintrc.js', icon: withColor(FileSliders, C.js) },
  { filename: '.eslintrc.json', icon: withColor(FileJson, C.json) },
  { filename: '.eslintrc.yaml', icon: withColor(FileSliders, C.yaml) },
  { filename: '.eslintrc.yml', icon: withColor(FileSliders, C.yaml) },
  { filename: '.prettierrc', icon: withColor(FileSliders, C.config) },
  { filename: '.prettierrc.json', icon: withColor(FileJson, C.json) },
  { filename: '.babelrc', icon: withColor(FileSliders, C.js) },
  { filename: '.npmrc', icon: withColor(FileSliders, C.config) },
  { filename: 'readme', icon: withColor(FileText, C.markdown) },
  { filename: 'readme.md', icon: withColor(FileText, C.markdown) },
  { filename: 'license', icon: withColor(FileKey, C.key) },
  { filename: 'copying', icon: withColor(FileKey, C.key) },
  { filename: 'notice', icon: withColor(FileKey, C.key) },
  { filename: 'codeowners', icon: withColor(FileKey, C.key) },
  { filename: 'security.md', icon: withColor(FileLock, C.lock) },
  { filename: 'changelog', icon: withColor(FileText, C.text) },
  { filename: 'changelog.md', icon: withColor(FileText, C.text) },
  { filename: 'contributing', icon: withColor(FileText, C.text) },
  { filename: 'contributing.md', icon: withColor(FileText, C.text) },

  // Pattern matches ──────────────────────────────────────────────────────
  { pattern: /^\.env(\..+)?$/, icon: withColor(FileLock, C.lock) },
  { pattern: /^dockerfile\..+$/, icon: withColor(FileCog, C.config) },
  { pattern: /^makefile\..+$/, icon: withColor(FileTerminal, C.shell) },

  // Extension matches — TypeScript / JavaScript ─────────────────────────
  { extension: 'ts', icon: withColor(FileCode, C.ts) },
  { extension: 'tsx', icon: withColor(FileCode, C.react) },
  { extension: 'cts', icon: withColor(FileCode, C.ts) },
  { extension: 'mts', icon: withColor(FileCode, C.ts) },
  { extension: 'js', icon: withColor(FileCode, C.js) },
  { extension: 'jsx', icon: withColor(FileCode, C.react) },
  { extension: 'mjs', icon: withColor(FileCode, C.js) },
  { extension: 'cjs', icon: withColor(FileCode, C.js) },

  // Other languages
  { extension: 'py', icon: withColor(FileCode, C.python) },
  { extension: 'rs', icon: withColor(FileCode, C.rust) },
  { extension: 'go', icon: withColor(FileCode, C.go) },
  { extension: 'java', icon: withColor(FileCode, C.java) },
  { extension: 'kt', icon: withColor(FileCode, C.kotlin) },
  { extension: 'kts', icon: withColor(FileCode, C.kotlin) },
  { extension: 'rb', icon: withColor(FileCode, C.ruby) },
  { extension: 'php', icon: withColor(FileCode, C.php) },
  { extension: 'swift', icon: withColor(FileCode, C.swift) },
  { extension: 'c', icon: withColor(FileCode, C.c) },
  { extension: 'cc', icon: withColor(FileCode, C.c) },
  { extension: 'cpp', icon: withColor(FileCode, C.c) },
  { extension: 'cxx', icon: withColor(FileCode, C.c) },
  { extension: 'h', icon: withColor(FileCode, C.c) },
  { extension: 'hpp', icon: withColor(FileCode, C.c) },
  { extension: 'cs', icon: withColor(FileCode, C.csharp) },
  { extension: 'vue', icon: withColor(FileCode, C.vue) },
  { extension: 'svelte', icon: withColor(FileCode, C.svelte) },
  { extension: 'astro', icon: withColor(FileCode, C.svelte) },
  { extension: 'dart', icon: withColor(FileCode, C.ts) },
  { extension: 'scala', icon: withColor(FileCode, C.java) },
  { extension: 'clj', icon: withColor(FileCode, C.csharp) },
  { extension: 'lua', icon: withColor(FileCode, C.binary) },
  { extension: 'erl', icon: withColor(FileCode, C.ruby) },
  { extension: 'ex', icon: withColor(FileCode, C.kotlin) },
  { extension: 'exs', icon: withColor(FileCode, C.kotlin) },
  { extension: 'hs', icon: withColor(FileCode, C.csharp) },
  { extension: 'nim', icon: withColor(FileCode, C.python) },
  { extension: 'zig', icon: withColor(FileCode, C.archive) },
  { extension: 'sol', icon: withColor(FileCode, C.config) },
  { extension: 'r', icon: withColor(FileCode, C.go) },

  // Markup / data
  { extension: 'html', icon: withColor(FileCode, C.html) },
  { extension: 'htm', icon: withColor(FileCode, C.html) },
  { extension: 'xhtml', icon: withColor(FileCode, C.html) },
  { extension: 'xml', icon: withColor(FileCode, C.config) },
  { extension: 'json', icon: withColor(FileJson, C.json) },
  { extension: 'json5', icon: withColor(FileJson, C.json) },
  { extension: 'jsonc', icon: withColor(FileJson, C.json) },
  { extension: 'gql', icon: withColor(FileBraces, C.react) },
  { extension: 'graphql', icon: withColor(FileBraces, C.react) },
  { extension: 'proto', icon: withColor(FileBraces, C.config) },

  // Styles
  { extension: 'css', icon: withColor(FileType, C.css) },
  { extension: 'sass', icon: withColor(FileType, C.sass) },
  { extension: 'scss', icon: withColor(FileType, C.sass) },
  { extension: 'less', icon: withColor(FileType, C.css) },

  // Docs
  { extension: 'md', icon: withColor(FileText, C.markdown) },
  { extension: 'mdx', icon: withColor(FileText, C.markdown) },
  { extension: 'rst', icon: withColor(FileText, C.text) },
  { extension: 'adoc', icon: withColor(FileText, C.text) },
  { extension: 'tex', icon: withColor(FileText, C.text) },
  { extension: 'txt', icon: withColor(FileText, C.text) },
  { extension: 'log', icon: withColor(FileText, C.text) },
  { extension: 'rtf', icon: withColor(FileText, C.text) },
  { extension: 'doc', icon: withColor(FileText, C.ts) },
  { extension: 'docx', icon: withColor(FileText, C.ts) },
  { extension: 'pdf', icon: withColor(FileText, C.video) },

  // Config files
  { extension: 'yaml', icon: withColor(FileSliders, C.yaml) },
  { extension: 'yml', icon: withColor(FileSliders, C.yaml) },
  { extension: 'toml', icon: withColor(FileSliders, C.toml) },
  { extension: 'ini', icon: withColor(FileSliders, C.config) },
  { extension: 'conf', icon: withColor(FileSliders, C.config) },
  { extension: 'cfg', icon: withColor(FileSliders, C.config) },
  { extension: 'properties', icon: withColor(FileSliders, C.config) },
  { extension: 'hcl', icon: withColor(FileSliders, C.config) },
  { extension: 'tf', icon: withColor(FileSliders, C.config) },
  { extension: 'tfvars', icon: withColor(FileSliders, C.config) },

  // Shell
  { extension: 'sh', icon: withColor(FileTerminal, C.shell) },
  { extension: 'bash', icon: withColor(FileTerminal, C.shell) },
  { extension: 'zsh', icon: withColor(FileTerminal, C.shell) },
  { extension: 'fish', icon: withColor(FileTerminal, C.shell) },
  { extension: 'bat', icon: withColor(FileTerminal, C.shell) },
  { extension: 'cmd', icon: withColor(FileTerminal, C.shell) },
  { extension: 'ps1', icon: withColor(FileTerminal, C.shell) },
  { extension: 'nu', icon: withColor(FileTerminal, C.shell) },

  // Images
  { extension: 'png', icon: withColor(FileImage, C.image) },
  { extension: 'jpg', icon: withColor(FileImage, C.image) },
  { extension: 'jpeg', icon: withColor(FileImage, C.image) },
  { extension: 'gif', icon: withColor(FileImage, C.image) },
  { extension: 'svg', icon: withColor(FileImage, C.image) },
  { extension: 'webp', icon: withColor(FileImage, C.image) },
  { extension: 'avif', icon: withColor(FileImage, C.image) },
  { extension: 'ico', icon: withColor(FileImage, C.image) },
  { extension: 'bmp', icon: withColor(FileImage, C.image) },
  { extension: 'tif', icon: withColor(FileImage, C.image) },
  { extension: 'tiff', icon: withColor(FileImage, C.image) },
  { extension: 'heic', icon: withColor(FileImage, C.image) },
  { extension: 'psd', icon: withColor(FileImage, C.image) },
  { extension: 'ai', icon: withColor(FileImage, C.image) },
  { extension: 'eps', icon: withColor(FileImage, C.image) },

  // Audio / Video
  { extension: 'mp3', icon: withColor(FileMusic, C.audio) },
  { extension: 'wav', icon: withColor(FileMusic, C.audio) },
  { extension: 'flac', icon: withColor(FileMusic, C.audio) },
  { extension: 'ogg', icon: withColor(FileMusic, C.audio) },
  { extension: 'm4a', icon: withColor(FileMusic, C.audio) },
  { extension: 'opus', icon: withColor(FileMusic, C.audio) },
  { extension: 'aac', icon: withColor(FileMusic, C.audio) },
  { extension: 'mp4', icon: withColor(FileVideo, C.video) },
  { extension: 'mov', icon: withColor(FileVideo, C.video) },
  { extension: 'avi', icon: withColor(FileVideo, C.video) },
  { extension: 'mkv', icon: withColor(FileVideo, C.video) },
  { extension: 'webm', icon: withColor(FileVideo, C.video) },
  { extension: 'm4v', icon: withColor(FileVideo, C.video) },
  { extension: 'mpeg', icon: withColor(FileVideo, C.video) },
  { extension: 'mpg', icon: withColor(FileVideo, C.video) },

  // Archives
  { extension: 'zip', icon: withColor(FileArchive, C.archive) },
  { extension: 'tar', icon: withColor(FileArchive, C.archive) },
  { extension: 'tar.gz', icon: withColor(FileArchive, C.archive) },
  { extension: 'tar.bz2', icon: withColor(FileArchive, C.archive) },
  { extension: 'tar.xz', icon: withColor(FileArchive, C.archive) },
  { extension: 'tgz', icon: withColor(FileArchive, C.archive) },
  { extension: 'tbz2', icon: withColor(FileArchive, C.archive) },
  { extension: 'gz', icon: withColor(FileArchive, C.archive) },
  { extension: 'bz2', icon: withColor(FileArchive, C.archive) },
  { extension: 'xz', icon: withColor(FileArchive, C.archive) },
  { extension: 'rar', icon: withColor(FileArchive, C.archive) },
  { extension: '7z', icon: withColor(FileArchive, C.archive) },
  { extension: 'iso', icon: withColor(FileArchive, C.archive) },
  { extension: 'dmg', icon: withColor(FileArchive, C.archive) },
  { extension: 'br', icon: withColor(FileArchive, C.archive) },

  // Fonts
  { extension: 'woff', icon: withColor(FileType, C.font) },
  { extension: 'woff2', icon: withColor(FileType, C.font) },
  { extension: 'ttf', icon: withColor(FileType, C.font) },
  { extension: 'otf', icon: withColor(FileType, C.font) },
  { extension: 'eot', icon: withColor(FileType, C.font) },

  // Databases / data
  { extension: 'db', icon: withColor(Database, C.database) },
  { extension: 'sql', icon: withColor(Database, C.database) },
  { extension: 'sqlite', icon: withColor(Database, C.database) },
  { extension: 'sqlite3', icon: withColor(Database, C.database) },
  { extension: 'duckdb', icon: withColor(Database, C.database) },
  { extension: 'prisma', icon: withColor(Database, C.database) },
  { extension: 'csv', icon: withColor(FileSpreadsheet, C.spreadsheet) },
  { extension: 'tsv', icon: withColor(FileSpreadsheet, C.spreadsheet) },
  { extension: 'xls', icon: withColor(FileSpreadsheet, C.spreadsheet) },
  { extension: 'xlsx', icon: withColor(FileSpreadsheet, C.spreadsheet) },
  { extension: 'ods', icon: withColor(FileSpreadsheet, C.spreadsheet) },

  // Misc
  { extension: 'diff', icon: withColor(FileDiff, C.diff) },
  { extension: 'patch', icon: withColor(FileDiff, C.diff) },
  { extension: 'ipynb', icon: withColor(FileChartColumn, C.python) },
  { extension: 'mmd', icon: withColor(FileChartColumn, C.config) },
  { extension: 'ppt', icon: withColor(FileChartColumn, C.video) },
  { extension: 'pptx', icon: withColor(FileChartColumn, C.video) },
  { extension: 'gradle', icon: withColor(FileCog, C.config) },
  { extension: 'lock', icon: withColor(FileLock, C.lock) },
  { extension: 'pem', icon: withColor(FileKey, C.key) },
  { extension: 'pub', icon: withColor(FileKey, C.key) },
  { extension: 'crt', icon: withColor(FileKey, C.key) },
  { extension: 'cer', icon: withColor(FileKey, C.key) },
  { extension: 'asc', icon: withColor(FileKey, C.key) },
  { extension: 'gpg', icon: withColor(FileKey, C.key) },
  { extension: 'key', icon: withColor(FileKey, C.key) },
  { extension: 'p12', icon: withColor(FileLock, C.lock) },
  { extension: 'pfx', icon: withColor(FileLock, C.lock) },
  { extension: 'obj', icon: withColor(FileAxis3D, C.config) },
  { extension: 'stl', icon: withColor(FileAxis3D, C.config) },
  { extension: 'glb', icon: withColor(FileAxis3D, C.config) },
  { extension: 'gltf', icon: withColor(FileAxis3D, C.config) },
  { extension: 'fbx', icon: withColor(FileAxis3D, C.config) },
  { extension: 'blend', icon: withColor(FileAxis3D, C.config) }
]

export const colorClassicIconTheme: IconTheme = {
  id: 'color-classic',
  name: 'Color Classic',
  description:
    'Same icon shapes as Default, but each file type is tinted by language — TS blue, JSON yellow, images purple, archives amber, etc.',
  monochrome: false,
  defaultFileIcon: withColor(File, C.defaultFile),
  defaultFolder: {
    closed: withColor(Folder, C.folder),
    open: withColor(FolderOpen, C.folderOpen)
  },
  fileRules,
  folderRules: []
}
