import type { ConnectPanePtySession } from './connect-pane-pty-session'

export type ReattachPayloadSession = Pick<
  ConnectPanePtySession,
  | 'applyColdRestoreAgentResumeStartup'
  | 'applySnapshotKittyKeyboardModes'
  | 'buildColdRestoreAgentResumeStartup'
  | 'cacheKey'
  | 'cancelStartupDraftPasteDelivery'
  | 'clearRegisteredStartupLaunchConfig'
  | 'clearSleepingRecordAfterColdRestoreSpawn'
  | 'consumeRestoredViewportBlankingMarker'
  | 'createReattachGridPush'
  | 'isPaneOnAlternateScreen'
  | 'kittyKeyboardModes'
  | 'pane'
  | 'pendingStartupCommand'
  | 'pendingReattachFit'
  | 'reattachReplayResetSequence'
  | 'recordRendererOrderedSeq'
  | 'rememberReattachPayloadAgentSignal'
  | 'schedulePendingStartupCommandDelivery'
  | 'sendFocusedReattachFocusInAfterReplay'
  | 'setRestoredSnapshotBaseline'
  | 'shouldPreserveAgentReattachModes'
  | 'showSessionRestoredBanner'
  | 'suppressStructuralReplayPtyResize'
  | 'startupInjectTimer'
  | 'transport'
  | 'writeFreshShellViewportBlanking'
  | 'writeReplayData'
>
