import type { CliInstallStatus } from '../../shared/cli-install-types';
type CliInstallerOptions = {
    platform?: NodeJS.Platform;
    isPackaged?: boolean;
    userDataPath?: string;
    resourcesPath?: string;
    execPath?: string;
    appPath?: string;
    homePath?: string;
    localAppDataPath?: string;
    processPathEnv?: string | null;
    commandPathOverride?: string | null;
    privilegedRunner?: (command: string) => Promise<void>;
    userPathReader?: () => Promise<string | null>;
    userPathWriter?: (value: string) => Promise<void>;
};
export declare class CliInstaller {
    private readonly platform;
    private readonly isPackaged;
    private readonly userDataPath;
    private readonly resourcesPath;
    private readonly execPathValue;
    private readonly appPathValue;
    private readonly homePath;
    private readonly localAppDataPath;
    private readonly processPathEnv;
    private readonly commandPathOverride;
    private readonly privilegedRunner;
    private readonly userPathReader;
    private readonly userPathWriter;
    constructor(options?: CliInstallerOptions);
    getStatus(): Promise<CliInstallStatus>;
    install(): Promise<CliInstallStatus>;
    remove(): Promise<CliInstallStatus>;
    private resolveInstallSpec;
    private resolveCommandPath;
    private resolveLauncherPath;
    private installSymlink;
    private removeSymlink;
    private installWindowsWrapper;
    private inspectSymlink;
    private inspectWindowsWrapper;
    private buildStatus;
    private isPathConfigured;
    private withPathInfo;
    private ensureWindowsPathEntry;
    private removeWindowsPathEntry;
}
export declare function getBundledLauncherPath(platform: NodeJS.Platform, resourcesPath: string): string | null;
export {};
