// Tree-sitter definition queries, validated per grammar against @vscode/tree-sitter-wasm.
// Each query captures definition names as @name (functions, types, methods, top-level consts).

export type GrammarName =
  | 'typescript'
  | 'tsx'
  | 'javascript'
  | 'python'
  | 'go'
  | 'rust'
  | 'java'
  | 'c-sharp'
  | 'cpp'
  | 'ruby'
  | 'php'
  | 'bash'

export const DEFINITION_QUERIES: Record<GrammarName, string> = {
  typescript:
    '; Function declarations (incl. generators)\n(function_declaration\n  name: (identifier) @name)\n\n(generator_function_declaration\n  name: (identifier) @name)\n\n; Ambient function declarations: declare function foo(): void\n(function_signature\n  name: (identifier) @name)\n\n; Classes\n(class_declaration\n  name: (type_identifier) @name)\n\n(abstract_class_declaration\n  name: (type_identifier) @name)\n\n; Interfaces\n(interface_declaration\n  name: (type_identifier) @name)\n\n; Type aliases\n(type_alias_declaration\n  name: (type_identifier) @name)\n\n; Enums\n(enum_declaration\n  name: (identifier) @name)\n\n; Namespaces / internal modules\n(internal_module\n  name: (identifier) @name)\n\n(module\n  name: (identifier) @name)\n\n; Methods and method signatures\n(method_definition\n  name: (property_identifier) @name)\n\n(method_signature\n  name: (property_identifier) @name)\n\n(abstract_method_signature\n  name: (property_identifier) @name)\n\n; Module/top-level constant & variable definitions (not function-body locals).\n; Anchored to program or export_statement at the top level.\n(program\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n\n(program\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n\n(export_statement\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n\n(export_statement\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name)))',
  tsx: '; Function declarations\n(function_declaration\n  name: (identifier) @name)\n\n; Generator function declarations\n(generator_function_declaration\n  name: (identifier) @name)\n\n; Class declarations\n(class_declaration\n  name: (type_identifier) @name)\n\n; Abstract class declarations\n(abstract_class_declaration\n  name: (type_identifier) @name)\n\n; Interface declarations\n(interface_declaration\n  name: (type_identifier) @name)\n\n; Type alias declarations\n(type_alias_declaration\n  name: (type_identifier) @name)\n\n; Enum declarations\n(enum_declaration\n  name: (identifier) @name)\n\n; Namespace / module declarations\n(internal_module\n  name: (identifier) @name)\n(module\n  name: (identifier) @name)\n\n; Methods\n(method_definition\n  name: (property_identifier) @name)\n\n; Abstract methods (interfaces / abstract classes)\n(method_signature\n  name: (property_identifier) @name)\n(abstract_method_signature\n  name: (property_identifier) @name)\n\n; Class fields\n(public_field_definition\n  name: (property_identifier) @name)\n\n; Top-level const/let/var bindings (including arrow-function and component consts)\n(program\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n(program\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n\n; Top-level bindings under an export statement\n(program\n  (export_statement\n    (lexical_declaration\n      (variable_declarator\n        name: (identifier) @name))))\n(program\n  (export_statement\n    (variable_declaration\n      (variable_declarator\n        name: (identifier) @name))))',
  javascript:
    ';; Function declarations\n(function_declaration\n  name: (identifier) @name)\n\n;; Generator function declarations\n(generator_function_declaration\n  name: (identifier) @name)\n\n;; Class declarations\n(class_declaration\n  name: (identifier) @name)\n\n;; Methods inside classes\n(method_definition\n  name: (property_identifier) @name)\n\n;; Top-level const/let/var bindings (not function-body locals)\n(program\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n(program\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n(export_statement\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name)))\n(export_statement\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name)))',
  python:
    ';; Top-level function definitions\n(module (function_definition name: (identifier) @name))\n\n;; Class definitions\n(class_definition name: (identifier) @name)\n\n;; Methods (functions nested directly inside a class body)\n(class_definition body: (block (function_definition name: (identifier) @name)))\n\n;; Decorated functions/methods\n(decorated_definition definition: (function_definition name: (identifier) @name))\n\n;; Decorated classes\n(decorated_definition definition: (class_definition name: (identifier) @name))\n\n;; Module-level constant / variable / type-alias definitions\n;; (covers `X = ...` and annotated `X: T = ...` / `X: T`)\n(module (expression_statement (assignment left: (identifier) @name)))',
  go: '; Functions\n(function_declaration\n  name: (identifier) @name)\n\n; Methods\n(method_declaration\n  name: (field_identifier) @name)\n\n; Type definitions: struct / interface / defined type, etc.\n(type_declaration\n  (type_spec\n    name: (type_identifier) @name))\n(type_declaration\n  (type_alias\n    name: (type_identifier) @name))\n\n; Top-level const definitions\n(const_declaration\n  (const_spec\n    name: (identifier) @name))\n\n; Top-level var definitions (single and grouped blocks)\n(var_declaration\n  (var_spec\n    name: (identifier) @name))\n(var_declaration\n  (var_spec_list\n    (var_spec\n      name: (identifier) @name)))',
  rust: '; Functions and methods (function_item covers both free fns and impl/trait methods)\n(function_item name: (identifier) @name)\n\n; Trait method signatures without bodies\n(function_signature_item name: (identifier) @name)\n\n; Structs, enums, unions, traits\n(struct_item name: (type_identifier) @name)\n(enum_item name: (type_identifier) @name)\n(union_item name: (type_identifier) @name)\n(trait_item name: (type_identifier) @name)\n\n; Type aliases\n(type_item name: (type_identifier) @name)\n\n; Modules\n(mod_item name: (identifier) @name)\n\n; Top-level / module constants and statics\n(const_item name: (identifier) @name)\n(static_item name: (identifier) @name)\n\n; Declarative macros\n(macro_definition name: (identifier) @name)',
  java: '; classes\n(class_declaration\n  name: (identifier) @name)\n\n; interfaces\n(interface_declaration\n  name: (identifier) @name)\n\n; annotation type declarations (@interface)\n(annotation_type_declaration\n  name: (identifier) @name)\n\n; enums\n(enum_declaration\n  name: (identifier) @name)\n\n; records\n(record_declaration\n  name: (identifier) @name)\n\n; methods\n(method_declaration\n  name: (identifier) @name)\n\n; constructors\n(constructor_declaration\n  name: (identifier) @name)\n\n; enum constants\n(enum_constant\n  name: (identifier) @name)\n\n; annotation type element (e.g. String value();)\n(annotation_type_element_declaration\n  name: (identifier) @name)\n\n; fields / top-level constant or variable definitions\n(field_declaration\n  declarator: (variable_declarator\n    name: (identifier) @name))',
  'c-sharp':
    ';; namespaces\n(namespace_declaration\n  name: (_) @name) @definition.namespace\n\n;; class / struct / interface / enum / record\n(class_declaration\n  name: (identifier) @name) @definition.class\n\n(struct_declaration\n  name: (identifier) @name) @definition.struct\n\n(interface_declaration\n  name: (identifier) @name) @definition.interface\n\n(enum_declaration\n  name: (identifier) @name) @definition.enum\n\n(record_declaration\n  name: (identifier) @name) @definition.record\n\n;; delegates (function-type definitions)\n(delegate_declaration\n  name: (identifier) @name) @definition.delegate\n\n;; methods\n(method_declaration\n  name: (identifier) @name) @definition.method\n\n;; constructors\n(constructor_declaration\n  name: (identifier) @name) @definition.method\n\n;; properties\n(property_declaration\n  name: (identifier) @name) @definition.property\n\n;; enum members\n(enum_member_declaration\n  name: (identifier) @name) @definition.enum_member\n\n;; fields and constants (module/type-level variable definitions)\n(field_declaration\n  (variable_declaration\n    (variable_declarator\n      (identifier) @name))) @definition.field',
  cpp: '; Functions (free functions and out-of-class method definitions)\n(function_definition\n  declarator: [\n    (function_declarator declarator: (identifier) @name)\n    (function_declarator declarator: (field_identifier) @name)\n    (function_declarator declarator: (qualified_identifier name: (identifier) @name))\n    (pointer_declarator (function_declarator declarator: (identifier) @name))\n    (reference_declarator (function_declarator declarator: (identifier) @name))\n  ])\n\n; Function/method declarations (prototypes inside classes, pure virtuals)\n(declaration\n  declarator: (function_declarator\n    declarator: [\n      (identifier) @name\n      (field_identifier) @name\n      (qualified_identifier name: (identifier) @name)\n    ]))\n\n; Field-declared methods inside a class/struct body\n(field_declaration\n  declarator: (function_declarator\n    declarator: [\n      (field_identifier) @name\n      (identifier) @name\n    ]))\n\n; Classes / structs / unions\n(class_specifier name: (type_identifier) @name)\n(struct_specifier name: (type_identifier) @name)\n(union_specifier name: (type_identifier) @name)\n\n; Enums (plain and scoped)\n(enum_specifier name: (type_identifier) @name)\n\n; Type aliases\n(type_definition declarator: (type_identifier) @name)\n(alias_declaration name: (type_identifier) @name)\n\n; Top-level / namespace-level constant and variable definitions\n(translation_unit\n  (declaration\n    declarator: (init_declarator declarator: (identifier) @name)))\n(namespace_definition\n  body: (declaration_list\n    (declaration\n      declarator: (init_declarator declarator: (identifier) @name))))',
  ruby: '; Top-level and instance method definitions (functions/methods)\n(method\n  name: [(identifier) (constant) (operator) (setter)] @name)\n\n; Singleton methods (def self.foo / def obj.foo)\n(singleton_method\n  name: [(identifier) (constant) (operator) (setter)] @name)\n\n; Class definitions (incl. qualified names like Foo::Bar)\n(class\n  name: [(constant) (scope_resolution)] @name)\n\n; Module definitions (incl. qualified names like App::Web)\n(module\n  name: [(constant) (scope_resolution)] @name)\n\n; Top-level constant assignments (e.g. MAX_SIZE = 100, Config = Struct.new(...))\n(assignment\n  left: (constant) @name)\n\n; Constant assignments via scope resolution (e.g. Foo::BAR = 1)\n(assignment\n  left: (scope_resolution\n    name: (constant) @name))',
  php: '; Function declarations\n(function_definition\n  name: (name) @name)\n\n; Method declarations\n(method_declaration\n  name: (name) @name)\n\n; Class declarations\n(class_declaration\n  name: (name) @name)\n\n; Interface declarations\n(interface_declaration\n  name: (name) @name)\n\n; Trait declarations\n(trait_declaration\n  name: (name) @name)\n\n; Enum declarations\n(enum_declaration\n  name: (name) @name)\n\n; const TOP_CONST = ...; at top level and class consts\n(const_declaration\n  (const_element\n    (name) @name))\n\n; define(\'CONST\', ...)  \u2014 only the first string argument is the const name\n(function_call_expression\n  function: (name) @_def\n  arguments: (arguments\n    .\n    (argument\n      (string (string_content) @name)))\n  (#eq? @_def "define"))\n\n; Enum cases\n(enum_case\n  name: (name) @name)',
  bash: ';; function definitions (both `name() { }` and `function name { }`)\n(function_definition\n  name: (word) @name)\n\n;; top-level constant / variable definitions (direct children of the program)\n(program\n  (variable_assignment\n    name: (variable_name) @name))\n\n;; declare / readonly / export / local / typeset declarations\n(declaration_command\n  (variable_assignment\n    name: (variable_name) @name))'
}
