export const MOBILE_WEB_BRIDGE_MAX_MESSAGE_BYTES = 640 * 1024
export const MOBILE_WEB_BRIDGE_ENVELOPE_RESERVE_BYTES = 40 * 1024
export const MOBILE_WEB_BRIDGE_MAX_OPERATION_BYTES =
  MOBILE_WEB_BRIDGE_MAX_MESSAGE_BYTES - MOBILE_WEB_BRIDGE_ENVELOPE_RESERVE_BYTES
export const MOBILE_WEB_BRIDGE_MAX_PENDING_REQUESTS = 64
export const MOBILE_WEB_BRIDGE_MAX_SUBSCRIPTIONS = 32
export const MOBILE_WEB_BRIDGE_MAX_GRANTS = 256
