import { createRequire } from 'node:module'
const require=createRequire('/Users/m4air/orca/workspaces/orca/pr25658-review-qa-2/package.json'); const { chromium }=require('@playwright/test')
import fs from 'node:fs'
const base='/Users/m4air/orca-qa/pr-25658/remote', report={sha:'354c3efb70d0214bf8a9bdb44aab7baf50d4ae65',results:[],screenshots:[]}
const browser=await chromium.connectOverCDP('http://127.0.0.1:9441'); const page=browser.contexts().flatMap(x=>x.pages())[0]
const save=()=>fs.writeFileSync(`${base}/final-geometry.json`,JSON.stringify(report,null,2)); const rec=async(n)=>{report.results.push({name:n,state:await page.evaluate(()=>{const p=document.querySelector('[data-native-chat-appearance-preview]'),b=p?.getBoundingClientRect(),q=[...p?.querySelectorAll('p')??[]].at(-1)?.getBoundingClientRect();return {inert:p?.hasAttribute('inert'),preview:b&&{width:Math.round(b.width),height:Math.round(b.height)},closing:q&&{top:Math.round(q.top-b.top),bottom:Math.round(q.bottom-b.top),inside:q.bottom<=b.bottom},sample:p?.innerText,links:p?.querySelectorAll('a').length}})});save()}
const shot=async n=>{const path=`${base}/shots/final-${n}.png`;await page.screenshot({path,animations:'disabled'});report.screenshots.push(path);await rec(`shot-${n}`)}
const click=async l=>{await l.scrollIntoViewIfNeeded();await l.click();await page.waitForTimeout(100)}
await fs.promises.mkdir(`${base}/shots`,{recursive:true}); await page.setViewportSize({width:1480,height:1500});
const id=await page.evaluate(()=>window.api.app.getIdentity());if(id.devRepoRoot!='/Users/m4air/orca/workspaces/orca/pr25658-review-qa-2')throw Error(JSON.stringify(id));report.identity=id
await page.evaluate(()=>{const s=window.__store.getState();s.openSettingsTarget({pane:'appearance',repoId:null});s.openSettingsPage()}); await page.locator('[data-native-chat-appearance-preview]').waitFor()
for(const theme of ['Dark','Light']){await click(page.getByText(theme,{exact:true}).first());await rec(`theme-${theme}`);await shot(`theme-${theme.toLowerCase()}`)}
const width=page.locator('[role=radio]').filter({hasText:'Comfortable'}).last();for(const n of ['Comfortable','Wide','Full']){await click(page.locator('[role=radio]').filter({hasText:n}).last());await rec(`width-${n}`)}
const slider=page.locator('[role=slider]').last(), box=await slider.boundingBox(); const before=await slider.getAttribute('aria-valuenow');await page.mouse.move(box.x+5,box.y+5);await page.mouse.down();await page.mouse.move(box.x+box.width-5,box.y+5,{steps:8});report.draft={before,during:await slider.getAttribute('aria-valuenow')};await page.mouse.up();await page.waitForFunction((v)=>document.querySelector('[role=slider]')?.getAttribute('aria-valuenow')===v,await slider.getAttribute('aria-valuenow'));report.draft.after=await slider.getAttribute('aria-valuenow');await slider.press('ArrowLeft');await slider.press('ArrowRight');report.draft.focused=await page.evaluate(()=>document.activeElement?.getAttribute('role'));await rec('contrast')
for(const l of ['en','es','fr','ja','ko','zh']){await page.evaluate(async x=>window.__store.getState().updateSettings({uiLanguage:x,nativeChatAppearance:{fontSize:20,codeFontSize:18}}),l);await page.waitForTimeout(400);await rec(`locale-${l}-20-18`);await shot(`locale-${l}`)}
save();console.log(JSON.stringify(report))
