import React from 'react'
import { View, StyleSheet, useWindowDimensions } from 'react-native'
import type { RpcClient } from '../transport/rpc-client'
import { clampPositionToViewport, tickRoam, type Position } from '../../../src/shared/pet-roam'
import { edgeAtNormalized } from './pet-edge'
import { MobilePetSprite } from './MobilePetSprite'
import { petSheetFor } from './pet-sheets'
import petFrames from './pet-frames.generated.json'
import { useMobilePetPresence } from './use-mobile-pet-presence'

// The pet, on the phone (P3 + P4).
//
// Roam comes from src/shared/pet-roam — the SAME module the desktop runs — so
// the creature moves identically either side of a handoff. Frames come from a
// build-time manifest generated by the desktop's own detector, because React
// Native has no canvas to detect them on device.

const PET_SIZE = 72
const FRAME_MS = 140
/** Roam ticks at ~30fps rather than 60: the pet is decoration, and on a phone
 *  the battery cost of a 60fps timer is not worth motion nobody can perceive. */
const TICK_MS = 33

type PetFrameManifest = Record<
  string,
  {
    displayName: string
    sheet: string
    width: number
    height: number
    frames: { x: number; y: number; w: number; h: number }[]
  }
>

const FRAMES = petFrames as PetFrameManifest

/** Every pet this build has sheets for. Reported to the authority so it never
 *  routes a creature here that this bundle cannot draw. */
const RENDERABLE_PET_IDS = Object.keys(FRAMES)

export function MobilePetOverlay({
  client,
  enabled = true
}: {
  client: RpcClient | null
  enabled?: boolean
}): React.JSX.Element | null {
  const { width, height } = useWindowDimensions()
  const presence = useMobilePetPresence({
    client,
    enabled,
    renderablePetIds: RENDERABLE_PET_IDS
  })

  // Identity comes from the authority, NEVER a local default. The old fallback
  // to Object.keys(FRAMES)[0] — alphabetically 'apupepe' — is exactly why a
  // gandalf walking off the desktop arrived here as a pepe. Drawing nothing is
  // correct for a pet we cannot render; the authority also refuses to hand one
  // here, so this is belt-and-braces rather than a reachable blank screen.
  const resolvedId = presence.petId
  const entry = resolvedId ? FRAMES[resolvedId] : undefined
  const sheet = resolvedId ? petSheetFor(resolvedId) : null

  const viewport = React.useMemo(
    () => ({ width: Math.max(1, width), height: Math.max(1, height) }),
    [width, height]
  )

  const [position, setPosition] = React.useState<Position>(() => ({
    x: viewport.width / 2,
    y: viewport.height / 2
  }))
  const [frameIndex, setFrameIndex] = React.useState(0)
  const [facing, setFacing] = React.useState<'left' | 'right'>('right')
  const targetRef = React.useRef<Position | null>(null)
  const positionRef = React.useRef(position)
  positionRef.current = position

  // Adopt the authority's arrival position so the pet walks in from the edge it
  // crossed rather than appearing mid-screen.
  React.useEffect(() => {
    if (!presence.holdsPet || presence.enteredFromEdge === null) {
      return
    }
    setPosition(
      clampPositionToViewport(
        {
          x: presence.position.x * Math.max(0, viewport.width - PET_SIZE),
          y: presence.position.y * Math.max(0, viewport.height - PET_SIZE)
        },
        PET_SIZE,
        viewport
      )
    )
    setFacing(presence.facing)
    presence.acknowledgeEntry()
  }, [presence, viewport])

  // Roam + frame advance. One timer drives both so the sprite's legs and its
  // travel cannot fall out of step.
  React.useEffect(() => {
    if (!presence.holdsPet || !entry) {
      return
    }
    const frameCount = entry.frames.length
    let last = Date.now()
    let sinceFrame = 0
    const timer = setInterval(() => {
      const now = Date.now()
      const dt = Math.min(64, now - last)
      last = now

      const result = tickRoam({
        position: positionRef.current,
        target: targetRef.current,
        size: PET_SIZE,
        viewport,
        dtMs: dt,
        paused: false
      })
      targetRef.current = result.target
      if (result.position.x !== positionRef.current.x) {
        setFacing(result.position.x > positionRef.current.x ? 'right' : 'left')
      }
      setPosition(result.position)

      sinceFrame += dt
      if (sinceFrame >= FRAME_MS) {
        sinceFrame = 0
        setFrameIndex((current) => (current + 1) % frameCount)
      }
    }, TICK_MS)
    return () => clearInterval(timer)
  }, [presence.holdsPet, entry, viewport])

  // Walk-off: reaching an edge with somewhere to go asks the authority to hand
  // the pet on. The authority ignores it unless this phone holds the pet.
  React.useEffect(() => {
    if (!presence.holdsPet || !presence.canHandOff) {
      return
    }
    const normalized = {
      x: viewport.width > PET_SIZE ? position.x / (viewport.width - PET_SIZE) : 0.5,
      y: viewport.height > PET_SIZE ? position.y / (viewport.height - PET_SIZE) : 0.5
    }
    const edge = edgeAtNormalized(normalized)
    if (edge) {
      presence.reportExit(edge, normalized)
    }
  }, [presence, position, viewport])

  // Exclusive: when the pet is on another surface, this phone draws nothing.
  if (!presence.holdsPet || !entry || !sheet) {
    return null
  }
  const frame = entry.frames[frameIndex % entry.frames.length]
  if (!frame) {
    return null
  }

  return (
    // pointerEvents none throughout: the pet floats over real UI and must never
    // eat a tap meant for a workspace row.
    <View style={styles.layer} pointerEvents="none">
      <View style={[styles.pet, { left: position.x, top: position.y }]}>
        <MobilePetSprite
          source={sheet}
          frame={frame}
          sheetWidth={entry.width}
          sheetHeight={entry.height}
          size={PET_SIZE}
          facing={facing}
        />
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  layer: { ...StyleSheet.absoluteFillObject },
  pet: { position: 'absolute' }
})
