import type { AgentExitRetirementDisposition } from '../../shared/agent-exit-retirement'

// Why 1 s then 5 s: covers a renderer reload or relay blip without becoming a poll.
export const AGENT_EXIT_RETIREMENT_RETRY_DELAYS_MS = [1_000, 5_000] as const
export const AGENT_EXIT_RETIREMENT_DEADLINE_MS = 30_000

export type AgentExitRetirementOutcome =
  | AgentExitRetirementDisposition
  /** Every attempt threw or the deadline passed; reported once, never retried again. */
  | 'failed'
  /** The run, PTY or authority it was for is gone or replaced. */
  | 'abandoned'

export type AgentExitRetirementOperation = {
  /** A renderer-ready signal: spend the next remaining attempt now instead of waiting. */
  nudge: () => void
  cancel: () => void
}

/**
 * One proven exit's finite retirement: an attempt now plus retries at 1 s and 5 s inside 30 s,
 * one in flight at a time. Dies on any disposition (only `applied` mutated anything), when it is
 * no longer owed, or at the deadline. Never a send latch and never regenerated by itself.
 */
export function startAgentExitRetirementOperation(args: {
  attempt: () => Promise<AgentExitRetirementDisposition>
  stillOwed: () => boolean
  onSettled: (outcome: AgentExitRetirementOutcome, error?: unknown) => void
  now?: () => number
  setTimer?: (callback: () => void, ms: number) => ReturnType<typeof setTimeout>
  clearTimer?: (handle: ReturnType<typeof setTimeout>) => void
}): AgentExitRetirementOperation {
  const now = args.now ?? Date.now
  const setTimer = args.setTimer ?? ((callback, ms) => setTimeout(callback, ms))
  const clearTimer = args.clearTimer ?? clearTimeout
  const deadline = now() + AGENT_EXIT_RETIREMENT_DEADLINE_MS
  let retriesUsed = 0
  let inFlight = false
  let settled = false
  let timer: ReturnType<typeof setTimeout> | null = null
  let lastError: unknown

  const settle = (outcome: AgentExitRetirementOutcome, error?: unknown): void => {
    if (settled) {
      return
    }
    settled = true
    if (timer) {
      clearTimer(timer)
      timer = null
    }
    args.onSettled(outcome, error)
  }

  const scheduleRetry = (): void => {
    const delay = AGENT_EXIT_RETIREMENT_RETRY_DELAYS_MS[retriesUsed]
    if (delay === undefined || now() + delay > deadline) {
      settle('failed', lastError)
      return
    }
    retriesUsed += 1
    const handle = setTimer(() => {
      timer = null
      run()
    }, delay)
    handle.unref?.()
    timer = handle
  }

  const run = (): void => {
    if (settled || inFlight) {
      return
    }
    if (!args.stillOwed()) {
      settle('abandoned')
      return
    }
    if (now() > deadline) {
      settle('failed', lastError)
      return
    }
    inFlight = true
    args.attempt().then(
      (disposition) => {
        inFlight = false
        settle(args.stillOwed() || disposition === 'applied' ? disposition : 'abandoned')
      },
      (error: unknown) => {
        inFlight = false
        lastError = error
        if (!settled) {
          scheduleRetry()
        }
      }
    )
  }

  run()
  return {
    nudge: () => {
      if (timer && !inFlight && !settled) {
        clearTimer(timer)
        timer = null
        run()
      }
    },
    cancel: () => settle('abandoned')
  }
}
