/* eslint-disable max-lines -- Why: this file contains a multi-line inline
   JS plugin source emitted into OpenCode's plugins directory as a single
   file; splitting the plugin source across TS modules would obscure the
   runtime artifact and scatter tightly coupled string-template logic. */
import { app } from 'electron'
import { join } from 'node:path'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  realpathSync,
  statSync,
  unlinkSync,
  writeFileSync
} from 'node:fs'
import { createHash } from 'node:crypto'
import { mirrorEntry, safeRemoveTree } from '../pty/overlay-mirror'

const ORCA_OPENCODE_PLUGIN_FILE = 'orca-opencode-status.js'
const OPENCODE_LEGACY_HOOKS_DIR = 'opencode-hooks'
const OPENCODE_OVERLAY_DIR = 'opencode-config-overlays'
const OPENCODE_SHARED_CONFIG_DIR = 'shared'
const OPENCODE_OVERLAY_MANIFEST_FILE = '.orca-opencode-overlay-manifest.json'

type OpenCodeOverlayManifest = {
  topLevelEntries: string[]
  pluginEntries: string[]
}

// Why: the id passed in by pty.ts's daemon path is a sessionId shaped like
// "<worktreeId>@@<uuid>" where worktreeId itself contains "::" and a
// filesystem path (slashes, colons). Earlier the id was a simple numeric
// counter, so rejecting anything with "/" or ":" was a safe guard against
// path traversal. After the daemon-parity refactor (#1148) the sessionId
// shape changed, and the old regex silently rejected every legitimate id,
// leaving OPENCODE_CONFIG_DIR unset and the plugin never loading.
//
// Keep an input-bounds guard (non-empty, bounded length) for defense in
// depth, and derive the on-disk directory name via hash so any caller's id —
// including ones containing path separators — produces a short, stable,
// filesystem-safe name. Hashing also eliminates path-traversal risk at the
// source: the directory name is always 32 hex chars, never a prefix/suffix
// of the caller's input.
// Why: 1024 is a generous sanity cap — daemon-shaped ids embed a worktree
// filesystem path plus "@@<uuid>", and this bound prevents pathological inputs
// from burning CPU in the SHA-256 step. Since the id is hashed anyway, 1024
// is decoupled from PATH_MAX.
function isUsableId(id: string): boolean {
  return typeof id === 'string' && id.length > 0 && id.length <= 1024
}

function toSafeDirName(id: string): string {
  // Why: SHA-256 truncated to 32 hex chars (128 bits) is ample for a
  // per-session directory name — collisions require ~2^64 concurrent sessions
  // to become likely, far beyond any real workload. Hex keeps the name
  // portable across all filesystems (no base64 padding, no `/`).
  return createHash('sha256').update(id).digest('hex').slice(0, 32)
}

export function getOpenCodePluginSource(): string {
  return getOpenCodeFamilyPluginSource('/hook/opencode')
}

export function getOpenCodeFamilyPluginSource(hookPathname: string): string {
  // Why: the plugin runs inside the OpenCode Node process and POSTs to the
  // unified agent-hooks server shared with Claude/Codex/Gemini. It reads the
  // same ORCA_PANE_KEY / ORCA_TAB_ID / ORCA_WORKTREE_ID / ORCA_AGENT_HOOK_*
  // env vars that Orca injects into every PTY, so OpenCode panes flow into
  // agentStatusByPaneKey via the same IPC path as every other agent. Event
  // mapping is done plugin-side (SessionBusy / SessionIdle / PermissionRequest)
  // so the server-side normalizer can keep its one-event-per-case switch shape.
  return [
    '// Why: process-lifetime guard so a recurring parse error on a malformed',
    "// endpoint file does not spam OpenCode's stderr once per hook post.",
    '// This guard lives inside the plugin source because the plugin runs in',
    "// OpenCode's Node process (not Orca's) and has no access to server.ts's",
    '// equivalent warnedVersions / warnedEnvs Sets.',
    'let warnedBadEndpoint = false;',
    '',
    '// Why: message.part.updated can fire many times per second during a',
    '// streaming assistant reply, and each post() calls resolveHookCoords()',
    '// which reads the endpoint file. The file only changes on Orca restart',
    '// (rare), so a stat+mtime check is substantially cheaper than a full',
    '// readFileSync+parse on every streamed part. On stat error we fall',
    '// through to parse so the fail-open behavior is preserved.',
    'let cachedEndpointKey = "";',
    'let cachedEndpointValues = null;',
    '',
    'function readEndpointFile() {',
    '  const path = process.env.ORCA_AGENT_HOOK_ENDPOINT;',
    '  if (!path) return null;',
    '  try {',
    '    const fs = require("fs");',
    '    try {',
    '      const stat = fs.statSync(path);',
    '      // Why: cache key combines mtime + size + inode. renameSync (used by',
    '      // writeEndpointFile on the Orca side) allocates a fresh inode on',
    '      // POSIX and a new Windows file ID on NTFS, so ino changes on every',
    '      // legitimate rewrite even when mtimeMs resolution is coarse and size',
    '      // happens to match.',
    '      const cacheKey = stat.mtimeMs + ":" + stat.size + ":" + stat.ino;',
    '      if (cacheKey === cachedEndpointKey && cachedEndpointValues) {',
    '        return cachedEndpointValues;',
    '      }',
    '      const contents = fs.readFileSync(path, "utf8");',
    '      const out = {};',
    '      for (const line of contents.split(/\\r?\\n/)) {',
    '        // Why: Windows endpoint.cmd uses `set KEY=VALUE`; Unix endpoint.env',
    '        // uses `KEY=VALUE`. Making `set ` optional lets the same parser',
    '        // handle both without platform detection in the plugin. Allow',
    '        // digits in the key for forward-compat with future ORCA_AGENT_HOOK_*',
    '        // names that may contain numerics, and strip a trailing CR so',
    '        // mixed-EOL files with lone `\\r` do not leak CR into the value.',
    '        const m = line.match(/^(?:set\\s+)?([A-Z0-9_]+)=(.*)$/);',
    '        if (m) out[m[1]] = m[2].replace(/\\r$/, "");',
    '      }',
    '      cachedEndpointKey = cacheKey;',
    '      cachedEndpointValues = out;',
    '      return out;',
    '    } catch (ioErr) {',
    '      // Why: any stat or read failure (file yanked mid-read, permission',
    '      // race, unlink between stat and readFileSync) must invalidate the',
    '      // cache so a transient failure does not lock in a stale parse for',
    '      // the remaining process lifetime; rethrow to the outer catch.',
    '      cachedEndpointKey = "";',
    '      cachedEndpointValues = null;',
    '      throw ioErr;',
    '    }',
    '  } catch (err) {',
    '    // Why: warn once per process if the file exists but is unreadable or',
    '    // malformed — a persistent, silently-swallowed parse error would',
    '    // otherwise leave the plugin falling back to stale process.env on',
    '    // every post with no signal. ENOENT / missing env var is the normal',
    '    // pre-install case; stay silent for it.',
    '    if (err && err.code !== "ENOENT" && !warnedBadEndpoint) {',
    '      warnedBadEndpoint = true;',
    '      console.warn("[orca-hook] failed to parse endpoint file:", err.message);',
    '    }',
    '    return null;',
    '  }',
    '}',
    '',
    'function resolveHookCoords() {',
    '  // Why: prefer the on-disk endpoint file over process.env because env was',
    '  // frozen when OpenCode was fork()ed — stale after an Orca restart. The',
    '  // file is rewritten on every Orca start(), so sourcing it per post lets',
    '  // a long-running OpenCode session reach the current server. Falls back',
    '  // to process.env when the file is absent (first-run / pre-endpoint-file / Orca',
    '  // never started writing the file).',
    '  const fileEnv = readEndpointFile() || {};',
    '  return {',
    '    port: fileEnv.ORCA_AGENT_HOOK_PORT || process.env.ORCA_AGENT_HOOK_PORT,',
    '    token: fileEnv.ORCA_AGENT_HOOK_TOKEN || process.env.ORCA_AGENT_HOOK_TOKEN,',
    '    env: fileEnv.ORCA_AGENT_HOOK_ENV || process.env.ORCA_AGENT_HOOK_ENV || "",',
    '    version: fileEnv.ORCA_AGENT_HOOK_VERSION || process.env.ORCA_AGENT_HOOK_VERSION || "",',
    '  };',
    '}',
    '',
    'function getStatusType(event) {',
    '  return event?.properties?.status?.type ?? event?.status?.type ?? null;',
    '}',
    '',
    '// Why: the ordinary OpenCode TUI can bootstrap worktree directories inside',
    '// one process. OpenCode creates a plugin factory per directory, but every',
    '// factory still reports one Orca pane, so status priority and ordering must',
    '// be coordinated at module scope instead of independently per factory.',
    'let nextFactoryID = 0;',
    'const activeFactoryIDs = new Set();',
    'let lastPublishedStatus = "idle";',
    'let lastPublishedSessionID = null;',
    'let lastPublishedOutcomeID = null;',
    'let aggregatePublishDirty = false;',
    'const busyRootSessionIds = new Set();',
    'const busyRootOwnerBySessionID = new Map();',
    'const pendingErrorByRootSessionID = new Map();',
    'const preflightErrorTimerByRootSessionID = new Map();',
    'const pendingPreflightRecoveryByRootSessionID = new Map();',
    'const terminalOutcomeByRootSessionID = new Map();',
    'let nextTerminalOutcomeID = 0;',
    'let lastDeliveredTerminalOutcomeID = 0;',
    'const rootSessionById = new Map();',
    'const pendingRequestByKey = new Map();',
    'const assistantPartStateBySession = new Map();',
    'const messagePartTextByKey = new Map();',
    'const messageRoleById = new Map();',
    'const inflightControllerOwner = new Map();',
    'let waitingRetryTimer = null;',
    'let waitingRetryAttempt = 0;',
    'let waitingRetryTargetKey = null;',
    'let lifecycleRetryTimer = null;',
    'let lifecycleRetryAttempt = 0;',
    'let lifecycleRetryTargetKey = null;',
    'let lifecycleRetryPreferredSessionID = null;',
    '',
    '// Why: OpenCode fire-and-forgets event promises, including events from',
    '// different directory factories. A module queue prevents an async lookup',
    '// or hook post in either factory from being overtaken by a later event.',
    'let eventQueue = Promise.resolve();',
    'function enqueueCoordinatorWork(work) {',
    '  const queued = eventQueue.then(work);',
    '  eventQueue = queued.catch(() => {});',
    '  return eventQueue;',
    '}',
    '',
    '// Why: accept an optional opaque context instead of destructuring. Some',
    '// OpenCode startup paths invoke file plugins with undefined context.',
    'export const OrcaOpenCodeStatusPlugin = async (_ctx) => {',
    'const client = _ctx?.client;',
    'const factoryID = ++nextFactoryID;',
    'activeFactoryIDs.add(factoryID);',
    '',
    '// Why: one OpenCode process can run multiple root sessions concurrently.',
    '// Orca has one pane for that process, so publish their aggregate state:',
    '// human input wins over busy, then terminal error/interruption, then idle.',
    'let disposed = false;',
    '',
    'function enqueuePluginWork(work) {',
    '  return enqueueCoordinatorWork(() => (disposed ? undefined : work()));',
    '}',
    '',
    '// Why: current OpenCode streams text as message.part.delta; older releases',
    '// and the final text-end event send full message.part.updated snapshots.',
    "// Forwarding either form at token cadence floods Orca's main/renderer loops.",
    '// Accumulate a bounded preview and trailing-edge coalesce it at human cadence.',
    'const MESSAGE_PART_THROTTLE_MS = 250;',
    'const MESSAGE_PART_MAX_CHARS = 4000;',
    'const MESSAGE_PART_RETRY_ATTEMPTS = 3;',
    'const WAITING_RETRY_MS = 500;',
    'const WAITING_RETRY_MAX_MS = 30000;',
    'const LIFECYCLE_RETRY_MS = 500;',
    'const LIFECYCLE_RETRY_MAX_MS = 30000;',
    '// Why: known failures before the first user message may emit no later',
    '// lifecycle event. Delay only source-proven terminal failures before surfacing them.',
    'const PREFLIGHT_ERROR_GRACE_MS = 5000;',
    'const SESSION_ERROR_MAX_CHARS = 1000;',
    '',
    'function capMessagePartText(text) {',
    '  return text.length > MESSAGE_PART_MAX_CHARS ? text.slice(0, MESSAGE_PART_MAX_CHARS) : text;',
    '}',
    '',
    '// Why: deltas carry only the appended fragment. Keep a bounded accumulator',
    '// per session+part so concurrent roots and consecutive text parts cannot mix.',
    'function messagePartTextKey(sessionID, partID) {',
    '  return sessionID && partID ? sessionID + ":" + partID : null;',
    '}',
    'function rememberMessagePartText(sessionID, partID, text) {',
    '  const key = messagePartTextKey(sessionID, partID);',
    '  const capped = capMessagePartText(text);',
    '  if (!key) return capped;',
    '  if (messagePartTextByKey.size >= 128 && !messagePartTextByKey.has(key)) {',
    '    const first = messagePartTextByKey.keys().next().value;',
    '    if (first !== undefined) messagePartTextByKey.delete(first);',
    '  }',
    '  messagePartTextByKey.set(key, { sessionID, text: capped });',
    '  return capped;',
    '}',
    'function appendMessagePartText(sessionID, partID, delta) {',
    '  const key = messagePartTextKey(sessionID, partID);',
    '  const current = key ? messagePartTextByKey.get(key)?.text || "" : "";',
    '  return rememberMessagePartText(sessionID, partID, current + delta);',
    '}',
    'function clearMessagePartTextForSession(sessionID) {',
    '  for (const [key, value] of messagePartTextByKey) {',
    '    if (value.sessionID === sessionID) messagePartTextByKey.delete(key);',
    '  }',
    '}',
    '',
    'function getAssistantPartState(sessionID) {',
    '  let state = assistantPartStateBySession.get(sessionID);',
    '  if (!state) {',
    '    if (assistantPartStateBySession.size >= 128) {',
    '      const first = assistantPartStateBySession.keys().next().value;',
    '      const evicted = assistantPartStateBySession.get(first);',
    '      if (evicted?.timer) clearTimeout(evicted.timer);',
    '      if (first !== undefined) assistantPartStateBySession.delete(first);',
    '    }',
    '    state = { ownerID: factoryID, pending: null, timer: null, lastAttemptAt: 0, retryAttempt: 0 };',
    '    assistantPartStateBySession.set(sessionID, state);',
    '  } else if (state.ownerID !== factoryID) {',
    '    // A moved session now belongs to this directory factory. Its old timer',
    '    // closes over the prior factory, so replace that ownership atomically.',
    '    if (state.timer) clearTimeout(state.timer);',
    '    state.ownerID = factoryID;',
    '    state.timer = null;',
    '  }',
    '  return state;',
    '}',
    '',
    'function scheduleAssistantPartFlush(sessionID, delay) {',
    '  const state = assistantPartStateBySession.get(sessionID);',
    '  if (!state || state.timer || !state.pending) return;',
    '  state.timer = setTimeout(() => {',
    '    state.timer = null;',
    '    void enqueueCoordinatorWork(() => flushPendingAssistantPart(sessionID));',
    '  }, delay);',
    '  if (state.timer.unref) state.timer.unref();',
    '}',
    '',
    'async function flushPendingAssistantPart(sessionID) {',
    '  const state = assistantPartStateBySession.get(sessionID);',
    '  if (!state) return;',
    '  if (state.timer) {',
    '    clearTimeout(state.timer);',
    '    state.timer = null;',
    '  }',
    '  const pending = state.pending;',
    '  if (!pending) return;',
    '  // Why: another root may keep streaming while one root needs attention.',
    '  // Suppress that lower-priority content ping so it cannot erase waiting.',
    '  if (pendingRequestByKey.size > 0) return;',
    '  const delivered = await post("MessagePart", {',
    '    role: pending.role,',
    '    text: capMessagePartText(pending.text),',
    '    messageID: pending.messageID,',
    '    sessionID: pending.sessionID,',
    '  }, state.ownerID);',
    '  // Why: failed loopback delivery must still consume the throttle slot.',
    '  // Otherwise every queued delta retries immediately and a 2s timeout can',
    '  // turn a brief Orca restart into minutes of serialized event backlog.',
    '  state.lastAttemptAt = Date.now();',
    '  if (!delivered) {',
    '    aggregatePublishDirty = true;',
    '    state.retryAttempt += 1;',
    '    if (state.retryAttempt <= MESSAGE_PART_RETRY_ATTEMPTS) {',
    '      scheduleAssistantPartFlush(',
    '        sessionID,',
    '        MESSAGE_PART_THROTTLE_MS * Math.pow(2, state.retryAttempt - 1)',
    '      );',
    '    }',
    '    return;',
    '  }',
    '  state.pending = null;',
    '  state.retryAttempt = 0;',
    '  lastPublishedStatus = "busy";',
    '  lastPublishedSessionID = pending.sessionID;',
    '  lastPublishedOutcomeID = null;',
    '  aggregatePublishDirty = false;',
    '}',
    '',
    'async function flushAllPendingAssistantParts() {',
    '  for (const sessionID of assistantPartStateBySession.keys()) {',
    '    await flushPendingAssistantPart(sessionID);',
    '  }',
    '}',
    '',
    'function clearAssistantPartState(sessionID) {',
    '  const state = assistantPartStateBySession.get(sessionID);',
    '  if (state?.timer) clearTimeout(state.timer);',
    '  assistantPartStateBySession.delete(sessionID);',
    '  clearMessagePartTextForSession(sessionID);',
    '}',
    'function retireAssistantPartsForIdleRoots() {',
    '  for (const sessionID of Array.from(assistantPartStateBySession.keys())) {',
    '    if (!busyRootSessionIds.has(sessionID)) clearAssistantPartState(sessionID);',
    '  }',
    '}',
    '',
    'async function queueAssistantPart(part) {',
    '  // Why: keep only the latest accumulated snapshot; intermediate previews',
    '  // carry no durable information once a newer delta/full part arrives.',
    '  const state = getAssistantPartState(part.sessionID);',
    '  if (state.pending?.text !== part.text) state.retryAttempt = 0;',
    '  state.pending = part;',
    '  const sinceLastAttempt = Date.now() - state.lastAttemptAt;',
    '  if (sinceLastAttempt >= MESSAGE_PART_THROTTLE_MS && !state.timer) {',
    '    await flushPendingAssistantPart(part.sessionID);',
    '    return;',
    '  }',
    '  scheduleAssistantPartFlush(',
    '    part.sessionID,',
    '    Math.max(0, MESSAGE_PART_THROTTLE_MS - sinceLastAttempt)',
    '  );',
    '}',
    '',
    'async function publishMessageText(part) {',
    '  if (pendingRequestByKey.size > 0) {',
    '    // A preview must never transiently replace human attention. Retain the',
    '    // latest snapshot and flush it when all real blockers are gone.',
    '    getAssistantPartState(part.sessionID).pending = part;',
    '    return;',
    '  }',
    '  if (part.role === "user") {',
    '    const delivered = await post("MessagePart", {',
    '      role: part.role,',
    '      text: capMessagePartText(part.text),',
    '      messageID: part.messageID,',
    '      sessionID: part.sessionID,',
    '    });',
    '    if (delivered) {',
    '      lastPublishedStatus = "busy";',
    '      lastPublishedSessionID = part.sessionID;',
    '      lastPublishedOutcomeID = null;',
    '      aggregatePublishDirty = false;',
    '    } else {',
    '      aggregatePublishDirty = true;',
    '    }',
    '    return;',
    '  }',
    '  await queueAssistantPart(part);',
    '}',
    '',
    '// Why: message.part.updated fires for every Part (text, tool, reasoning)',
    '// but does not include the message role — that lives on the parent',
    '// message.updated event. Cache the role per session+message so concurrent',
    '// roots cannot overwrite one another even if an integration reuses ids.',
    '// This lets us tag a TextPart as user vs assistant when POSTing. Capped',
    '// at 128 entries',
    '// so long-running sessions do not grow this map unboundedly.',
    'function messageRoleKey(sessionID, messageID) {',
    '  return sessionID && messageID ? sessionID + ":" + messageID : null;',
    '}',
    'function rememberMessageRole(sessionID, messageID, role) {',
    '  const key = messageRoleKey(sessionID, messageID);',
    '  if (!key || !role) return;',
    '  if (messageRoleById.size >= 128 && !messageRoleById.has(key)) {',
    '    const first = messageRoleById.keys().next().value;',
    '    if (first !== undefined) messageRoleById.delete(first);',
    '  }',
    '  messageRoleById.set(key, role);',
    '}',
    '',
    '// Why: child completion/message events must not overwrite the root pane, but',
    '// OpenCode itself rolls descendant permission/questions into the root UI.',
    '// Resolve and cache the full ancestry so attention can be attributed to the',
    '// root while every other child event stays filtered.',
    'function rememberRootSession(sessionID, rootSessionID) {',
    '  if (rootSessionById.size >= 128 && !rootSessionById.has(sessionID)) {',
    '    const first = rootSessionById.keys().next().value;',
    '    if (first !== undefined) rootSessionById.delete(first);',
    '  }',
    '  rootSessionById.set(sessionID, rootSessionID);',
    '}',
    '',
    'async function getSessionByID(client, sessionID) {',
    '  const shapes = [{ path: { id: sessionID } }, { sessionID }];',
    '  for (const input of shapes) {',
    '    try {',
    '      const response = await client.session.get(input);',
    '      if (response?.data?.id) return response.data;',
    '    } catch {',
    '      // Try the other SDK generation before falling back to session.list.',
    '    }',
    '  }',
    '  return null;',
    '}',
    '',
    'async function resolveRootSessionID(client, sessionID) {',
    '  if (!sessionID) return null;',
    '  if (rootSessionById.has(sessionID)) return rootSessionById.get(sessionID);',
    '  if (!client?.session) return null;',
    '  // Prefer point lookups: session.list is paginated in current OpenCode,',
    "  // so a child's older root may not appear in the default first page.",
    '  if (client.session.get) {',
    '    try {',
    '      const ancestry = [];',
    '      const seen = new Set();',
    '      let currentID = sessionID;',
    '      while (currentID && seen.size < 128) {',
    '        if (seen.has(currentID)) throw new Error("cyclic session lineage");',
    '        seen.add(currentID);',
    '        ancestry.push(currentID);',
    '        if (rootSessionById.has(currentID)) {',
    '          const cachedRoot = rootSessionById.get(currentID);',
    '          for (const id of ancestry) rememberRootSession(id, cachedRoot);',
    '          return cachedRoot;',
    '        }',
    '        const session = await getSessionByID(client, currentID);',
    '        if (!session?.id) throw new Error("session lookup failed");',
    '        if (!session.parentID) {',
    '          for (const id of ancestry) rememberRootSession(id, session.id);',
    '          return session.id;',
    '        }',
    '        currentID = session.parentID;',
    '      }',
    '    } catch {',
    '      // Older SDKs and transient lookup failures fall back to list below.',
    '    }',
    '  }',
    '  if (!client.session.list) return null;',
    '  try {',
    '    const response = await client.session.list();',
    '    const list = Array.isArray(response?.data) ? response.data : [];',
    '    const sessionById = new Map(list.filter((entry) => entry?.id).map((entry) => [entry.id, entry]));',
    '    let session = sessionById.get(sessionID);',
    '    if (!session) return null;',
    '    const ancestry = [];',
    '    const seen = new Set();',
    '    while (session) {',
    '      if (seen.has(session.id)) return null;',
    '      seen.add(session.id);',
    '      ancestry.push(session.id);',
    '      if (!session.parentID) break;',
    '      session = sessionById.get(session.parentID);',
    '      if (!session) return null;',
    '    }',
    '    const rootSessionID = session.id;',
    '    for (const id of ancestry) rememberRootSession(id, rootSessionID);',
    '    return rootSessionID;',
    '  } catch {',
    '    return null;',
    '  }',
    '}',
    '',
    'function capSessionErrorText(value) {',
    '  if (typeof value !== "string") return null;',
    '  const trimmed = value.trim();',
    '  if (!trimmed) return null;',
    '  return trimmed.length > SESSION_ERROR_MAX_CHARS',
    '    ? trimmed.slice(0, SESSION_ERROR_MAX_CHARS)',
    '    : trimmed;',
    '}',
    'function normalizeSessionError(error) {',
    '  const record = error && typeof error === "object" ? error : {};',
    '  const data = record.data && typeof record.data === "object" ? record.data : {};',
    '  const name = capSessionErrorText(record.name) || "UnknownError";',
    '  const message =',
    '    capSessionErrorText(data.message) ||',
    '    capSessionErrorText(record.message) ||',
    '    (name === "MessageAbortedError" ? "Aborted" : "OpenCode session failed");',
    '  return { name, data: { message } };',
    '}',
    'function classifyTerminalPreflightFailure(error) {',
    '  const message = error?.data?.message;',
    '  if (error?.name !== "UnknownError" || typeof message !== "string") return null;',
    '  if (/^(?:Agent|Command|Model) not found(?::|$)/.test(message)) return "direct";',
    '  // prompt_async serializes terminal Cause.pretty stacks, while recoverable',
    '  // attachment/directory events publish only the underlying Error.message.',
    '  if (/^[^\\r\\n]+:[^\\r\\n]*\\r?\\n\\s+at(?:\\s|$)/.test(message)) return "serialized";',
    '  return null;',
    '}',
    'function rememberPendingRootError(rootSessionID, error) {',
    '  if (',
    '    pendingErrorByRootSessionID.size >= 128 &&',
    '    !pendingErrorByRootSessionID.has(rootSessionID)',
    '  ) {',
    '    const first = pendingErrorByRootSessionID.keys().next().value;',
    '    if (first !== undefined) takePendingRootError(first);',
    '  }',
    '  const normalizedError = normalizeSessionError(error);',
    '  const preflightFailureKind = classifyTerminalPreflightFailure(normalizedError);',
    '  const current = pendingErrorByRootSessionID.get(rootSessionID);',
    '  if (',
    '    current?.preflightFailureKind &&',
    '    (!preflightFailureKind || current.preflightFailureKind === "direct")',
    '  ) return current;',
    '  const pendingError = {',
    '    ownerID: factoryID,',
    '    error: normalizedError,',
    '    preflightFailureKind,',
    '  };',
    '  pendingErrorByRootSessionID.set(rootSessionID, pendingError);',
    '  return pendingError;',
    '}',
    'function clearPreflightErrorTimer(rootSessionID) {',
    '  const timer = preflightErrorTimerByRootSessionID.get(rootSessionID);',
    '  if (timer) clearTimeout(timer);',
    '  preflightErrorTimerByRootSessionID.delete(rootSessionID);',
    '}',
    'function takePendingRootError(rootSessionID) {',
    '  clearPreflightErrorTimer(rootSessionID);',
    '  const pendingError = pendingErrorByRootSessionID.get(rootSessionID);',
    '  pendingErrorByRootSessionID.delete(rootSessionID);',
    '  return pendingError;',
    '}',
    'function schedulePreflightErrorPromotion(rootSessionID) {',
    '  clearPreflightErrorTimer(rootSessionID);',
    '  const timer = setTimeout(() => {',
    '    preflightErrorTimerByRootSessionID.delete(rootSessionID);',
    '    void enqueueCoordinatorWork(async () => {',
    '      if (disposed || busyRootSessionIds.has(rootSessionID)) return;',
    '      const pendingError = takePendingRootError(rootSessionID);',
    '      if (!pendingError || !activeFactoryIDs.has(pendingError.ownerID)) return;',
    '      // Elapsed time alone cannot prove failure: OpenCode can continue',
    '      // preflight through arbitrarily slow user plugins after this timer.',
    '      recordTerminalOutcome(rootSessionID, pendingError, true);',
    '      await publishAggregateStatus(rootSessionID);',
    '    });',
    '  }, PREFLIGHT_ERROR_GRACE_MS);',
    '  preflightErrorTimerByRootSessionID.set(rootSessionID, timer);',
    '  if (timer.unref) timer.unref();',
    '}',
    'function recordTerminalOutcome(rootSessionID, pendingError, preflight = false) {',
    '  if (',
    '    terminalOutcomeByRootSessionID.size >= 128 &&',
    '    !terminalOutcomeByRootSessionID.has(rootSessionID)',
    '  ) {',
    '    const first = terminalOutcomeByRootSessionID.keys().next().value;',
    '    if (first !== undefined) terminalOutcomeByRootSessionID.delete(first);',
    '  }',
    '  terminalOutcomeByRootSessionID.delete(rootSessionID);',
    '  terminalOutcomeByRootSessionID.set(rootSessionID, {',
    '    id: ++nextTerminalOutcomeID,',
    '    ownerID: pendingError.ownerID,',
    '    sessionID: rootSessionID,',
    '    type: pendingError.error.name === "MessageAbortedError" ? "aborted" : "error",',
    '    error: pendingError.error,',
    '    preflight,',
    '  });',
    '}',
    'function clearPendingPreflightRecovery(rootSessionID, messageID = null) {',
    '  const recovery = pendingPreflightRecoveryByRootSessionID.get(rootSessionID);',
    '  if (!recovery || (messageID && recovery.messageID !== messageID)) return false;',
    '  clearTimeout(recovery.timer);',
    '  pendingPreflightRecoveryByRootSessionID.delete(rootSessionID);',
    '  return true;',
    '}',
    'function schedulePreflightRecoverySettlement(rootSessionID, messageID) {',
    '  clearPendingPreflightRecovery(rootSessionID);',
    '  const recovery = { ownerID: factoryID, messageID, timer: null };',
    '  recovery.timer = setTimeout(() => {',
    '    if (pendingPreflightRecoveryByRootSessionID.get(rootSessionID) !== recovery) return;',
    '    pendingPreflightRecoveryByRootSessionID.delete(rootSessionID);',
    '    void enqueueCoordinatorWork(async () => {',
    '      if (!activeFactoryIDs.has(recovery.ownerID)) return;',
    '      await publishAggregateStatus(rootSessionID);',
    '    });',
    '  }, 0);',
    '  pendingPreflightRecoveryByRootSessionID.set(rootSessionID, recovery);',
    '  if (recovery.timer.unref) recovery.timer.unref();',
    '}',
    'function recoverRootPreflightError(rootSessionID, messageID) {',
    '  clearPendingPreflightRecovery(rootSessionID);',
    '  takePendingRootError(rootSessionID);',
    '  const outcome = terminalOutcomeByRootSessionID.get(rootSessionID);',
    '  if (!outcome?.preflight) return;',
    '  // A late root user message is stronger evidence than a preflight timeout.',
    '  // Defer clearing the UI until its part proves working vs synthetic noReply.',
    '  terminalOutcomeByRootSessionID.delete(rootSessionID);',
    '  if (lastDeliveredTerminalOutcomeID === outcome.id) {',
    '    // This provisional result must not retire an older, undelivered root.',
    '    lastDeliveredTerminalOutcomeID = 0;',
    '  }',
    '  const recoveredTargetKey = outcome.type + ":" + rootSessionID + ":" + outcome.id;',
    '  if (lifecycleRetryTargetKey === recoveredTargetKey) clearLifecycleRetry();',
    '  schedulePreflightRecoverySettlement(rootSessionID, messageID);',
    '}',
    'function latestTerminalOutcome() {',
    '  let latestError = null;',
    '  let latestAborted = null;',
    '  for (const outcome of terminalOutcomeByRootSessionID.values()) {',
    '    if (outcome.type === "error") latestError = outcome;',
    '    else latestAborted = outcome;',
    '  }',
    '  return latestError || latestAborted;',
    '}',
    'function retireDeliveredTerminalOutcomes() {',
    '  if (lastDeliveredTerminalOutcomeID === 0) return;',
    '  for (const [sessionID, outcome] of terminalOutcomeByRootSessionID) {',
    '    if (outcome.id <= lastDeliveredTerminalOutcomeID) {',
    '      terminalOutcomeByRootSessionID.delete(sessionID);',
    '    }',
    '  }',
    '  lastDeliveredTerminalOutcomeID = 0;',
    '}',
    '',
    'async function post(hookEventName, extraProperties, preferredOwnerID = factoryID) {',
    '  // Why: resolve coords per post — the endpoint file may have been',
    '  // rewritten by a newer Orca since the last call. Pane/tab/worktree IDs',
    '  // stay on process.env because they are per-PTY (stable for the life of',
    '  // the OpenCode process), not per-Orca-instance.',
    '  const coords = resolveHookCoords();',
    '  const paneKey = process.env.ORCA_PANE_KEY;',
    '  const postOwnerID = activeFactoryIDs.has(preferredOwnerID)',
    '    ? preferredOwnerID',
    '    : activeFactoryIDs.values().next().value;',
    '  if (!coords.port || !coords.token || !paneKey || postOwnerID === undefined) return false;',
    `  const url = \`http://127.0.0.1:\${coords.port}${hookPathname}\`;`,
    '  const body = JSON.stringify({',
    '    paneKey,',
    '    launchToken: process.env.ORCA_AGENT_LAUNCH_TOKEN || "",',
    '    tabId: process.env.ORCA_TAB_ID || "",',
    '    worktreeId: process.env.ORCA_WORKTREE_ID || "",',
    '    env: coords.env,',
    '    version: coords.version,',
    '    payload: { hook_event_name: hookEventName, ...(extraProperties || {}) },',
    '  });',
    '  const controller = new AbortController();',
    '  inflightControllerOwner.set(controller, postOwnerID);',
    '  const timeout = setTimeout(() => controller.abort(), 2000);',
    '  if (timeout.unref) timeout.unref();',
    '  try {',
    '    const response = await fetch(url, {',
    '      method: "POST",',
    '      headers: {',
    '        "Content-Type": "application/json",',
    '        "X-Orca-Agent-Hook-Token": coords.token,',
    '      },',
    '      body,',
    '      signal: controller.signal,',
    '    });',
    '    return response.ok;',
    '  } catch {',
    '    // Why: OpenCode session events must never fail the agent run just',
    '    // because Orca is unavailable or the local loopback request failed.',
    '    return false;',
    '  } finally {',
    '    clearTimeout(timeout);',
    '    inflightControllerOwner.delete(controller);',
    '  }',
    '}',
    '',
    'function requestKey(kind, requestID) {',
    '  return typeof requestID === "string" && requestID ? kind + ":" + requestID : null;',
    '}',
    'function questionToolReference(properties) {',
    '  const tool = properties?.tool;',
    '  if (!tool || typeof tool !== "object") return null;',
    '  const messageID = tool.messageID;',
    '  const callID = tool.callID;',
    '  if (typeof messageID !== "string" || !messageID) return null;',
    '  if (typeof callID !== "string" || !callID) return null;',
    '  return { messageID, callID };',
    '}',
    '',
    'function latestBusyRootSessionID(preferredSessionID) {',
    '  if (preferredSessionID && busyRootSessionIds.has(preferredSessionID)) {',
    '    return preferredSessionID;',
    '  }',
    '  let latest = null;',
    '  for (const sessionID of busyRootSessionIds) latest = sessionID;',
    '  return latest;',
    '}',
    '',
    'function clearLifecycleRetry() {',
    '  if (lifecycleRetryTimer) clearTimeout(lifecycleRetryTimer);',
    '  lifecycleRetryTimer = null;',
    '  lifecycleRetryAttempt = 0;',
    '  lifecycleRetryTargetKey = null;',
    '  lifecycleRetryPreferredSessionID = null;',
    '}',
    'function setLifecycleRetryTarget(targetKey, preferredSessionID) {',
    '  if (lifecycleRetryTargetKey === targetKey) {',
    '    lifecycleRetryPreferredSessionID = preferredSessionID;',
    '    return false;',
    '  }',
    '  clearLifecycleRetry();',
    '  lifecycleRetryTargetKey = targetKey;',
    '  lifecycleRetryPreferredSessionID = preferredSessionID;',
    '  return true;',
    '}',
    'function scheduleLifecycleRetry() {',
    '  if (',
    '    lifecycleRetryTimer ||',
    '    lifecycleRetryTargetKey === null ||',
    '    activeFactoryIDs.size === 0',
    '  ) return;',
    '  const targetKey = lifecycleRetryTargetKey;',
    '  const preferredSessionID = lifecycleRetryPreferredSessionID;',
    '  // Why: a surviving agent may outlast an Orca restart. Ramp quickly, then',
    '  // keep one low-frequency unrefd probe alive until this state is superseded.',
    '  const delay = Math.min(',
    '    LIFECYCLE_RETRY_MS * Math.pow(2, Math.min(lifecycleRetryAttempt, 30)),',
    '    LIFECYCLE_RETRY_MAX_MS',
    '  );',
    '  lifecycleRetryAttempt = Math.min(lifecycleRetryAttempt + 1, 31);',
    '  lifecycleRetryTimer = setTimeout(() => {',
    '    lifecycleRetryTimer = null;',
    '    void enqueueCoordinatorWork(async () => {',
    '      // A newer busy/waiting/error target invalidates this queued retry.',
    '      if (lifecycleRetryTargetKey !== targetKey || activeFactoryIDs.size === 0) return;',
    '      await publishAggregateStatus(preferredSessionID, targetKey);',
    '    });',
    '  }, delay);',
    '  if (lifecycleRetryTimer.unref) lifecycleRetryTimer.unref();',
    '}',
    '',
    'async function publishAggregateStatus(preferredSessionID, scheduledTargetKey = null) {',
    '  if (pendingRequestByKey.size > 0) {',
    '    clearLifecycleRetry();',
    '    if (lastPublishedStatus !== "waiting" || aggregatePublishDirty) {',
    '      await publishCurrentWaiting();',
    '    }',
    '    return;',
    '  }',
    '  const terminalOutcome = busyRootSessionIds.size === 0 ? latestTerminalOutcome() : null;',
    '  const next = busyRootSessionIds.size > 0 ? "busy" : terminalOutcome?.type || "idle";',
    '  const sessionID =',
    '    next === "busy"',
    '      ? latestBusyRootSessionID(preferredSessionID)',
    '      : terminalOutcome?.sessionID || preferredSessionID;',
    '  // Once a root is canonical idle, its one-shot final preview may be tried',
    '  // before the lifecycle post but must never retry after that authority.',
    '  retireAssistantPartsForIdleRoots();',
    '  const targetKey =',
    '    next + ":" + (sessionID || "") + ":" + (terminalOutcome?.id || "");',
    '  const targetChanged = setLifecycleRetryTarget(targetKey, sessionID);',
    '  // Why: session.status idle and deprecated session.idle are emitted as a',
    '  // pair, but a different busy root must refresh resumable session metadata.',
    '  if (',
    '    !aggregatePublishDirty &&',
    '    lastPublishedStatus === next &&',
    '    (next === "idle" || lastPublishedSessionID === sessionID) &&',
    '    (!terminalOutcome || lastPublishedOutcomeID === terminalOutcome.id)',
    '  ) {',
    '    clearLifecycleRetry();',
    '    return;',
    '  }',
    '  // Canonical+deprecated duplicates share one retry target and bounded cadence.',
    '  if (',
    '    !targetChanged &&',
    '    scheduledTargetKey !== targetKey &&',
    '    lifecycleRetryTimer',
    '  ) return;',
    '  const hookEventName =',
    '    next === "busy"',
    '      ? "SessionBusy"',
    '      : next === "error"',
    '        ? "SessionError"',
    '        : next === "aborted"',
    '          ? "SessionAborted"',
    '          : "SessionIdle";',
    '  const properties = terminalOutcome',
    '    ? { sessionID, error: terminalOutcome.error }',
    '    : sessionID',
    '      ? { sessionID }',
    '      : {};',
    '  const delivered = await post(',
    '    hookEventName,',
    '    properties,',
    '    busyRootOwnerBySessionID.get(sessionID) ?? terminalOutcome?.ownerID ?? factoryID',
    '  );',
    '  if (!delivered) {',
    '    aggregatePublishDirty = true;',
    '    scheduleLifecycleRetry();',
    '    return;',
    '  }',
    '  clearLifecycleRetry();',
    '  lastPublishedStatus = next;',
    '  lastPublishedSessionID = sessionID;',
    '  lastPublishedOutcomeID = terminalOutcome?.id || null;',
    '  if (terminalOutcome) lastDeliveredTerminalOutcomeID = terminalOutcome.id;',
    '  aggregatePublishDirty = false;',
    '}',
    '',
    'function scheduleWaitingRetry() {',
    '  if (',
    '    waitingRetryTimer ||',
    '    waitingRetryTargetKey === null ||',
    '    pendingRequestByKey.size === 0 ||',
    '    activeFactoryIDs.size === 0',
    '  ) return;',
    '  const targetKey = waitingRetryTargetKey;',
    '  // Why: blockers can outlive an Orca restart. After the quick ramp, keep',
    '  // a capped unrefd probe so the new endpoint eventually receives attention.',
    '  const delay = Math.min(',
    '    WAITING_RETRY_MS * Math.pow(2, Math.min(waitingRetryAttempt, 30)),',
    '    WAITING_RETRY_MAX_MS',
    '  );',
    '  waitingRetryAttempt = Math.min(waitingRetryAttempt + 1, 31);',
    '  waitingRetryTimer = setTimeout(() => {',
    '    waitingRetryTimer = null;',
    '    void enqueueCoordinatorWork(async () => {',
    '      if (',
    '        waitingRetryTargetKey !== targetKey ||',
    '        pendingRequestByKey.size === 0 ||',
    '        activeFactoryIDs.size === 0',
    '      ) return;',
    '      await publishCurrentWaiting();',
    '    });',
    '  }, delay);',
    '  if (waitingRetryTimer.unref) waitingRetryTimer.unref();',
    '}',
    '',
    'function clearWaitingRetry() {',
    '  if (waitingRetryTimer) clearTimeout(waitingRetryTimer);',
    '  waitingRetryTimer = null;',
    '  waitingRetryAttempt = 0;',
    '  waitingRetryTargetKey = null;',
    '}',
    'function setWaitingRetryTarget(targetKey) {',
    '  if (waitingRetryTargetKey === targetKey) return;',
    '  clearWaitingRetry();',
    '  waitingRetryTargetKey = targetKey;',
    '}',
    '',
    'function clearWaitingRetryIfSettled() {',
    '  if (pendingRequestByKey.size > 0) return;',
    '  clearWaitingRetry();',
    '}',
    '',
    'function currentWaitingRequest() {',
    '  let firstQuestion = null;',
    '  for (const request of pendingRequestByKey.values()) {',
    '    // Why: OpenCode keeps its permission prompt visible ahead of every',
    '    // queued question. Match that priority so Orca describes the blocker',
    '    // the user can actually resolve in OpenCode.',
    '    if (request.kind === "permission") return request;',
    '    if (!firstQuestion) firstQuestion = request;',
    '  }',
    '  return firstQuestion;',
    '}',
    '',
    'async function publishCurrentWaiting() {',
    '  clearLifecycleRetry();',
    '  const request = currentWaitingRequest();',
    '  if (!request) return true;',
    '  setWaitingRetryTarget(request.key);',
    '  const delivered = await post(request.hookEventName, request.properties, request.ownerID);',
    '  if (delivered) {',
    '    clearWaitingRetry();',
    '    lastPublishedStatus = "waiting";',
    '    lastPublishedSessionID = request.rootSessionID;',
    '    lastPublishedOutcomeID = null;',
    '    aggregatePublishDirty = false;',
    '  } else {',
    '    aggregatePublishDirty = true;',
    '    scheduleWaitingRetry();',
    '  }',
    '  return delivered;',
    '}',
    '',
    'async function publishWaiting(hookEventName, properties, rootSessionID, kind) {',
    '  clearLifecycleRetry();',
    '  // Flush every root before the first blocker becomes authoritative so no',
    '  // already-scheduled MessagePart can arrive later and erase attention.',
    '  if (pendingRequestByKey.size === 0) await flushAllPendingAssistantParts();',
    '  const key = requestKey(kind, properties?.id);',
    '  const sourceSessionID = properties?.sessionID;',
    '  const normalizedProperties = { ...(properties || {}), sessionID: rootSessionID };',
    '  if (key) {',
    '    pendingRequestByKey.set(key, {',
    '      key,',
    '      ownerID: factoryID,',
    '      hookEventName,',
    '      properties: normalizedProperties,',
    '      rootSessionID,',
    '      sourceSessionID,',
    '      kind,',
    '      questionTool: kind === "question" ? questionToolReference(properties) : null,',
    '    });',
    '  }',
    '  const delivered = key',
    '    ? await publishCurrentWaiting()',
    '    : await post(hookEventName, normalizedProperties);',
    '  if (key) return;',
    '  if (delivered) {',
    '    clearWaitingRetry();',
    '    lastPublishedStatus = "waiting";',
    '    lastPublishedSessionID = rootSessionID;',
    '    lastPublishedOutcomeID = null;',
    '    aggregatePublishDirty = false;',
    '  } else {',
    '    aggregatePublishDirty = true;',
    '    scheduleWaitingRetry();',
    '  }',
    '}',
    '',
    'async function publishAfterWaitingResolution(resolved) {',
    '  clearWaitingRetryIfSettled();',
    '  if (pendingRequestByKey.size > 0) {',
    '    // The resolved card may have been the one Orca showed. Re-post a real',
    '    // remaining blocker so the pane never displays stale question details.',
    '    await publishCurrentWaiting();',
    '    return;',
    '  }',
    '  if (busyRootSessionIds.size > 0) {',
    '    await flushAllPendingAssistantParts();',
    '    // End on the active root so resume metadata cannot point at an idle',
    '    // session whose retained preview was just flushed.',
    '    await publishAggregateStatus(resolved.rootSessionID);',
    '    return;',
    '  }',
    '  // If the root finished while blocked, the final preview must precede done.',
    '  await flushAllPendingAssistantParts();',
    '  await publishAggregateStatus(resolved.rootSessionID);',
    '}',
    '',
    'async function resolveWaiting(properties, kind) {',
    '  const key = requestKey(kind, properties?.requestID);',
    '  if (!key) return;',
    '  const resolved = pendingRequestByKey.get(key);',
    '  if (!resolved) return;',
    '  pendingRequestByKey.delete(key);',
    '  await publishAfterWaitingResolution(resolved);',
    '}',
    '',
    'async function resolveCompletedQuestionTool(part, sourceSessionID) {',
    '  if (!part || part.type !== "tool" || part.tool !== "question") return false;',
    '  if (part.state?.status !== "completed" && part.state?.status !== "error") return false;',
    '  if (typeof sourceSessionID !== "string" || !sourceSessionID) return false;',
    '  if (part.sessionID !== undefined && part.sessionID !== sourceSessionID) return false;',
    '  if (typeof part.messageID !== "string" || !part.messageID) return false;',
    '  if (typeof part.callID !== "string" || !part.callID) return false;',
    '  let resolved = null;',
    '  for (const [key, request] of pendingRequestByKey) {',
    '    const tool = request.questionTool;',
    '    if (request.sourceSessionID !== sourceSessionID || !tool) continue;',
    '    if (tool.messageID !== part.messageID || tool.callID !== part.callID) continue;',
    '    pendingRequestByKey.delete(key);',
    '    resolved ||= request;',
    '  }',
    '  if (!resolved) return false;',
    '  // Why: OpenCode can finish a question tool without question.replied.',
    '  await publishAfterWaitingResolution(resolved);',
    '  return true;',
    '}',
    '',
    'async function clearWaitingForIdleSession(sessionID, rootSessionID, clearRootDescendants) {',
    '  let removed = false;',
    '  for (const [key, request] of pendingRequestByKey) {',
    '    const belongsToIdleSession = request.sourceSessionID === sessionID;',
    '    const belongsToAbortedRoot =',
    '      clearRootDescendants && rootSessionID && request.rootSessionID === rootSessionID;',
    '    if (!belongsToIdleSession && !belongsToAbortedRoot) continue;',
    '    pendingRequestByKey.delete(key);',
    '    removed = true;',
    '  }',
    '  clearWaitingRetryIfSettled();',
    '  // OpenCode aborts asks by deleting them without a replied/rejected event.',
    '  // If another blocker remains, re-post it instead of showing stale details.',
    '  if (removed && pendingRequestByKey.size > 0) await publishCurrentWaiting();',
    '  return removed;',
    '}',
    '',
    '  async function handleEvent(event) {',
    '    if (!event?.type) return;',
    '    const properties = event.properties || {};',
    '    const sessionID = properties.sessionID ?? properties.part?.sessionID;',
    '    const statusType = event.type === "session.status" ? getStatusType(event) : null;',
    '',
    '    if (event.type === "message.updated") {',
    '      const info = properties.info;',
    '      rememberMessageRole(sessionID, info?.id, info?.role);',
    '    }',
    '',
    '    if (event.type === "permission.replied") {',
    '      await resolveWaiting(properties, "permission");',
    '      return;',
    '    }',
    '    if (event.type === "question.replied" || event.type === "question.rejected") {',
    '      await resolveWaiting(properties, "question");',
    '      return;',
    '    }',
    '    if (',
    '      event.type === "message.part.updated" &&',
    '      await resolveCompletedQuestionTool(properties.part, sessionID)',
    '    ) return;',
    '    const rootSessionID = await resolveRootSessionID(client, sessionID);',
    '    if (',
    '      event.type === "message.updated" &&',
    '      rootSessionID === sessionID &&',
    '      properties.info?.role === "user"',
    '    ) {',
    '      // Why: OpenCode can emit recoverable prompt-file errors before it',
    '      // finishes the root user message. That message proves preflight continued.',
    '      recoverRootPreflightError(rootSessionID, properties.info?.id);',
    '    }',
    '    if (event.type === "session.error") {',
    '      // Auto-compaction emits an error and keeps running, while fatal and',
    '      // aborted turns emit the same event immediately before canonical idle.',
    '      // Buffer in-turn and recoverable preflight errors until event authority',
    '      // resolves them. Only failures known to lack a later status get a',
    '      // grace timer; root user/busy evidence can still retire that outcome.',
    '      if (rootSessionID && rootSessionID === sessionID) {',
    '        const pendingError = rememberPendingRootError(rootSessionID, properties.error);',
    '        if (',
    '          !busyRootSessionIds.has(rootSessionID) &&',
    '          pendingError.preflightFailureKind',
    '        ) {',
    '          schedulePreflightErrorPromotion(rootSessionID);',
    '        } else {',
    '          clearPreflightErrorTimer(rootSessionID);',
    '        }',
    '      }',
    '      return;',
    '    }',
    '    if (event.type === "permission.asked" || event.type === "question.asked") {',
    '      // Human input rolls up from descendants. On lookup failure, surface the',
    '      // request under its own session id; missing a real blocker is worse than',
    '      // temporarily lacking its parent attribution.',
    '      const attentionRootSessionID = rootSessionID || sessionID;',
    '      if (!attentionRootSessionID) return;',
    '      await publishWaiting(',
    '        event.type === "permission.asked" ? "PermissionRequest" : "AskUserQuestion",',
    '        properties,',
    '        attentionRootSessionID,',
    '        event.type === "permission.asked" ? "permission" : "question"',
    '      );',
    '      return;',
    '    }',
    '',
    '    const isIdleEvent = event.type === "session.idle" || statusType === "idle";',
    '    if (isIdleEvent) {',
    '      const pendingRootError = rootSessionID',
    '        ? pendingErrorByRootSessionID.get(rootSessionID)',
    '        : null;',
    '      // Root abort can silently dispose every descendant ask. Normal root',
    '      // idle must leave background-child blockers live until that child idles.',
    '      const clearsAbortedRootDescendants =',
    '        rootSessionID === sessionID && pendingRootError?.error.name === "MessageAbortedError";',
    '      const clearedWaiting = await clearWaitingForIdleSession(',
    '        sessionID,',
    '        rootSessionID,',
    '        clearsAbortedRootDescendants',
    '      );',
    '      if (!rootSessionID && !clearedWaiting) return;',
    '      if (rootSessionID && rootSessionID !== sessionID) {',
    '        if (clearedWaiting) {',
    '          // OpenCode silently aborts child asks on idle. Release the root',
    '          // preview retained behind that attention just like a real reply.',
    '          if (pendingRequestByKey.size === 0) await flushAllPendingAssistantParts();',
    '          await publishAggregateStatus(rootSessionID);',
    '        }',
    '        return;',
    '      }',
    '      const idleRootSessionID = rootSessionID || sessionID;',
    '      clearPendingPreflightRecovery(idleRootSessionID);',
    '      const pendingError = takePendingRootError(idleRootSessionID);',
    '      const ownsBusyRoot = busyRootOwnerBySessionID.get(idleRootSessionID) === factoryID;',
    '      await flushPendingAssistantPart(sessionID);',
    "      // Another root's blocker suppresses but retains this final preview.",
    '      if (pendingRequestByKey.size === 0) clearAssistantPartState(sessionID);',
    '      if (ownsBusyRoot) {',
    '        busyRootSessionIds.delete(idleRootSessionID);',
    '        busyRootOwnerBySessionID.delete(idleRootSessionID);',
    '      }',
    '      if (pendingError) {',
    '        recordTerminalOutcome(idleRootSessionID, pendingError);',
    '      } else if (ownsBusyRoot) {',
    '        terminalOutcomeByRootSessionID.delete(idleRootSessionID);',
    '      }',
    '      await publishAggregateStatus(idleRootSessionID);',
    '      return;',
    '    }',
    '',
    '    // Only a proven root may drive pane lifecycle or previews. Child activity',
    "    // belongs inside OpenCode's task UI and must not spin/finish the root tab.",
    '    if (!rootSessionID || rootSessionID !== sessionID) return;',
    '    if (event.type === "message.updated") return;',
    '',
    '    if (event.type === "message.part.updated") {',
    '      // Why: a TextPart carries the actual user prompt or assistant reply',
    '      // text. Skip non-text parts (tool, reasoning, file, …) so we only',
    '      // forward what the dashboard renders. Role came from the earlier',
    '      // message.updated event; if we never saw one (e.g. plugin loaded',
    '      // mid-turn) the role is unknown, and mislabeling the part — a user',
    '      // prompt displayed as the assistant reply, or vice versa — is worse',
    '      // than silently dropping a single in-flight text chunk. The next',
    '      // message.updated event will re-seed the role cache, so subsequent',
    '      // parts in the same session flow normally.',
    '      const part = properties.part;',
    '      if (!part || part.type !== "text") return;',
    '      const role = messageRoleById.get(messageRoleKey(sessionID, part.messageID));',
    '      if (!role) return;',
    '      // Move/warp reminders are synthetic noReply user parts. They update',
    '      // history but must not make an otherwise idle pane look like it is working.',
    '      if (role === "user" && part.synthetic === true) return;',
    '      if (role === "user") clearPendingPreflightRecovery(rootSessionID, part.messageID);',
    '      const text = rememberMessagePartText(',
    '        sessionID,',
    '        part.id || part.messageID,',
    '        typeof part.text === "string" ? part.text : ""',
    '      );',
    '      if (!text) return;',
    '      await publishMessageText({ role, text, messageID: part.messageID, sessionID });',
    '      return;',
    '    }',
    '',
    '    if (event.type === "message.part.delta") {',
    '      if (properties.field !== "text" || typeof properties.delta !== "string") return;',
    '      const role = messageRoleById.get(messageRoleKey(sessionID, properties.messageID));',
    '      if (!role) return;',
    '      if (role === "user") clearPendingPreflightRecovery(rootSessionID, properties.messageID);',
    '      const text = appendMessagePartText(sessionID, properties.partID, properties.delta);',
    '      if (!text) return;',
    '      await publishMessageText({ role, text, messageID: properties.messageID, sessionID });',
    '      return;',
    '    }',
    '',
    '    if (event.type === "session.status") {',
    '      if (statusType === "busy" || statusType === "retry") {',
    '        // A new/retried turn proves buffered failures stale. Outcomes that',
    '        // Orca already saw are also retired so another root cannot resurrect',
    '        // an old error after its own later successful completion.',
    '        clearPendingPreflightRecovery(rootSessionID);',
    '        takePendingRootError(rootSessionID);',
    '        retireDeliveredTerminalOutcomes();',
    '        terminalOutcomeByRootSessionID.delete(rootSessionID);',
    '        // Refresh insertion order so aggregate metadata follows the latest root.',
    '        busyRootSessionIds.delete(rootSessionID);',
    '        busyRootSessionIds.add(rootSessionID);',
    '        busyRootOwnerBySessionID.set(rootSessionID, factoryID);',
    '        await publishAggregateStatus(rootSessionID);',
    '      }',
    '    }',
    '  }',
    '',
    '  async function disposePlugin() {',
    '    if (disposed) return;',
    '    disposed = true;',
    '    // Abort immediately instead of waiting behind the serialized post that',
    '    // dispose is meant to cancel. Shared posts owned by other directories',
    '    // remain live.',
    '    for (const [controller, ownerID] of inflightControllerOwner) {',
    '      if (ownerID === factoryID) controller.abort();',
    '    }',
    '    await enqueueCoordinatorWork(async () => {',
    '      let preferredSessionID = null;',
    '      for (const [sessionID, ownerID] of busyRootOwnerBySessionID) {',
    '        if (ownerID !== factoryID) continue;',
    '        preferredSessionID = sessionID;',
    '        busyRootOwnerBySessionID.delete(sessionID);',
    '        busyRootSessionIds.delete(sessionID);',
    '      }',
    '      for (const [key, request] of pendingRequestByKey) {',
    '        if (request.ownerID === factoryID) pendingRequestByKey.delete(key);',
    '      }',
    '      for (const [sessionID, pendingError] of pendingErrorByRootSessionID) {',
    '        if (pendingError.ownerID === factoryID) takePendingRootError(sessionID);',
    '      }',
    '      for (const [sessionID, recovery] of pendingPreflightRecoveryByRootSessionID) {',
    '        if (recovery.ownerID === factoryID) clearPendingPreflightRecovery(sessionID);',
    '      }',
    '      for (const [sessionID, outcome] of terminalOutcomeByRootSessionID) {',
    '        if (outcome.ownerID === factoryID) terminalOutcomeByRootSessionID.delete(sessionID);',
    '      }',
    '      for (const [sessionID, state] of assistantPartStateBySession) {',
    '        if (state.ownerID === factoryID) clearAssistantPartState(sessionID);',
    '      }',
    '      clearWaitingRetryIfSettled();',
    '      if (pendingRequestByKey.size > 0) {',
    '        await publishCurrentWaiting();',
    '      } else {',
    '        await flushAllPendingAssistantParts();',
    '        await publishAggregateStatus(preferredSessionID);',
    '      }',
    '      activeFactoryIDs.delete(factoryID);',
    '      if (activeFactoryIDs.size === 0) {',
    '        clearWaitingRetry();',
    '        clearLifecycleRetry();',
    '        for (const timer of preflightErrorTimerByRootSessionID.values()) clearTimeout(timer);',
    '        preflightErrorTimerByRootSessionID.clear();',
    '        for (const recovery of pendingPreflightRecoveryByRootSessionID.values()) {',
    '          clearTimeout(recovery.timer);',
    '        }',
    '        pendingPreflightRecoveryByRootSessionID.clear();',
    '        pendingErrorByRootSessionID.clear();',
    '        terminalOutcomeByRootSessionID.clear();',
    '        lastDeliveredTerminalOutcomeID = 0;',
    '        rootSessionById.clear();',
    '        messageRoleById.clear();',
    '        messagePartTextByKey.clear();',
    '      }',
    '    });',
    '  }',
    '',
    '  return {',
    '    event: ({ event }) => enqueuePluginWork(() => handleEvent(event)),',
    '    dispose: disposePlugin,',
    '  };',
    '};',
    ''
  ].join('\n')
}

// Why: OpenCode hooks used to run their own loopback HTTP server + IPC
// channel (pty:opencode-status). That pathway produced a synthetic terminal
// title but never entered agentStatusByPaneKey, so the unified dashboard
// never saw OpenCode sessions. The service now only installs the plugin
// file into OPENCODE_CONFIG_DIR — the plugin POSTs directly to the shared
// agent-hooks server (/hook/opencode), so OpenCode rides the same status
// pipeline as Claude/Codex/Gemini.
export class OpenCodeHookService {
  clearPty(_ptyId: string): void {
    // Why: OpenCode can materialize thousands of plugin runtime files under
    // OPENCODE_CONFIG_DIR. This teardown runs on Electron's main process hot
    // path, so recursive deletion here can freeze the whole app on Windows
    // while Node, antivirus, or indexing still holds file handles.
    //
    // Current builds use app/source-scoped config dirs, not PTY-scoped dirs,
    // so there is no live PTY-owned OpenCode filesystem state to remove.
  }

  buildPtyEnv(ptyId: string, existingConfigDir?: string | undefined): Record<string, string> {
    if (!isUsableId(ptyId)) {
      // Why: defense-in-depth. If the id fails the bounds guard, a user-set
      // OPENCODE_CONFIG_DIR should still be preserved so OpenCode loads the
      // user's own config — only the Orca status plugin is forfeited.
      return existingConfigDir ? { OPENCODE_CONFIG_DIR: existingConfigDir } : {}
    }

    if (!existingConfigDir) {
      // Why: OpenCode may install plugin dependencies under this root. Sharing
      // it prevents per-terminal node_modules churn and teardown freezes.
      const configDir = this.writeSharedPluginConfig()
      if (!configDir) {
        return {}
      }
      return { OPENCODE_CONFIG_DIR: configDir }
    }

    // Why: do NOT `mkdir -p` the user's typoed path — overriding it with an
    // Orca-owned dir is the exact config-replacement failure mode documented in
    // docs/opencode-config-dir-collision.md. Let OpenCode surface the typo on
    // its own; we only forfeit our status plugin for this pane.
    if (!existsSync(existingConfigDir)) {
      return { OPENCODE_CONFIG_DIR: existingConfigDir }
    }

    const overlayDir = this.getSourceOverlayDir(existingConfigDir)

    try {
      mkdirSync(overlayDir, { recursive: true })
      this.mirrorUserConfig(existingConfigDir, overlayDir)
      this.writePluginIntoOverlay(overlayDir)
    } catch {
      // Why: overlay creation is best-effort. Symlink-creation can fail on
      // Windows without developer mode (EPERM), userData can be read-only on
      // locked-down corporate machines, etc. In every case, preserve the
      // user's OPENCODE_CONFIG_DIR — a missing status plugin is a vastly
      // smaller harm than silently dropping the user's auth/models/keymap.
      return { OPENCODE_CONFIG_DIR: existingConfigDir }
    }

    return { OPENCODE_CONFIG_DIR: overlayDir }
  }

  private getOverlayRoot(): string {
    return join(app.getPath('userData'), OPENCODE_OVERLAY_DIR)
  }

  private getSourceOverlayDir(sourceConfigDir: string): string {
    return join(this.getOverlayRoot(), toSafeDirName(`source:${sourceConfigDir}`))
  }

  private getSharedConfigDir(): string {
    return join(app.getPath('userData'), OPENCODE_LEGACY_HOOKS_DIR, OPENCODE_SHARED_CONFIG_DIR)
  }

  private readOverlayManifest(overlayDir: string): OpenCodeOverlayManifest {
    try {
      const parsed = JSON.parse(
        readFileSync(join(overlayDir, OPENCODE_OVERLAY_MANIFEST_FILE), 'utf8')
      ) as Partial<OpenCodeOverlayManifest>
      return {
        topLevelEntries: Array.isArray(parsed.topLevelEntries) ? parsed.topLevelEntries : [],
        pluginEntries: Array.isArray(parsed.pluginEntries) ? parsed.pluginEntries : []
      }
    } catch {
      return { topLevelEntries: [], pluginEntries: [] }
    }
  }

  private writeOverlayManifest(overlayDir: string, manifest: OpenCodeOverlayManifest): void {
    writeFileSync(
      join(overlayDir, OPENCODE_OVERLAY_MANIFEST_FILE),
      `${JSON.stringify(manifest, null, 2)}\n`
    )
  }

  private clearManifestEntries(overlayDir: string, manifest: OpenCodeOverlayManifest): void {
    for (const entryName of manifest.topLevelEntries) {
      safeRemoveTree(join(overlayDir, entryName))
    }

    const overlayPluginsDir = join(overlayDir, 'plugins')
    for (const entryName of manifest.pluginEntries) {
      if (entryName === ORCA_OPENCODE_PLUGIN_FILE) {
        continue
      }
      safeRemoveTree(join(overlayPluginsDir, entryName))
    }
  }

  // Why: walks the user's OPENCODE_CONFIG_DIR top-level entries. The
  // `plugins/` subdirectory gets created as a real directory in the overlay
  // so Orca can drop a sibling file alongside the user's plugins; everything
  // else (opencode.json, auth.json, themes/, etc.) is mirrored as a single
  // top-level entry via symlink/junction so user edits propagate live on
  // POSIX (and on Windows-with-developer-mode) without copying files.
  private mirrorUserConfig(sourceDir: string, overlayDir: string): void {
    const previousManifest = this.readOverlayManifest(overlayDir)
    // Why: source-scoped overlays persist across terminals. Only remove paths
    // Orca previously mirrored, so deleted/replaced user config cannot stay
    // stale while OpenCode-owned runtime dirs such as node_modules survive.
    this.clearManifestEntries(overlayDir, previousManifest)

    const nextManifest: OpenCodeOverlayManifest = { topLevelEntries: [], pluginEntries: [] }

    for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
      const sourcePath = join(sourceDir, entry.name)

      if (entry.name === 'plugins') {
        // Why: check isSymbolicLink BEFORE isDirectory — a Windows junction
        // can report both as true on a Dirent, and we must take the symlink
        // branch so the per-entry mirroring (not a single mirrorEntry call
        // that would create a symlink at <overlay>/plugins) handles it.
        const isSymlink = entry.isSymbolicLink()
        let isLinkPointingToDir = false
        if (isSymlink) {
          try {
            isLinkPointingToDir = statSync(sourcePath).isDirectory()
          } catch {
            // Why: broken symlink (target missing) or permission error — fall
            // through to the default mirrorEntry path so the dangling link is
            // mirrored verbatim rather than write-through-resolved.
            isLinkPointingToDir = false
          }
        }

        if ((!isSymlink && entry.isDirectory()) || isLinkPointingToDir) {
          // Why: when the user's plugins/ is a symlink-to-dir, resolve to the
          // real target so readdir returns the actual entries and child paths
          // join against the resolved root. mirrorEntry then creates symlinks
          // pointing into the resolved real plugins (not back through the
          // user's link), and <overlay>/plugins itself stays a real dir so
          // writePluginIntoOverlay can never write through to the user's FS.
          const resolvedSource = isLinkPointingToDir ? realpathSync(sourcePath) : sourcePath
          const overlayPluginsDir = join(overlayDir, 'plugins')
          mkdirSync(overlayPluginsDir, { recursive: true })
          for (const pluginEntry of readdirSync(resolvedSource, { withFileTypes: true })) {
            // Why: skip a user file with the same filename as Orca's plugin —
            // mirroring it here would either resolve a same-named target via
            // symlink (writePluginIntoOverlay then clobbers the user's file
            // through the link) or collide on Windows with the directory entry
            // about to be created by writePluginIntoOverlay. Either way the
            // user's plugin would be lost. Skipping yields the desired
            // semantics: Orca's status plugin runs and the user's same-named
            // plugin is shadowed for this PTY only — their source file on disk
            // is untouched.
            if (pluginEntry.name === ORCA_OPENCODE_PLUGIN_FILE) {
              continue
            }
            mirrorEntry(
              join(resolvedSource, pluginEntry.name),
              join(overlayPluginsDir, pluginEntry.name)
            )
            nextManifest.pluginEntries.push(pluginEntry.name)
          }
          continue
        }
      }

      mirrorEntry(sourcePath, join(overlayDir, entry.name))
      nextManifest.topLevelEntries.push(entry.name)
    }

    this.writeOverlayManifest(overlayDir, nextManifest)
  }

  // Why: write Orca's status plugin into the overlay's plugins/ dir. The
  // pre-write unlink is the load-bearing part — POSIX writeFileSync over a
  // symlink writes through to the link target, so without it a user-owned
  // plugin with this filename would be clobbered through a mirrored link.
  // Skipping the same-named user file in mirrorUserConfig already prevents
  // the link from being created, but the unlink keeps this function safe
  // even if a stale overlay slips through with the link still in place.
  private writePluginIntoOverlay(overlayDir: string): void {
    const pluginsDir = join(overlayDir, 'plugins')
    mkdirSync(pluginsDir, { recursive: true })
    const pluginPath = join(pluginsDir, ORCA_OPENCODE_PLUGIN_FILE)
    try {
      unlinkSync(pluginPath)
    } catch {
      // No-op: file may not exist on a fresh overlay. Any persistent failure
      // (e.g. permissions) will surface on the writeFileSync below.
    }
    writeFileSync(pluginPath, getOpenCodePluginSource())
  }

  private writeSharedPluginConfig(): string | null {
    const configDir = this.getSharedConfigDir()
    const pluginsDir = join(configDir, 'plugins')
    try {
      mkdirSync(pluginsDir, { recursive: true })
      writeFileSync(join(pluginsDir, ORCA_OPENCODE_PLUGIN_FILE), getOpenCodePluginSource())
    } catch {
      // Why: on Windows, userData directories can be locked by antivirus or
      // indexers (EPERM/EBUSY). Plugin config is non-critical — the PTY should
      // still spawn without the OpenCode status plugin.
      return null
    }
    return configDir
  }
}

export const openCodeHookService = new OpenCodeHookService()
export const _internals = {
  getOpenCodePluginSource,
  isUsableId,
  toSafeDirName
}
