/**
 * Builds the OpenCode 2 `setup(ctx)` entry point: a V2 client facade for the
 * engine session lookups plus the subscription pump feeding the event adapter.
 */
export function getStatusPluginV2SetupSource(): string[] {
  return [
    'function createOrcaV2Client(ctx) {',
    '  // Why: the engine session lookups accept either SDK generation and read',
    '  // `result.data`, so expose the V2 context domain methods in that shape.',
    '  const sessionApi = ctx && ctx.session;',
    '  return {',
    '    session: {',
    '      get: async (input, options) => {',
    '        if (!sessionApi || typeof sessionApi.get !== "function") {',
    '          return { data: undefined };',
    '        }',
    '        const sessionID =',
    '          input && (input.sessionID || (input.path && input.path.id));',
    '        const result = await sessionApi.get({ sessionID }, options);',
    '        return result && result.data ? result : { data: result };',
    '      },',
    '      list: async (input, options) => {',
    '        if (!sessionApi || typeof sessionApi.list !== "function") {',
    '          return { data: [] };',
    '        }',
    '        const result = await sessionApi.list(input, options);',
    '        return result && result.data ? result : { data: result };',
    '      }',
    '    }',
    '  };',
    '}',
    '',
    'async function setupOrcaV2Compat(ctx) {',
    '  if (!ctx || !ctx.event || typeof ctx.event.subscribe !== "function") {',
    '    console.warn(',
    '      "[orca-hook] OpenCode 2 event API unavailable; status reporting disabled"',
    '    );',
    '    return;',
    '  }',
    '  let hooks;',
    '  try {',
    '    hooks = await OrcaOpenCodeStatusPlugin({ client: createOrcaV2Client(ctx) });',
    '  } catch (err) {',
    '    console.warn(',
    '      "[orca-hook] V2 setup failed:",',
    '      err && err.message ? err.message : err',
    '    );',
    '    return;',
    '  }',
    '  const controller = new AbortController();',
    '  const pump = (async () => {',
    '    try {',
    '      const stream = await ctx.event.subscribe({ signal: controller.signal });',
    '      for await (const event of stream) {',
    '        const mapped = mapOrcaV2EventToLegacy(event);',
    '        for (const legacyEvent of mapped) {',
    '          try {',
    '            await hooks.event({ event: legacyEvent });',
    '          } catch (err) {',
    '            if (!controller.signal.aborted) {',
    '              console.warn(',
    '                "[orca-hook] V2 event handler failed:",',
    '                err && err.message ? err.message : err',
    '              );',
    '            }',
    '          }',
    '        }',
    '      }',
    '    } catch (err) {',
    '      if (!controller.signal.aborted) {',
    '        console.warn(',
    '          "[orca-hook] V2 event stream ended:",',
    '          err && err.message ? err.message : err',
    '        );',
    '      }',
    '    }',
    '  })();',
    '  return async () => {',
    '    controller.abort();',
    '    try {',
    '      await hooks.dispose();',
    '    } catch {}',
    '    try {',
    '      await pump;',
    '    } catch {}',
    '  };',
    '}'
  ]
}
