export function getStatusPluginV2SetupSource(): string[] {
  return [
    '// Why: OpenCode v2 validates the module default export against',
    '// `{ id, effect } | { id, setup }` and rejects the legacy v1 shape',
    '// `{ id, server }` with `Missing key at ["default"]["effect"]` +',
    '// `Missing key at ["default"]["setup"]`, which disables all status updates.',
    '// This adapter reuses the tested v1 factory so both loaders share one',
    '// implementation: v1 mapping is `event -> ctx.event.subscribe()` and',
    '// `dispose -> cleanup returned by setup`. The `server` key stays on the',
    '// default export for pre-v2 loaders.',
    'function toV1LifecycleEvent(event) {',
    '  // Why: v2 ctx.event.subscribe() yields encoded OpenCodeEvent items shaped',
    '  // `{ id, created, type, data }`, while the v1 factory reads',
    '  // `event.properties.*`. Only lifecycle-relevant names cross the bridge,',
    '  // and only with payload shapes the factory understands — anything else',
    '  // returns null so v2 text/preview vocabulary (which carries no v1 role or',
    '  // message identity) can never be mislabeled as v1 message parts.',
    '  // Why: a normal v2 turn emits NO session.status/session.idle — liveness is',
    '  // `session.execution.started` -> `...succeeded|failed|interrupted`, each',
    '  // carrying only `{ sessionID }`. Those map to v1 busy/idle so the shared',
    '  // aggregation, child-attribution, and retry logic applies unchanged.',
    '  // Shapes below verified against @opencode/schema@2.0.7 source:',
    '  // session.status -> data { sessionID, status }, session.idle -> data',
    '  // { sessionID }, session.created -> data { sessionID, parentID? },',
    '  // permission.asked -> data { sessionID, id }, permission.replied -> data',
    '  // { sessionID, requestID }. No question.* or permission.v2.* events exist',
    '  // there, so there is nothing to bridge for them.',
    '  if (!event || typeof event.type !== "string") return null;',
    '  const data = event.data || {};',
    '  switch (event.type) {',
    '    case "session.status":',
    '    case "session.idle":',
    '    case "permission.asked":',
    '    case "permission.replied":',
    '      return { type: event.type, properties: data };',
    '    case "session.created":',
    '      if (!data || typeof data.sessionID !== "string") return null;',
    '      return { type: event.type, properties: { info: { id: data.sessionID, parentID: data.parentID } } };',
    '    case "session.execution.started":',
    '      if (!data || typeof data.sessionID !== "string") return null;',
    '      return { type: "session.status", properties: { sessionID: data.sessionID, status: { type: "busy" } } };',
    '    case "session.execution.succeeded":',
    '    case "session.execution.failed":',
    '    case "session.execution.interrupted":',
    '      if (!data || typeof data.sessionID !== "string") return null;',
    '      return { type: "session.idle", properties: { sessionID: data.sessionID } };',
    '    default:',
    '      return null;',
    '  }',
    '}',
    '',
    'const seenV2SessionIDs = new Set();',
    'function rememberSeenV2Session(sessionID) {',
    '  // Why: bounded like the other module caches so long-running processes do',
    '  // not grow this set without limit.',
    '  if (!sessionID) return;',
    '  if (seenV2SessionIDs.size >= 128 && !seenV2SessionIDs.has(sessionID)) {',
    '    const first = seenV2SessionIDs.values().next().value;',
    '    if (first !== undefined) seenV2SessionIDs.delete(first);',
    '  }',
    '  seenV2SessionIDs.add(sessionID);',
    '}',
    '',
    'async function ensureV2SessionStart(client, sessionID, forward) {',
    '  // Why: v1 always posts SessionStart at session creation, before any busy.',
    '  // v2 turns often start with `session.execution.started` and no creation',
    '  // event, so synthesize the start on first sight to preserve ordering — but',
    '  // only for lookup-confirmed roots. A wrongly-rooted child would poison the',
    '  // session cache; on unknown lineage skip the synthetic (busy still posts).',
    '  // Why: resolveRootSessionID (not a bare session.get) so the lookup inherits',
    '  // its deadline and cache. The mark is released on skip so a transient',
    '  // failure retries on the next execution instead of suppressing Start forever.',
    '  if (!sessionID || seenV2SessionIDs.has(sessionID)) return;',
    '  rememberSeenV2Session(sessionID);',
    '  const rootSessionID = await resolveRootSessionID(client, sessionID);',
    '  if (rootSessionID !== sessionID) {',
    '    seenV2SessionIDs.delete(sessionID);',
    '    return;',
    '  }',
    '  await forward({ type: "session.created", properties: { info: { id: sessionID, parentID: undefined } } });',
    '}',
    '',
    'function buildV1ClientShim(ctx) {',
    '  // Why: the v1 factory expects `client.session.get/list`, but the v2',
    '  // context exposes `ctx.session.get({ sessionID })` (single input argument,',
    '  // raw Session.Info result) instead of a separate `client` property. Prefer',
    '  // a native v1 client when present (backward compat), otherwise adapt the v2',
    '  // session domain to the v1 shape. Return undefined when neither is available',
    '  // so the factory fail-opens (root busy/idle still reported).',
    '  // Why: only the observed shapes are adapted — `{ sessionID }` and legacy',
    '  // `{ path: { id } }` inputs, unwrapped results. Anything else throws into',
    '  // the lookup timeout/fail-open path, which skips the synthetic Start while',
    '  // Busy still posts. The v2 domain takes a single input, so there is no',
    '  // channel for the abort signal; the caller-side deadline still bounds the wait.',
    '  if (ctx?.client?.session?.get || ctx?.client?.session?.list) return ctx.client;',
    '  const sessionDomain = ctx?.session;',
    '  if (!sessionDomain?.get) return undefined;',
    '  return {',
    '    session: {',
    '      get: async (...args) => {',
    '        const first = args[0] || {};',
    '        const sessionID = first.sessionID || first.path?.id;',
    '        if (!sessionID) throw new Error("missing sessionID");',
    '        const raw = await sessionDomain.get({ sessionID });',
    '        if (!raw || !raw.id) throw new Error("session not found");',
    '        return { data: raw };',
    '      },',
    '    },',
    '  };',
    '}',
    '',
    'async function OrcaOpenCodeStatusSetup(ctx) {',
    '  // Why: without an event stream there is nothing to forward — return a',
    '  // no-op cleanup WITHOUT instantiating the factory, so a loader that',
    '  // invokes setup on a pre-v2 context cannot spawn a ghost owner that never',
    '  // receives events. The v1 `server` factory owns the lifecycle there.',
    '  if (!ctx?.event?.subscribe) {',
    '    return () => {};',
    '  }',
    '  const shimClient = buildV1ClientShim(ctx);',
    '  const hooks = await OrcaOpenCodeStatusPlugin({ ...(ctx || {}), client: shimClient });',
    '  const controller = new AbortController();',
    '  const forward = (v1Event) => hooks.event?.({ event: v1Event });',
    '  void (async () => {',
    '    try {',
    '      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {',
    '        try {',
    '          if (event?.type === "session.execution.started" && event?.data?.sessionID) {',
    '            await ensureV2SessionStart(shimClient, event.data.sessionID, forward);',
    '          }',
    '          let v1Event = null;',
    '          if (event?.type === "session.created" && typeof event?.data?.sessionID === "string") {',
    '            // Why: skip when Start was already synthesized or posted, so a late',
    '            // creation event can never double-post it.',
    '            if (!seenV2SessionIDs.has(event.data.sessionID)) {',
    '              rememberSeenV2Session(event.data.sessionID);',
    '              v1Event = toV1LifecycleEvent(event);',
    '            }',
    '          } else {',
    '            v1Event = toV1LifecycleEvent(event);',
    '          }',
    '          if (v1Event) await forward(v1Event);',
    '        } catch {',
    '          // Hook delivery must never reject into OpenCode.',
    '        }',
    '      }',
    '    } catch {',
    '      // Abort on cleanup is expected.',
    '    } finally {',
    '      // Why: a terminated stream (server gone, loader unloading) must not',
    '      // leave the factory registered as an active owner that can never',
    '      // clear — dispose is idempotent, so later loader cleanup stays safe.',
    '      await hooks.dispose?.();',
    '    }',
    '  })();',
    '  return () => {',
    '    controller.abort();',
    '    return hooks.dispose?.();',
    '  };',
    '}',
    ''
  ]
}
