/**
 * Builds the OpenCode 2 event adapter for the generated status plugin: V2
 * `session.*` / `permission.*` / `form.*` events are mapped onto the V1 events
 * the engine consumes, so delivery, ownership and previews keep working.
 */
export function getStatusPluginV2EventSource(): string[] {
  return [
    '// Why: OpenCode 2 reworked both the plugin API (default `{ id, setup }`) and',
    '// its event stream. V2 emits `session.status`, `session.idle`, `session.text.*`,',
    '// `permission.*` and `form.*` events whose payloads live under `data`, while the',
    '// engine below consumes V1 events with a `properties` envelope. This adapter maps',
    '// the V2 stream onto those V1 shapes so the existing delivery, ownership and',
    '// preview logic keeps working unchanged.',
    'const ORCA_V2_FORM_HEADER_MAX = 30;',
    '',
    'function orcaV2FormFieldToQuestion(field) {',
    '  const title =',
    '    field && typeof field.title === "string" && field.title.length > 0',
    '      ? field.title',
    '      : String((field && field.key) || "Question");',
    '  const options = Array.isArray(field && field.options)',
    '    ? field.options',
    '        .filter(',
    '          (option) =>',
    '            option && typeof option.label === "string" && option.label.length > 0',
    '        )',
    '        .map((option) => ({',
    '          label: option.label,',
    '          description:',
    '            typeof option.description === "string" ? option.description : ""',
    '        }))',
    '    : [];',
    '  const question = {',
    '    question: title,',
    '    header: title.slice(0, ORCA_V2_FORM_HEADER_MAX),',
    '    options',
    '  };',
    '  if (field && field.type === "multiselect") question.multiSelect = true;',
    '  return question;',
    '}',
    '',
    'function mapOrcaV2EventToLegacy(event) {',
    '  const type = event && event.type;',
    '  const data = event && event.data;',
    '  if (!type || !data) return [];',
    '  const sessionID = data.sessionID;',
    '',
    '  if (type === "session.created") {',
    '    return [',
    '      {',
    '        type: "session.created",',
    '        properties: { info: { id: data.sessionID, parentID: data.parentID } }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.status") {',
    '    if (!data.status || typeof data.status.type !== "string") return [];',
    '    return [',
    '      { type: "session.status", properties: { sessionID, status: data.status } }',
    '    ];',
    '  }',
    '  // Why: OpenCode 2 turn boundaries arrive as session.execution.* events;',
    '  // session.status is not emitted for ordinary busy/idle transitions.',
    '  if (type === "session.execution.started") {',
    '    return [',
    '      {',
    '        type: "session.status",',
    '        properties: { sessionID, status: { type: "busy" } }',
    '      }',
    '    ];',
    '  }',
    '  if (',
    '    type === "session.execution.succeeded" ||',
    '    type === "session.execution.interrupted" ||',
    '    type === "session.execution.failed"',
    '  ) {',
    '    return [',
    '      {',
    '        type: "session.status",',
    '        properties: { sessionID, status: { type: "idle" } }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.idle") {',
    '    return [{ type: "session.idle", properties: { sessionID } }];',
    '  }',
    '  if (type === "session.text.started") {',
    '    return [',
    '      {',
    '        type: "message.updated",',
    '        properties: { info: { id: data.assistantMessageID, role: "assistant" } }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.text.delta") {',
    '    if (typeof data.delta !== "string" || data.delta.length === 0) return [];',
    '    return [',
    '      {',
    '        type: "message.updated",',
    '        properties: { info: { id: data.assistantMessageID, role: "assistant" } }',
    '      },',
    '      {',
    '        type: "message.part.delta",',
    '        properties: {',
    '          sessionID,',
    '          messageID: data.assistantMessageID,',
    '          field: "text",',
    '          delta: data.delta',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.text.ended") {',
    '    if (typeof data.text !== "string" || data.text.length === 0) return [];',
    '    return [',
    '      {',
    '        type: "message.part.updated",',
    '        properties: {',
    '          sessionID,',
    '          part: {',
    '            type: "text",',
    '            messageID: data.assistantMessageID,',
    '            text: data.text,',
    '            synthetic: false',
    '          }',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.inbox.enqueued") {',
    '    const item = data.item;',
    '    if (',
    '      !item ||',
    '      item.type !== "user" ||',
    '      !item.payload ||',
    '      typeof item.payload.text !== "string" ||',
    '      item.payload.text.length === 0',
    '    ) {',
    '      return [];',
    '    }',
    '    const messageID = data.inboxID || item.id;',
    '    return [',
    '      {',
    '        type: "message.updated",',
    '        properties: { info: { id: messageID, role: "user" } }',
    '      },',
    '      {',
    '        type: "message.part.updated",',
    '        properties: {',
    '          sessionID,',
    '          part: {',
    '            type: "text",',
    '            messageID,',
    '            text: item.payload.text,',
    '            synthetic: false',
    '          }',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "permission.asked") {',
    '    return [',
    '      {',
    '        type: "permission.asked",',
    '        properties: {',
    '          id: data.id,',
    '          sessionID,',
    '          permission: data.action,',
    '          patterns: Array.isArray(data.resources) ? data.resources : [],',
    '          metadata:',
    '            data.metadata && typeof data.metadata === "object"',
    '              ? data.metadata',
    '              : {},',
    '          always: Array.isArray(data.save) ? data.save : [],',
    '          tool: data.source',
    '            ? { messageID: data.source.messageID, callID: data.source.id }',
    '            : undefined',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "permission.replied") {',
    '    return [',
    '      {',
    '        type: "permission.replied",',
    '        properties: { sessionID, requestID: data.requestID || data.id }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "form.created") {',
    '    const form = data.form;',
    '    if (!form || !form.id) return [];',
    '    const questions = Array.isArray(form.fields)',
    '      ? form.fields.map(orcaV2FormFieldToQuestion)',
    '      : [];',
    '    return [',
    '      {',
    '        type: "question.asked",',
    '        properties: {',
    '          id: form.id,',
    '          sessionID: form.sessionID || sessionID,',
    '          questions',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "form.replied") {',
    '    return [',
    '      {',
    '        type: "question.replied",',
    '        properties: { sessionID, requestID: data.requestID || data.id }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "form.cancelled") {',
    '    return [',
    '      {',
    '        type: "question.rejected",',
    '        properties: { sessionID, requestID: data.requestID || data.id }',
    '      }',
    '    ];',
    '  }',
    '  return [];',
    '}',
    ''
  ]
}
