export function getStatusPluginV2SetupSource(): string[] {
  return [
    '// Why: OpenCode v2 validates the module default export against',
    '// `{ id, effect } | { id, setup }` and rejects the legacy v1 shape',
    '// `{ id, server }` with `Missing key at ["default"]["effect"]` +',
    '// `Missing key at ["default"]["setup"]`, which disables all status updates.',
    '// This adapter reuses the tested v1 factory so both loaders share one',
    '// implementation: v1 mapping is `event -> ctx.event.subscribe()` and',
    '// `dispose -> cleanup returned by setup`. The `server` key stays on the',
    '// default export for pre-v2 loaders.',
    'function toV1LifecycleEvent(event) {',
    '  // Why: v2 ctx.event.subscribe() yields encoded OpenCodeEvent items shaped',
    '  // `{ id, created, type, data }`, while the v1 factory reads',
    '  // `event.properties.*`. Only lifecycle-relevant names cross the bridge,',
    '  // and only with payload shapes the factory understands — anything else',
    '  // returns null so v2 text/preview vocabulary (which carries no v1 role or',
    '  // message identity) can never be mislabeled as v1 message parts.',
    '  if (!event || typeof event.type !== "string") return null;',
    '  const data = event.data || {};',
    '  switch (event.type) {',
    '    case "session.status":',
    '    case "session.idle":',
    '    case "permission.asked":',
    '    case "permission.replied":',
    '      return { type: event.type, properties: data };',
    '    case "session.created":',
    '      // Why: v2 reports the session flat (`data.id`, `data.parentID`) where',
    '      // v1 nests it under `properties.info`.',
    '      if (!data || typeof data.id !== "string") return null;',
    '      return { type: event.type, properties: { info: { id: data.id, parentID: data.parentID } } };',
    '    default:',
    '      return null;',
    '  }',
    '}',
    '',
    'function buildV1ClientShim(ctx) {',
    '  // Why: the v1 factory expects `client.session.get/list`, but the v2',
    '  // context exposes domain methods like `ctx.session.get({ sessionID })`',
    '  // (single input argument, raw Session.Info result) instead of a separate',
    '  // `client` property. Prefer a native v1 client when present (backward',
    '  // compat), otherwise adapt the v2 session domain to the v1 shape. Return',
    '  // undefined when neither is available so the factory fail-opens (root',
    '  // busy/idle still reported). Lookup timeouts stay enforced by the caller.',
    '  if (ctx?.client?.session?.get || ctx?.client?.session?.list) return ctx.client;',
    '  const sessionDomain = ctx?.session || ctx?.data?.session;',
    '  if (!sessionDomain?.get && !sessionDomain?.list) return undefined;',
    '  const shim = {};',
    '  if (sessionDomain.get) {',
    '    shim.get = async (...args) => {',
    '      const first = args[0] || {};',
    '      const sessionID = first.sessionID || first.path?.id || first.id;',
    '      if (!sessionID) throw new Error("missing sessionID");',
    '      const raw = await sessionDomain.get({ sessionID });',
    '      const data = raw?.data || raw;',
    '      if (!data?.id) throw new Error("session not found");',
    '      return { data };',
    '    };',
    '  }',
    '  if (sessionDomain.list) {',
    '    // Why: no arg-shape probing here — the v2 list (when present) takes a',
    '    // single input. Errors propagate to the lookup timeout/fail-open path,',
    '    // so an aborted lookup stays cancelled instead of retried.',
    '    shim.list = async () => {',
    '      const raw = await sessionDomain.list({});',
    '      const data = Array.isArray(raw) ? raw : raw?.data || [];',
    '      return { data };',
    '    };',
    '  }',
    '  return { session: shim };',
    '}',
    '',
    'async function OrcaOpenCodeStatusSetup(ctx) {',
    '  // Why: without an event stream there is nothing to forward — return a',
    '  // no-op cleanup WITHOUT instantiating the factory, so a loader that',
    '  // invokes setup on a pre-v2 context cannot spawn a ghost owner that never',
    '  // receives events. The v1 `server` factory owns the lifecycle there.',
    '  if (!ctx?.event?.subscribe) {',
    '    return () => {};',
    '  }',
    '  const hooks = await OrcaOpenCodeStatusPlugin({ ...(ctx || {}), client: buildV1ClientShim(ctx) });',
    '  const controller = new AbortController();',
    '  void (async () => {',
    '    try {',
    '      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {',
    '        try {',
    '          const v1Event = toV1LifecycleEvent(event);',
    '          if (v1Event) await hooks.event?.({ event: v1Event });',
    '        } catch {',
    '          // Hook delivery must never reject into OpenCode.',
    '        }',
    '      }',
    '    } catch {',
    '      // Abort on cleanup is expected.',
    '    } finally {',
    '      // Why: a terminated stream (server gone, loader unloading) must not',
    '      // leave the factory registered as an active owner that can never',
    '      // clear — dispose is idempotent, so later loader cleanup stays safe.',
    '      await hooks.dispose?.();',
    '    }',
    '  })();',
    '  return () => {',
    '    controller.abort();',
    '    return hooks.dispose?.();',
    '  };',
    '}',
    ''
  ]
}
