export function getStatusPluginV2CompatSource(): string[] {
  // Why: OpenCode 2 drives plugins through `setup(ctx)` and a `data`-shaped event stream;
  // these lines map that stream onto the V1 events the engine above consumes.
  return [
    '// Why: OpenCode 2 reworked both the plugin API (default `{ id, setup }`) and',
    '// its event stream. V2 emits `session.status`, `session.idle`, `session.text.*`,',
    '// `permission.*` and `form.*` events whose payloads live under `data`, while the',
    '// engine below consumes V1 events with a `properties` envelope. This adapter maps',
    '// the V2 stream onto those V1 shapes so the existing delivery, ownership and',
    '// preview logic keeps working unchanged.',
    'const ORCA_V2_FORM_HEADER_MAX = 30;',
    '',
    'function orcaV2FormFieldToQuestion(field) {',
    '  const title =',
    '    field && typeof field.title === "string" && field.title.length > 0',
    '      ? field.title',
    '      : String((field && field.key) || "Question");',
    '  const options = Array.isArray(field && field.options)',
    '    ? field.options',
    '        .filter(',
    '          (option) =>',
    '            option && typeof option.label === "string" && option.label.length > 0',
    '        )',
    '        .map((option) => ({',
    '          label: option.label,',
    '          description:',
    '            typeof option.description === "string" ? option.description : ""',
    '        }))',
    '    : [];',
    '  const question = {',
    '    question: title,',
    '    header: title.slice(0, ORCA_V2_FORM_HEADER_MAX),',
    '    options',
    '  };',
    '  if (field && field.type === "multiselect") question.multiple = true;',
    '  if (field && field.custom === true) question.custom = true;',
    '  return question;',
    '}',
    '',
    'function mapOrcaV2EventToLegacy(event) {',
    '  const type = event && event.type;',
    '  const data = event && event.data;',
    '  if (!type || !data) return [];',
    '  const sessionID = data.sessionID;',
    '',
    '  if (type === "session.created") {',
    '    return [',
    '      {',
    '        type: "session.created",',
    '        properties: { info: { id: data.sessionID, parentID: data.parentID } }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.status") {',
    '    if (!data.status || typeof data.status.type !== "string") return [];',
    '    return [',
    '      { type: "session.status", properties: { sessionID, status: data.status } }',
    '    ];',
    '  }',
    '  // Why: OpenCode 2 turn boundaries arrive as session.execution.* events;',
    '  // session.status is not emitted for ordinary busy/idle transitions.',
    '  if (type === "session.execution.started") {',
    '    return [',
    '      {',
    '        type: "session.status",',
    '        properties: { sessionID, status: { type: "busy" } }',
    '      }',
    '    ];',
    '  }',
    '  if (',
    '    type === "session.execution.succeeded" ||',
    '    type === "session.execution.interrupted" ||',
    '    type === "session.execution.failed"',
    '  ) {',
    '    return [',
    '      {',
    '        type: "session.status",',
    '        properties: { sessionID, status: { type: "idle" } }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.idle") {',
    '    return [{ type: "session.idle", properties: { sessionID } }];',
    '  }',
    '  if (type === "session.text.started") {',
    '    return [',
    '      {',
    '        type: "message.updated",',
    '        properties: { info: { id: data.assistantMessageID, role: "assistant" } }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.text.delta") {',
    '    if (typeof data.delta !== "string" || data.delta.length === 0) return [];',
    '    return [',
    '      {',
    '        type: "message.updated",',
    '        properties: { info: { id: data.assistantMessageID, role: "assistant" } }',
    '      },',
    '      {',
    '        type: "message.part.delta",',
    '        properties: {',
    '          sessionID,',
    '          messageID: data.assistantMessageID,',
    '          field: "text",',
    '          delta: data.delta',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.text.ended") {',
    '    if (typeof data.text !== "string" || data.text.length === 0) return [];',
    '    return [',
    '      {',
    '        type: "message.part.updated",',
    '        properties: {',
    '          sessionID,',
    '          part: {',
    '            type: "text",',
    '            messageID: data.assistantMessageID,',
    '            text: data.text,',
    '            synthetic: false',
    '          }',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "session.inbox.enqueued") {',
    '    const item = data.item;',
    '    if (',
    '      !item ||',
    '      item.type !== "user" ||',
    '      !item.payload ||',
    '      typeof item.payload.text !== "string" ||',
    '      item.payload.text.length === 0',
    '    ) {',
    '      return [];',
    '    }',
    '    const messageID = data.inboxID || item.id;',
    '    return [',
    '      {',
    '        type: "message.updated",',
    '        properties: { info: { id: messageID, role: "user" } }',
    '      },',
    '      {',
    '        type: "message.part.updated",',
    '        properties: {',
    '          sessionID,',
    '          part: {',
    '            type: "text",',
    '            messageID,',
    '            text: item.payload.text,',
    '            synthetic: false',
    '          }',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "permission.asked") {',
    '    return [',
    '      {',
    '        type: "permission.asked",',
    '        properties: {',
    '          id: data.id,',
    '          sessionID,',
    '          permission: data.action,',
    '          patterns: Array.isArray(data.resources) ? data.resources : [],',
    '          metadata:',
    '            data.metadata && typeof data.metadata === "object"',
    '              ? data.metadata',
    '              : {},',
    '          always: Array.isArray(data.save) ? data.save : [],',
    '          tool: data.source',
    '            ? { messageID: data.source.messageID, callID: data.source.id }',
    '            : undefined',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "permission.replied") {',
    '    return [',
    '      {',
    '        type: "permission.replied",',
    '        properties: { sessionID, requestID: data.requestID || data.id }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "form.created") {',
    '    const form = data.form;',
    '    if (!form || !form.id) return [];',
    '    const questions = Array.isArray(form.fields)',
    '      ? form.fields.map(orcaV2FormFieldToQuestion)',
    '      : [];',
    '    return [',
    '      {',
    '        type: "question.asked",',
    '        properties: {',
    '          id: form.id,',
    '          sessionID: form.sessionID || sessionID,',
    '          questions',
    '        }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "form.replied") {',
    '    return [',
    '      {',
    '        type: "question.replied",',
    '        properties: { sessionID, requestID: data.id }',
    '      }',
    '    ];',
    '  }',
    '  if (type === "form.cancelled") {',
    '    return [',
    '      {',
    '        type: "question.rejected",',
    '        properties: { sessionID, requestID: data.id }',
    '      }',
    '    ];',
    '  }',
    '  return [];',
    '}',
    '',
    'function createOrcaV2Client(ctx) {',
    '  // Why: the engine session lookups accept either SDK generation and read',
    '  // `result.data`, so expose the V2 context domain methods in that shape.',
    '  return {',
    '    session: {',
    '      get: async (input, options) => {',
    '        const sessionID =',
    '          input && (input.sessionID || (input.path && input.path.id));',
    '        const result = await ctx.session.get({ sessionID }, options);',
    '        return result && result.data ? result : { data: result };',
    '      },',
    '      list: async (input, options) => {',
    '        if (!ctx.session || typeof ctx.session.list !== "function") {',
    '          return { data: [] };',
    '        }',
    '        const result = await ctx.session.list(input, options);',
    '        return result && result.data ? result : { data: result };',
    '      }',
    '    }',
    '  };',
    '}',
    '',
    'async function setupOrcaV2Compat(ctx) {',
    '  if (!ctx || !ctx.event || typeof ctx.event.subscribe !== "function") {',
    '    return;',
    '  }',
    '  let hooks;',
    '  try {',
    '    hooks = await OrcaOpenCodeStatusPlugin({ client: createOrcaV2Client(ctx) });',
    '  } catch (err) {',
    '    console.warn(',
    '      "[orca-hook] V2 setup failed:",',
    '      err && err.message ? err.message : err',
    '    );',
    '    return;',
    '  }',
    '  const controller = new AbortController();',
    '  const pump = (async () => {',
    '    try {',
    '      const stream = await ctx.event.subscribe({ signal: controller.signal });',
    '      for await (const event of stream) {',
    '        const mapped = mapOrcaV2EventToLegacy(event);',
    '        for (const legacyEvent of mapped) {',
    '          try {',
    '            await hooks.event({ event: legacyEvent });',
    '          } catch (err) {',
    '            if (!controller.signal.aborted) {',
    '              console.warn(',
    '                "[orca-hook] V2 event handler failed:",',
    '                err && err.message ? err.message : err',
    '              );',
    '            }',
    '          }',
    '        }',
    '      }',
    '    } catch (err) {',
    '      if (!controller.signal.aborted) {',
    '        console.warn(',
    '          "[orca-hook] V2 event stream ended:",',
    '          err && err.message ? err.message : err',
    '        );',
    '      }',
    '    }',
    '  })();',
    '  return async () => {',
    '    controller.abort();',
    '    try {',
    '      await hooks.dispose();',
    '    } catch {}',
    '    try {',
    '      await pump;',
    '    } catch {}',
    '  };',
    '}'
  ]
}
