export function getPiAgentStatusPostQueueSourceLines(): string[] {
  return [
    'type HookPost = { hookEventName: string; extra: Record<string, unknown>; metadata: Record<string, unknown>; ompRuntime: boolean; revision: number; attempts: number; delivered: boolean; final?: boolean }',
    'let activePost = false',
    'let pendingPost: HookPost | null = null',
    'let latestPost: HookPost | null = null',
    // Why: a closed session's last word shares no slot with the next session's posts, which would replace it.
    'const finalPosts: HookPost[] = []',
    'let finalRetryTimer: ReturnType<typeof setTimeout> | null = null',
    '// A newer snapshot or session boundary retires every older retry.',
    'let postRevision = 0',
    'let retryTimer: ReturnType<typeof setTimeout> | null = null',
    '',
    'function cancelPostRetry(): void {',
    '  if (retryTimer !== null) clearTimeout(retryTimer)',
    '  retryTimer = null',
    '}',
    '',
    '// Why: a queued or scheduled post builds its body later, so it already carries newer state.',
    'function hasQueuedPost(): boolean {',
    '  return pendingPost !== null || retryTimer !== null',
    '}',
    '',
    'function resetPostQueue(): void {',
    '  cancelPostRetry()',
    '  postRevision++',
    // Why: a completion not yet sent is still the last word on its run, whatever replaces the session.
    "  if (pendingPost?.hookEventName === 'agent_end') finalPosts.push({ ...pendingPost, final: true })",
    '  pendingPost = null',
    '  latestPost = null',
    '}',
    '',
    'function drainPosts(): void {',
    // Why: a final post waiting to retry holds newer posts back, so the old session's row is never written last.
    '  if (activePost || finalRetryTimer !== null) return',
    '  const next = finalPosts[0] ?? pendingPost',
    '  if (!next) return',
    '  if (!next.final) pendingPost = null',
    '  activePost = true',
    '  void postOnce(next.hookEventName, next.extra, next.metadata, next.ompRuntime, next.final === true)',
    '    .then(() => {',
    '      next.delivered = true',
    '      if (next.final) finalPosts.shift()',
    '    })',
    '    .catch(() => {',
    '      if (next.final) {',
    '        if (next.attempts >= 3) {',
    '          finalPosts.shift()',
    "          console.warn('[orca-pi-status] hook delivery failed after retries:', next.hookEventName)",
    '          return',
    '        }',
    '        finalRetryTimer = setTimeout(() => {',
    '          finalRetryTimer = null',
    '          drainPosts()',
    '        }, 250 * 2 ** next.attempts++)',
    "        if (typeof finalRetryTimer.unref === 'function') finalRetryTimer.unref()",
    '        return',
    '      }',
    '      if (!next.ompRuntime || next.revision !== postRevision) return',
    '      if (next.attempts >= 3) {',
    "        console.warn('[orca-pi-status] hook delivery failed after retries:', next.hookEventName)",
    '        return',
    '      }',
    '      const delay = 250 * 2 ** next.attempts++',
    '      retryTimer = setTimeout(() => {',
    '        retryTimer = null',
    '        if (next.revision !== postRevision) return',
    '        pendingPost = next',
    '        drainPosts()',
    '      }, delay)',
    "      if (typeof retryTimer.unref === 'function') retryTimer.unref()",
    '    })',
    '    .finally(() => {',
    '      activePost = false',
    '      drainPosts()',
    '    })',
    '}',
    ''
  ]
}
