import type { PiAgentKind } from '../../shared/pi-agent-kind'

export function getPiAgentStatusRuntimeDetectionSourceLines(kind: PiAgentKind): string[] {
  return [
    'function processName(value: unknown): string {',
    "  return String(value || '').split(/[\\\\/]/).pop()?.toLowerCase() || ''",
    '}',
    '',
    `const CONFIGURED_HOOK_PATH = '/hook/${kind}'`,
    'let cachedOmpRuntime: boolean | null = null',
    'let cachedSenpiRuntime: boolean | null = null',
    '',
    'function isOmpRuntime(): boolean {',
    '  if (cachedOmpRuntime !== null) return cachedOmpRuntime',
    "  if (CONFIGURED_HOOK_PATH === '/hook/omp') {",
    '    cachedOmpRuntime = true',
    '    return true',
    '  }',
    '  const executableNames = [',
    '    processName(process.title),',
    '    processName(process.env._),',
    '    processName(process.argv[1]),',
    '    processName(process.argv[0])',
    '  ]',
    '  cachedOmpRuntime = executableNames.some((name) =>',
    "    ['omp', 'omp.js', 'omp.sh', 'omp.cmd', 'omp.exe', 'omp.bat'].includes(name)",
    '  )',
    '  return cachedOmpRuntime',
    '}',
    '',
    'function isSenpiRuntime(): boolean {',
    '  if (cachedSenpiRuntime !== null) return cachedSenpiRuntime',
    "  if (CONFIGURED_HOOK_PATH === '/hook/senpi') {",
    '    cachedSenpiRuntime = true',
    '    return true',
    '  }',
    '  const executableNames = [',
    '    processName(process.title),',
    '    processName(process.env._),',
    '    processName(process.argv[1]),',
    '    processName(process.argv[0])',
    '  ]',
    '  cachedSenpiRuntime = executableNames.some((name) =>',
    "    ['senpi', 'senpi.js', 'senpi.cmd', 'senpi.exe', 'senpi.bat'].includes(name)",
    '  )',
    '  return cachedSenpiRuntime',
    '}',
    '',
    'function resolveHookPath(ompRuntime: boolean): string {',
    '  // Why: runtime detection keeps a bare-shell OMP/senpi launch from reporting as Pi.',
    "  if (ompRuntime) return '/hook/omp'",
    "  if (isSenpiRuntime()) return '/hook/senpi'",
    '  return CONFIGURED_HOOK_PATH',
    '}'
  ]
}
