export function getPiTitlebarBackgroundActivitySourceLines(): string[] {
  return [
    "  const backgroundActivitySlot = Symbol.for('orca.pi.titlebar-background-activity')",
    '  const backgroundActivity = globalThis[backgroundActivitySlot] ??= { activeSubagentIds: new Set(), leadAgentActive: false, completionTimer: null, sessionId: null, generation: 0 }',
    '  backgroundActivity.generation += 1',
    '  const extensionGeneration = backgroundActivity.generation',
    '  clearDeferredCompletion()',
    '',
    '  function resolveSessionId(ctx) {',
    '    try {',
    '      const manager = ctx?.sessionManager',
    '      const file = manager?.getSessionFile?.()',
    '      const id = manager?.getSessionId?.()',
    "      return typeof file === 'string' && file ? file : typeof id === 'string' && id ? id : null",
    '    } catch { return null }',
    '  }',
    '',
    '  function restoreBackgroundActivity(ctx, recovering) {',
    '    const sessionId = resolveSessionId(ctx)',
    '    if (!recovering || (sessionId !== null && backgroundActivity.sessionId !== null && sessionId !== backgroundActivity.sessionId)) {',
    '      backgroundActivity.activeSubagentIds.clear()',
    '      backgroundActivity.leadAgentActive = false',
    '      backgroundActivity.sessionId = null',
    '    }',
    '    clearDeferredCompletion()',
    '    if (sessionId !== null) backgroundActivity.sessionId = sessionId',
    '  }',
    '',
    '  function isEffectivelyWorking() {',
    '    return backgroundActivity.leadAgentActive || backgroundActivity.activeSubagentIds.size > 0',
    '  }',
    '',
    '  function clearDeferredCompletion() {',
    '    if (backgroundActivity.completionTimer !== null) clearTimeout(backgroundActivity.completionTimer)',
    '    backgroundActivity.completionTimer = null',
    '  }',
    '',
    '  function settleLeadAgent(ctx) {',
    '    lastContext = ctx || lastContext',
    '    backgroundActivity.leadAgentActive = false',
    '    if (!isEffectivelyWorking() && lastContext) stopAnimation(lastContext)',
    '  }',
    '',
    '  function scheduleDeferredCompletion() {',
    '    if (backgroundActivity.completionTimer !== null) return',
    '    backgroundActivity.completionTimer = setTimeout(() => {',
    '      backgroundActivity.completionTimer = null',
    '      if (backgroundActivity.generation !== extensionGeneration || isEffectivelyWorking() || !lastContext) return',
    '      stopAnimation(lastContext)',
    '    }, 0)',
    "    if (typeof backgroundActivity.completionTimer.unref === 'function') backgroundActivity.completionTimer.unref()",
    '  }',
    '',
    '  const processEvents = pi.events',
    '  const asyncStartedHandler = (payload) => {',
    '    if (backgroundActivity.generation !== extensionGeneration) return',
    '    const id = payload?.id',
    "    if (typeof id !== 'string' || !id || backgroundActivity.activeSubagentIds.has(id)) return",
    '    const wasWorking = isEffectivelyWorking()',
    '    backgroundActivity.activeSubagentIds.add(id)',
    '    clearDeferredCompletion()',
    '    if (!wasWorking && lastContext) startAnimation(lastContext)',
    '  }',
    '',
    '  const asyncCompleteHandler = (payload) => {',
    '    if (backgroundActivity.generation !== extensionGeneration) return',
    '    const runId = payload?.runId',
    "    if (typeof runId !== 'string' || !runId || !backgroundActivity.activeSubagentIds.delete(runId)) return",
    '    if (!isEffectivelyWorking()) scheduleDeferredCompletion()',
    '  }',
    '',
    '  const backgroundEventUnsubscribes = [',
    "    processEvents?.on?.('subagent:async-started', asyncStartedHandler),",
    "    processEvents?.on?.('subagent:async-complete', asyncCompleteHandler)",
    "].filter((unsubscribe) => typeof unsubscribe === 'function')",
    '',
    "  pi.on('session_shutdown', () => {",
    '    clearDeferredCompletion()',
    '    for (const unsubscribe of backgroundEventUnsubscribes.splice(0)) unsubscribe()',
    '  })',
    ''
  ]
}
