export const ORCA_PI_EXTENSION_FILE = 'orca-titlebar-spinner.ts'

export function getPiTitlebarExtensionSource(): string {
  return [
    "const BRAILLE_FRAMES = ['\\u280b', '\\u2819', '\\u2839', '\\u2838', '\\u283c', '\\u2834', '\\u2826', '\\u2827', '\\u2807', '\\u280f']",
    'const FRAME_INTERVAL_MS = 80',
    'const AGENT_END_IDLE_RECHECK_MS = 25',
    'const AGENT_END_IDLE_RECHECK_MAX_MS = 250',
    'const IDLE_COMPACTION_MAX_FRAMES = Math.ceil(300000 / FRAME_INTERVAL_MS)',
    '',
    'export default function (pi) {',
    '  if (!process.env.ORCA_PANE_KEY) return',
    '  let retired = false',
    '  let current = null',
    '',
    '  function clearPending(owner) {',
    '    if (owner.pending !== null) clearTimeout(owner.pending)',
    '    owner.pending = null',
    '    owner.check = null',
    '  }',
    '',
    '  function dispose(owner) {',
    '    if (!owner) return',
    '    if (current === owner) current = null',
    '    if (owner.timer !== null) clearInterval(owner.timer)',
    '    owner.timer = null',
    '    clearPending(owner)',
    '    owner.ctx = null',
    '  }',
    '',
    '  // A replacement gets a new factory/API; this registration can never become live again.',
    '  function retire() {',
    '    retired = true',
    '    dispose(current)',
    '    pi = null',
    '  }',
    '',
    '  function active(owner) {',
    '    return !retired && current === owner',
    '  }',
    '',
    "  function publish(owner, prefix = '') {",
    '    if (!active(owner)) return false',
    '    try {',
    '      const cwd = process.cwd().split(/[\\\\/]/).filter(Boolean).at(-1) || process.cwd()',
    '      const session = pi.getSessionName()',
    '      owner.ctx.ui.setTitle(prefix + (session ? `π - ${session} - ${cwd}` : `π - ${cwd}`))',
    '      return true',
    '    } catch {',
    '      // Invalidation can precede shutdown delivery; fail-stop this API registration.',
    '      retire()',
    '      return false',
    '    }',
    '  }',
    '',
    '  function stop(owner) {',
    '    if (!active(owner)) return',
    '    publish(owner)',
    '    dispose(owner)',
    '  }',
    '',
    '  function render(owner) {',
    '    if (!active(owner)) return',
    '    if (owner.maintenance && owner.frame >= IDLE_COMPACTION_MAX_FRAMES) {',
    '      stop(owner)',
    '      return',
    '    }',
    "    if (publish(owner, BRAILLE_FRAMES[owner.frame % BRAILLE_FRAMES.length] + ' ')) owner.frame++",
    '  }',
    '',
    '  function start(ctx, maintenance = false) {',
    '    if (retired) return',
    '    dispose(current)',
    '    const owner = { ctx, maintenance, frame: 0, timer: null, pending: null, check: null }',
    '    current = owner',
    '    render(owner)',
    '    if (active(owner)) owner.timer = setInterval(() => render(owner), FRAME_INTERVAL_MS)',
    '  }',
    '',
    '  function settle(ctx) {',
    '    if (retired) return',
    '    if (!current) current = { ctx, timer: null, pending: null, check: null }',
    '    stop(current)',
    '  }',
    '',
    '  function scheduleCheck(owner, ctx) {',
    '    clearPending(owner)',
    '    const check = { delay: AGENT_END_IDLE_RECHECK_MS }',
    '    owner.check = check',
    '    function poll() {',
    '      if (!active(owner) || owner.check !== check) return',
    '      owner.pending = null',
    '      try {',
    '        if (ctx.isIdle()) {',
    '          stop(owner)',
    '          return',
    '        }',
    '      } catch {',
    '        retire()',
    '        return',
    '      }',
    '      owner.pending = setTimeout(poll, check.delay)',
    '      owner.pending.unref?.()',
    '      check.delay = Math.min(check.delay * 2, AGENT_END_IDLE_RECHECK_MAX_MS)',
    '    }',
    '    owner.pending = setTimeout(poll, 0)',
    '    owner.pending.unref?.()',
    '  }',
    '',
    "  pi.on('session_start', async (_event, ctx) => { dispose(current); settle(ctx) })",
    "  pi.on('agent_start', async (_event, ctx) => { start(ctx) })",
    "  pi.on('agent_settled', async (_event, ctx) => { settle(ctx) })",
    "  pi.on('agent_end', async (event, ctx) => {",
    '    if (retired) return',
    '    if (event?.willContinue === true) {',
    '      if (current) clearPending(current)',
    '      return',
    '    }',
    "    if (!ctx || typeof ctx.isIdle !== 'function') {",
    '      settle(ctx)',
    '      return',
    '    }',
    '    if (!current) current = { ctx, timer: null, pending: null, check: null }',
    '    scheduleCheck(current, ctx)',
    '  })',
    "  pi.on('auto_compaction_start', async (event, ctx) => {",
    "    if (event?.reason !== 'idle' || (current && current.timer !== null && !current.maintenance)) return",
    '    start(ctx, true)',
    '  })',
    "  pi.on('auto_compaction_end', async () => {",
    '    if (current?.maintenance) stop(current)',
    '  })',
    "  pi.on('session_shutdown', async () => { retire() })",
    '}',
    ''
  ].join('\n')
}
