export const ORCA_PI_EXTENSION_FILE = 'orca-titlebar-spinner.ts'

export function getPiTitlebarExtensionSource(): string {
  return [
    'const BRAILLE_FRAMES = [',
    "  '\\u280b',",
    "  '\\u2819',",
    "  '\\u2839',",
    "  '\\u2838',",
    "  '\\u283c',",
    "  '\\u2834',",
    "  '\\u2826',",
    "  '\\u2827',",
    "  '\\u2807',",
    "  '\\u280f'",
    ']',
    '',
    'const FRAME_INTERVAL_MS = 80',
    'const AGENT_END_IDLE_RECHECK_MS = 25',
    'const AGENT_END_IDLE_RECHECK_MAX_MS = 250',
    '// Why: a failed idle compaction can end without auto_compaction_end, and no agent turn will',
    '// close a maintenance spinner — cap it so idle maintenance cannot strand a working title.',
    'const IDLE_COMPACTION_MAX_FRAMES = Math.ceil(300000 / FRAME_INTERVAL_MS)',
    '',
    'function getBaseTitle(pi) {',
    '  const cwd = process.cwd().split(/[\\\\/]/).filter(Boolean).at(-1) || process.cwd()',
    '  const session = pi.getSessionName()',
    '  return session ? `\\u03c0 - ${session} - ${cwd}` : `\\u03c0 - ${cwd}`',
    '}',
    '',
    'export default function (pi) {',
    '  if (!process.env.ORCA_PANE_KEY) return',
    "  const backgroundActivitySlot = Symbol.for('orca.pi.titlebar-background-activity')",
    '  const backgroundActivityGlobal = globalThis',
    '  const backgroundActivity = backgroundActivityGlobal[backgroundActivitySlot] || {',
    '    activeSubagentIds: new Set(),',
    '    leadAgentActive: false,',
    '    completionTimer: null,',
    '    generation: 0',
    '  }',
    '  backgroundActivityGlobal[backgroundActivitySlot] = backgroundActivity',
    '  backgroundActivity.generation++',
    '  const extensionGeneration = backgroundActivity.generation',
    '  if (backgroundActivity.completionTimer !== null) {',
    '    clearTimeout(backgroundActivity.completionTimer)',
    '    backgroundActivity.completionTimer = null',
    '  }',
    '  let timer = null',
    '  let frameIndex = 0',
    '  // Why: only idle maintenance owns a spinner of its own. A threshold compaction runs',
    '  // inside an agent turn, whose spinner must outlive it, and any newer start clears the',
    '  // marker so a late idle completion cannot stop current work (#16470).',
    '  let idleCompactionOwnsSpinner = false',
    '  let pendingAgentEndCheck = null',
    '  let pendingAgentEndContext = null',
    '  let agentEndIdleRecheckMs = AGENT_END_IDLE_RECHECK_MS',
    '  let lastContext = null',
    '',
    '  function isEffectivelyWorking() {',
    '    return backgroundActivity.leadAgentActive || backgroundActivity.activeSubagentIds.size > 0',
    '  }',
    '',
    '  function clearDeferredCompletion() {',
    '    if (backgroundActivity.completionTimer !== null) clearTimeout(backgroundActivity.completionTimer)',
    '    backgroundActivity.completionTimer = null',
    '  }',
    '',
    '  function clearPendingAgentEndCheck() {',
    '    if (pendingAgentEndCheck !== null) clearTimeout(pendingAgentEndCheck)',
    '    pendingAgentEndCheck = null',
    '    pendingAgentEndContext = null',
    '  }',
    '',
    '  function clearAnimation() {',
    '    if (timer) {',
    '      clearInterval(timer)',
    '      timer = null',
    '    }',
    '    frameIndex = 0',
    '    idleCompactionOwnsSpinner = false',
    '  }',
    '',
    '  function stopAnimation(ctx) {',
    '    clearPendingAgentEndCheck()',
    '    clearAnimation()',
    '    ctx.ui.setTitle(getBaseTitle(pi))',
    '  }',
    '',
    '  function renderFrame(ctx) {',
    '    if (backgroundActivity.generation !== extensionGeneration) {',
    '      clearAnimation()',
    '      return',
    '    }',
    '    if (idleCompactionOwnsSpinner && frameIndex >= IDLE_COMPACTION_MAX_FRAMES) {',
    '      stopAnimation(ctx)',
    '      return',
    '    }',
    '      const frame = BRAILLE_FRAMES[frameIndex % BRAILLE_FRAMES.length]',
    '      const cwd = process.cwd().split(/[\\\\/]/).filter(Boolean).at(-1) || process.cwd()',
    '      const session = pi.getSessionName()',
    '      const title = session ? `${frame} \\u03c0 - ${session} - ${cwd}` : `${frame} \\u03c0 - ${cwd}`',
    '      ctx.ui.setTitle(title)',
    '      frameIndex++',
    '  }',
    '',
    '  function startAnimation(ctx) {',
    '    lastContext = ctx',
    '    clearPendingAgentEndCheck()',
    '    clearAnimation()',
    '    renderFrame(ctx)',
    '    timer = setInterval(() => renderFrame(ctx), FRAME_INTERVAL_MS)',
    '  }',
    '',
    '  function settleLeadAgent(ctx) {',
    '    lastContext = ctx || lastContext',
    '    backgroundActivity.leadAgentActive = false',
    '    if (!isEffectivelyWorking() && lastContext) stopAnimation(lastContext)',
    '  }',
    '',
    '  function scheduleDeferredCompletion() {',
    '    if (backgroundActivity.completionTimer !== null) return',
    '    backgroundActivity.completionTimer = setTimeout(() => {',
    '      backgroundActivity.completionTimer = null',
    '      if (backgroundActivity.generation !== extensionGeneration || isEffectivelyWorking() || !lastContext) return',
    '      stopAnimation(lastContext)',
    '    }, 0)',
    "    if (typeof backgroundActivity.completionTimer.unref === 'function') backgroundActivity.completionTimer.unref()",
    '  }',
    '',
    '  function checkPendingAgentEnd() {',
    '    pendingAgentEndCheck = null',
    '    if (backgroundActivity.generation !== extensionGeneration) {',
    '      pendingAgentEndContext = null',
    '      return',
    '    }',
    '    const ctx = pendingAgentEndContext',
    '    if (!ctx) return',
    '    try {',
    '      if (ctx.isIdle()) {',
    '        pendingAgentEndContext = null',
    '        settleLeadAgent(ctx)',
    '        return',
    '      }',
    '    } catch {',
    '      pendingAgentEndContext = null',
    '      return',
    '    }',
    '    pendingAgentEndCheck = setTimeout(checkPendingAgentEnd, agentEndIdleRecheckMs)',
    "    if (typeof pendingAgentEndCheck.unref === 'function') pendingAgentEndCheck.unref()",
    '    agentEndIdleRecheckMs = Math.min(agentEndIdleRecheckMs * 2, AGENT_END_IDLE_RECHECK_MAX_MS)',
    '  }',
    '',
    "  pi.on('session_start', async (event, ctx) => {",
    '    lastContext = ctx',
    "    if (event?.reason !== 'reload') {",
    '      clearDeferredCompletion()',
    '      backgroundActivity.activeSubagentIds.clear()',
    '      backgroundActivity.leadAgentActive = false',
    '      return',
    '    }',
    '    if (isEffectivelyWorking()) startAnimation(ctx)',
    '  })',
    '',
    "  pi.on('before_agent_start', async (_event, ctx) => {",
    '    lastContext = ctx',
    '    clearDeferredCompletion()',
    '    backgroundActivity.leadAgentActive = true',
    '  })',
    '',
    "  pi.on('agent_start', async (_event, ctx) => {",
    '    clearDeferredCompletion()',
    '    backgroundActivity.leadAgentActive = true',
    '    startAnimation(ctx)',
    '  })',
    '',
    '  // Why: modern Pi/OMP emit agent_end mid-run and only settle later, so settlement is the',
    '  // authoritative completion boundary. Legacy runtimes never emit it, so agent_end stays.',
    "  pi.on('agent_settled', async (_event, ctx) => {",
    '    settleLeadAgent(ctx)',
    '  })',
    '',
    "  pi.on('agent_end', async (event, ctx) => {",
    '    if (event?.willContinue === true) {',
    '      clearPendingAgentEndCheck()',
    '      return',
    '    }',
    "    if (!ctx || typeof ctx.isIdle !== 'function') {",
    '      settleLeadAgent(ctx)',
    '      return',
    '    }',
    '    clearPendingAgentEndCheck()',
    '    agentEndIdleRecheckMs = AGENT_END_IDLE_RECHECK_MS',
    '    pendingAgentEndContext = ctx',
    '    pendingAgentEndCheck = setTimeout(checkPendingAgentEnd, 0)',
    "    if (typeof pendingAgentEndCheck.unref === 'function') pendingAgentEndCheck.unref()",
    '  })',
    '',
    "  pi.on('auto_compaction_start', async (event, ctx) => {",
    "    if (event?.reason !== 'idle') return",
    '    // Why: the idle worker can fire against a turn that just started, and reason alone does',
    '    // not prove the pane is idle. Adopting a live agent spinner would let the matching',
    '    // auto_compaction_end mark the pane idle mid-run — the inverse of #16470.',
    '    if (timer && !idleCompactionOwnsSpinner) return',
    '    startAnimation(ctx)',
    '    idleCompactionOwnsSpinner = true',
    '  })',
    '',
    "  pi.on('auto_compaction_end', async (_event, ctx) => {",
    '    if (!idleCompactionOwnsSpinner || isEffectivelyWorking()) return',
    '    stopAnimation(ctx)',
    '  })',
    '',
    "  pi.on('session_shutdown', async (_event, ctx) => {",
    '    stopAnimation(ctx)',
    '  })',
    '',
    '  const processEvents = pi.events',
    "  processEvents?.on?.('subagent:async-started', (payload) => {",
    '    if (backgroundActivity.generation !== extensionGeneration) return',
    '    const id = payload?.id',
    "    if (typeof id !== 'string' || !id || backgroundActivity.activeSubagentIds.has(id)) return",
    '    const wasWorking = isEffectivelyWorking()',
    '    backgroundActivity.activeSubagentIds.add(id)',
    '    clearDeferredCompletion()',
    '    if (!wasWorking && lastContext) startAnimation(lastContext)',
    '  })',
    '',
    "  processEvents?.on?.('subagent:async-complete', (payload) => {",
    '    if (backgroundActivity.generation !== extensionGeneration) return',
    '    const runId = payload?.runId',
    "    if (typeof runId !== 'string' || !runId || !backgroundActivity.activeSubagentIds.delete(runId)) return",
    '    if (!isEffectivelyWorking()) scheduleDeferredCompletion()',
    '  })',
    '}',
    ''
  ].join('\n')
}
