export const ORCA_PI_EXTENSION_FILE = 'orca-titlebar-spinner.ts'

export function getPiTitlebarExtensionSource(): string {
  return [
    'const BRAILLE_FRAMES = [',
    "  '\\u280b',",
    "  '\\u2819',",
    "  '\\u2839',",
    "  '\\u2838',",
    "  '\\u283c',",
    "  '\\u2834',",
    "  '\\u2826',",
    "  '\\u2827',",
    "  '\\u2807',",
    "  '\\u280f'",
    ']',
    '',
    'const FRAME_INTERVAL_MS = 80',
    '',
    'function getCwdLabel() {',
    '  return process.cwd().split(/[\\\\/]/).filter(Boolean).at(-1) || process.cwd()',
    '}',
    '',
    'function formatTitle(frame, session, cwd) {',
    '  const prefix = frame ? `${frame} \\u03c0` : `\\u03c0`',
    '  return session ? `${prefix} - ${session} - ${cwd}` : `${prefix} - ${cwd}`',
    '}',
    '',
    'export default function (pi) {',
    '  if (!process.env.ORCA_PANE_KEY) return',
    '  let timer = null',
    '  let frameIndex = 0',
    '  let sessionLabel = null',
    '  let cwdLabel = getCwdLabel()',
    '  let handleStale = false',
    '',
    '  // Why: the captured pi handle is invalidated by newSession/fork/switchSession/',
    '  // reload. Read the name once per turn instead of on every frame, and latch the',
    '  // failure so a dead handle is not re-probed 12x a second. The last good label',
    '  // is kept so the title degrades to a stale name rather than losing it.',
    '  function refreshSessionLabel() {',
    '    if (handleStale) return',
    '    try {',
    '      sessionLabel = pi.getSessionName()',
    '    } catch {',
    '      handleStale = true',
    '    }',
    '  }',
    '',
    '  // Why: setTitle throws on a replaced ctx too. Report the failure instead of',
    '  // propagating so each caller can decide whether to unbind.',
    '  function writeTitle(ctx, title) {',
    '    try {',
    '      ctx.ui.setTitle(title)',
    '      return true',
    '    } catch {',
    '      return false',
    '    }',
    '  }',
    '',
    '  function clearTimer() {',
    '    if (timer) {',
    '      clearInterval(timer)',
    '      timer = null',
    '    }',
    '    frameIndex = 0',
    '  }',
    '',
    '  function stopAnimation(ctx) {',
    '    clearTimer()',
    '    refreshSessionLabel()',
    "    writeTitle(ctx, formatTitle('', sessionLabel, cwdLabel))",
    '  }',
    '',
    '  function startAnimation(ctx) {',
    '    clearTimer()',
    '    cwdLabel = getCwdLabel()',
    '    refreshSessionLabel()',
    '    timer = setInterval(() => {',
    '      const frame = BRAILLE_FRAMES[frameIndex % BRAILLE_FRAMES.length]',
    '      // Why: a timer callback is a top-level frame with no caller to catch it,',
    '      // so any throw here is an uncaughtException that takes the agent process',
    '      // down. Unbind on the first failed write instead of escalating.',
    '      if (!writeTitle(ctx, formatTitle(frame, sessionLabel, cwdLabel))) {',
    '        clearTimer()',
    '        return',
    '      }',
    '      frameIndex++',
    '    }, FRAME_INTERVAL_MS)',
    '    // Why: a cosmetic title animation must never hold the event loop open and',
    '    // keep ticking against a session that is already shutting down.',
    "    if (typeof timer.unref === 'function') timer.unref()",
    '  }',
    '',
    "  pi.on('agent_start', async (_event, ctx) => {",
    '    startAnimation(ctx)',
    '  })',
    '',
    "  pi.on('agent_end', async (_event, ctx) => {",
    '    stopAnimation(ctx)',
    '  })',
    '',
    "  pi.on('session_shutdown', async (_event, ctx) => {",
    '    stopAnimation(ctx)',
    '  })',
    '',
    '  // Why: session_start is the runtime signal for new/fork/switch/resume/reload —',
    '  // exactly the replacements that invalidate the ctx an in-flight animation is',
    '  // bound to. Unbind here so no frame ever runs against a replaced session, and',
    '  // re-probe the handle in case the replacement revived it. The next agent_start',
    '  // re-arms the spinner with the incoming ctx.',
    "  pi.on('session_start', async (_event, ctx) => {",
    '    clearTimer()',
    '    handleStale = false',
    '    cwdLabel = getCwdLabel()',
    '    refreshSessionLabel()',
    "    writeTitle(ctx, formatTitle('', sessionLabel, cwdLabel))",
    '  })',
    '}',
    ''
  ].join('\n')
}
