import { NATIVE_HOST_DIFF_REVIEW_DEVICE_OPERATIONS } from './native-host-diff-review-device-operations'

export const DEFAULT_HOST_DIFF_REVIEW_DEVICE_OPERATIONS = NATIVE_HOST_DIFF_REVIEW_DEVICE_OPERATIONS
