import type { MobileSessionTerminalListModel } from './use-mobile-session-terminal-list'

export type MobileSessionTabApplicationScope = Pick<
  MobileSessionTerminalListModel,
  | 'setTerminals'
  | 'terminalsRef'
  | 'setSessionTabs'
  | 'sessionTabsRef'
  | 'appliedSnapshotMarkerRef'
  | 'appliedSessionTabsRevisionRef'
  | 'closedTabTombstonesRef'
  | 'reconcileBufferedDraftsRef'
  | 'setTerminalsLoaded'
  | 'defaultTerminalHandlesToLiveInput'
  | 'setActiveHandle'
  | 'setActiveSessionTabId'
  | 'activeSessionTabIdRef'
  | 'selectedSessionTabIdRef'
  | 'markdownDocsRef'
  | 'initializedHandlesRef'
  | 'terminalDiagnosticsRef'
  | 'activeHandleRef'
  | 'activeSessionTabTypeRef'
  | 'pendingSelectionRef'
  | 'pendingBrowserFocusPageIdRef'
  | 'initialSessionAutoCreateRef'
  | 'unsubscribeTerminal'
  | 'subscribeToTerminal'
  | 'lastKnownTerminalCountRef'
  | 'clientRef'
  | 'creatingTerminalRef'
  | 'setCreating'
>
