export const WEBSOCKET_TRANSPORT_MAX_MESSAGE_BYTES = 1024 * 1024
export const WEBSOCKET_TRANSPORT_MAX_CONNECTIONS = 128
export const WEBSOCKET_TRANSPORT_MAX_TCP_CONNECTIONS = WEBSOCKET_TRANSPORT_MAX_CONNECTIONS * 2
export const WEBSOCKET_TRANSPORT_MAX_BACKPRESSURE_BYTES = 32 * 1024 * 1024
