import React from 'react';
import RepoCombobox from '@/components/repo/RepoCombobox';
import type { GitHubWorkItem, TuiAgent } from '../../../shared/types';
type RepoOption = React.ComponentProps<typeof RepoCombobox>['repos'][number];
type LinkedWorkItemSummary = {
    type: 'issue' | 'pr';
    number: number;
    title: string;
    url: string;
} | null;
type NewWorkspaceComposerCardProps = {
    containerClassName?: string;
    composerRef?: React.RefObject<HTMLDivElement | null>;
    nameInputRef?: React.RefObject<HTMLInputElement | null>;
    promptTextareaRef?: React.RefObject<HTMLTextAreaElement | null>;
    eligibleRepos: RepoOption[];
    repoId: string;
    onRepoChange: (value: string) => void;
    name: string;
    onNameChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    agentPrompt: string;
    onAgentPromptChange: (value: string) => void;
    onPromptKeyDown: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void;
    linkedOnlyTemplatePreview: string | null;
    attachmentPaths: string[];
    getAttachmentLabel: (pathValue: string) => string;
    onAddAttachment: () => void;
    onRemoveAttachment: (pathValue: string) => void;
    addAttachmentShortcut: string;
    linkedWorkItem: LinkedWorkItemSummary;
    onRemoveLinkedWorkItem: () => void;
    linkPopoverOpen: boolean;
    onLinkPopoverOpenChange: (open: boolean) => void;
    linkQuery: string;
    onLinkQueryChange: (value: string) => void;
    filteredLinkItems: GitHubWorkItem[];
    linkItemsLoading: boolean;
    linkDirectLoading: boolean;
    normalizedLinkQuery: {
        query: string;
        repoMismatch: string | null;
    };
    onSelectLinkedItem: (item: GitHubWorkItem) => void;
    tuiAgent: TuiAgent;
    onTuiAgentChange: (value: TuiAgent) => void;
    detectedAgentIds: Set<TuiAgent> | null;
    onOpenAgentSettings: () => void;
    advancedOpen: boolean;
    onToggleAdvanced: () => void;
    createDisabled: boolean;
    creating: boolean;
    onCreate: () => void;
    note: string;
    onNoteChange: (value: string) => void;
    setupConfig: {
        source: 'yaml' | 'legacy';
        command: string;
    } | null;
    requiresExplicitSetupChoice: boolean;
    setupDecision: 'run' | 'skip' | null;
    onSetupDecisionChange: (value: 'run' | 'skip') => void;
    shouldWaitForSetupCheck: boolean;
    resolvedSetupDecision: 'run' | 'skip' | null;
    createError: string | null;
};
export default function NewWorkspaceComposerCard({ containerClassName, composerRef, nameInputRef, promptTextareaRef, eligibleRepos, repoId, onRepoChange, name, onNameChange, agentPrompt, onAgentPromptChange, onPromptKeyDown, linkedOnlyTemplatePreview, attachmentPaths, getAttachmentLabel, onAddAttachment, onRemoveAttachment, addAttachmentShortcut, linkedWorkItem, onRemoveLinkedWorkItem, linkPopoverOpen, onLinkPopoverOpenChange, linkQuery, onLinkQueryChange, filteredLinkItems, linkItemsLoading, linkDirectLoading, normalizedLinkQuery, onSelectLinkedItem, tuiAgent, onTuiAgentChange, detectedAgentIds, onOpenAgentSettings, advancedOpen, onToggleAdvanced, createDisabled, creating, onCreate, note, onNoteChange, setupConfig, requiresExplicitSetupChoice, setupDecision, onSetupDecisionChange, shouldWaitForSetupCheck, resolvedSetupDecision, createError }: NewWorkspaceComposerCardProps): React.JSX.Element;
export {};
