import type { CodexRateLimitAccountsState } from '../../shared/types';
import type { Store } from '../persistence';
import type { RateLimitService } from '../rate-limits/service';
export declare class CodexAccountService {
    private readonly store;
    private readonly rateLimits;
    constructor(store: Store, rateLimits: RateLimitService);
    listAccounts(): CodexRateLimitAccountsState;
    addAccount(): Promise<CodexRateLimitAccountsState>;
    reauthenticateAccount(accountId: string): Promise<CodexRateLimitAccountsState>;
    removeAccount(accountId: string): Promise<CodexRateLimitAccountsState>;
    selectAccount(accountId: string | null): Promise<CodexRateLimitAccountsState>;
    getSelectedManagedHomePath(): string | null;
    private getSnapshot;
    private getActiveAccount;
    private toSummary;
    private requireAccount;
    private normalizeActiveSelection;
    private createManagedHome;
    private getManagedAccountsRoot;
    private assertManagedHomePath;
    private safeRemoveManagedHome;
    private runCodexLogin;
    private readIdentityFromHome;
    private loadOAuthCredentials;
    private parseJwtPayload;
    private readRecordClaim;
    private readStringClaim;
    private normalizeField;
}
