export const AGENT_DASHBOARD_INSPECTOR_DEFAULT_WIDTH = 42 * 16
export const AGENT_DASHBOARD_INSPECTOR_MIN_WIDTH = 320
export const AGENT_DASHBOARD_INSPECTOR_VIEWPORT_GAP = 3 * 16
export const AGENT_DASHBOARD_INSPECTOR_RESIZE_STEP = 24
