plugins { id 'com.android.application' }
android {
    namespace 'dev.orca.outsider'
    compileSdk 36
    defaultConfig {
        applicationId 'dev.orca.outsider'
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName '1'
    }
    buildTypes { release { debuggable false; signingConfig signingConfigs.debug } }
}
