import type { BrowserWindow } from 'electron';
import type { RateLimitState } from '../../shared/rate-limit-types';
export declare class RateLimitService {
    private state;
    private pollInterval;
    private timer;
    private lastFetchAt;
    private mainWindow;
    private detachWindowListeners;
    private isFetching;
    private fullFetchQueued;
    private codexOnlyFetchQueued;
    private fetchIdleResolvers;
    private codexFetchGeneration;
    private codexHomePathResolver;
    constructor();
    setCodexHomePathResolver(resolver: () => string | null): void;
    attach(mainWindow: BrowserWindow): void;
    start(): void;
    stop(): void;
    getState(): RateLimitState;
    refresh(): Promise<RateLimitState>;
    refreshForCodexAccountChange(): Promise<RateLimitState>;
    setPollingInterval(ms: number): void;
    private startTimer;
    private stopTimer;
    private shouldBackgroundPoll;
    private refreshIfWindowActive;
    private fetchAll;
    private fetchCodexOnly;
    private waitForFetchIdle;
    private resolveFetchIdleWaiters;
    private withFetchingStatus;
    private runFetchAllCycle;
    private runFetchCodexOnlyCycle;
    private applyStalePolicy;
    private updateState;
    private pushToRenderer;
}
