import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, Globe, Search } from 'lucide-react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
export function SettingsSidebar({ activeSectionId, generalSections, repoSections, hasRepos, searchQuery, onBack, onSearchChange, onSelectSection }) {
    return (_jsxs("aside", { className: "flex w-[280px] shrink-0 flex-col border-r border-border/50 bg-card/40", children: [_jsx("div", { className: "border-b border-border/50 px-3 py-3", children: _jsxs(Button, { variant: "ghost", size: "sm", onClick: onBack, className: "w-full justify-start gap-2 text-muted-foreground", children: [_jsx(ArrowLeft, { className: "size-4" }), "Back to app"] }) }), _jsx("div", { className: "border-b border-border/50 px-3 py-3", children: _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" }), _jsx(Input, { value: searchQuery, onChange: (event) => onSearchChange(event.target.value), placeholder: "Search settings", className: "pl-9" })] }) }), _jsx("div", { className: "min-h-0 flex-1 overflow-y-auto scrollbar-sleek px-3 py-4", children: _jsxs("div", { className: "space-y-5", children: [_jsx("div", { className: "space-y-1", children: generalSections.map((section) => {
                                const Icon = section.icon;
                                const isActive = activeSectionId === section.id;
                                return (_jsxs("button", { onClick: () => onSelectSection(section.id), className: `flex w-full items-center rounded-lg px-3 py-2 text-left text-sm transition-colors ${isActive
                                        ? 'bg-accent font-medium text-accent-foreground'
                                        : 'text-muted-foreground hover:bg-muted/60 hover:text-foreground'}`, children: [_jsx(Icon, { className: "mr-2 size-4" }), section.title, section.badge ? (_jsx("span", { className: "ml-auto rounded-full bg-muted px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wider text-muted-foreground", children: section.badge })) : null] }, section.id));
                            }) }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "px-3 text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground", children: "Repositories" }), repoSections.length > 0 ? (_jsx("div", { className: "space-y-1", children: repoSections.map((section) => {
                                        const isActive = activeSectionId === section.id;
                                        return (_jsxs("button", { onClick: () => onSelectSection(section.id), className: `flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm transition-colors ${isActive
                                                ? 'bg-accent font-medium text-accent-foreground'
                                                : 'text-muted-foreground hover:bg-muted/60 hover:text-foreground'}`, children: [_jsx("span", { className: "size-2.5 shrink-0 rounded-full", style: { backgroundColor: section.badgeColor ?? '#6b7280' } }), _jsx("span", { className: "truncate", children: section.title }), section.isRemote && (_jsxs("span", { className: "ml-auto inline-flex shrink-0 items-center gap-1 text-[10px] text-muted-foreground", children: [_jsx(Globe, { className: "size-3" }), "SSH"] }))] }, section.id));
                                    }) })) : (_jsx("p", { className: "px-3 text-xs text-muted-foreground", children: hasRepos ? 'No matching repository settings.' : 'No repositories added yet.' }))] })] }) })] }));
}
