import type { GlobalSettings } from '../../../../shared/types'

export const SETTING_LABELS: Partial<Record<keyof GlobalSettings, string>> = {
  nestWorkspaces: 'Nest Workspaces',
  refreshLocalBaseRefOnWorktreeCreate: 'Refresh Base Branch on Workspace Create',
  localBaseRefSuggestionDismissed: 'Base Branch Suggestion',
  autoRenameBranchFromWork: 'Auto-rename Branches',
  autoRenameBranchFromWorkDefaultedOn: 'Auto-rename Branches Default',
  branchPrefix: 'Branch Prefix',
  branchPrefixCustom: 'Custom Branch Prefix',
  enableGitHubAttribution: 'GitHub Attribution',
  theme: 'Theme',
  uiLanguage: 'Language',
  appIcon: 'App Icon',
  appFontFamily: 'App Font',
  editorAutoSave: 'Auto Save Files',
  editorAutoSaveDelayMs: 'Auto Save Delay',
  editorMinimapEnabled: 'Minimap',
  markdownReviewToolsEnabled: 'Markdown Review Notes',
  primarySelectionMiddleClickPaste: 'Middle-click Paste from Selection',
  primarySelectionMiddleClickPasteDefaultedForLinux: 'Middle-click Paste Default',
  primarySelectionMiddleClickPasteDefaultedForTerminalDefaults: 'Terminal Selection Paste Default',
  terminalFontSize: 'Font Size',
  terminalFontFamily: 'Font Family',
  terminalFontWeight: 'Font Weight',
  terminalLineHeight: 'Line Height',
  terminalGpuAcceleration: 'GPU Acceleration',
  terminalLigatures: 'Ligatures',
  terminalBackgroundOpacity: 'Background Opacity',
  terminalCursorStyle: 'Cursor Style',
  terminalCursorBlink: 'Cursor Blink',
  terminalThemeDark: 'Dark Terminal Theme',
  terminalThemeLight: 'Light Terminal Theme',
  terminalUseSeparateLightTheme: 'Separate Light Terminal Theme',
  terminalCustomThemes: 'Custom Terminal Themes',
  terminalCursorOpacity: 'Cursor Opacity',
  terminalMouseHideWhileTyping: 'Mouse Hide While Typing',
  terminalWordSeparator: 'Word Separator',
  terminalFocusFollowsMouse: 'Focus Follows Mouse',
  terminalColorOverrides: 'Color Overrides',
  terminalQuickCommands: 'Terminal Quick Commands',
  terminalMacOptionAsAlt: 'Option as Alt',
  terminalMacOptionAsAltMigrated: 'Option as Alt Migration',
  terminalJISYenToBackslash: 'JIS Yen Key as Backslash',
  terminalPaddingX: 'Padding X',
  terminalPaddingY: 'Padding Y',
  terminalDividerColorDark: 'Divider Color (Dark)',
  terminalDividerColorLight: 'Divider Color (Light)',
  terminalActivePaneOpacity: 'Active Pane Opacity',
  terminalInactivePaneOpacity: 'Inactive Pane Opacity',
  terminalPaneOpacityTransitionMs: 'Pane Opacity Transition',
  terminalDividerThicknessPx: 'Divider Thickness',
  terminalRightClickToPaste: 'Right-click to Paste',
  terminalClipboardOnSelect: 'Copy on Select',
  terminalAllowOsc52Clipboard: 'OSC 52 Clipboard',
  terminalScrollbackBytes: 'Terminal Scrollback',
  terminalShortcutPolicy: 'Terminal Shortcut Priority',
  terminalScopeHistoryByWorktree: 'Remember Terminal Scope by Workspace',
  windowBackgroundBlur: 'Window Background Blur',
  claudeAgentTeamsMode: 'Claude Agent Teams Mode',
  setupScriptLaunchMode: 'Setup Script Launch Mode',
  electronHttp1CompatibilityMode: 'HTTP/1.1 Compatibility',
  openLinksInApp: 'Open Links in Orca',
  rightSidebarOpenByDefault: 'Right Sidebar Default',
  showGitIgnoredFiles: 'Show Git-Ignored Files',
  sourceControlViewMode: 'Source Control View',
  showTitlebarAppName: 'Titlebar App Name',
  showTasksButton: 'Tasks Sidebar Button',
  showAutomationsButton: 'Automations Sidebar Button',
  showMobileButton: 'Mobile Sidebar Button',
  ctrlTabOrderMode: 'Tab Switcher Order',
  floatingTerminalEnabled: 'Floating Workspace',
  floatingTerminalDefaultedForAllUsers: 'Floating Workspace Default',
  floatingTerminalTriggerLocation: 'Floating Workspace Trigger',
  notifications: 'Notifications',
  diffDefaultView: 'Default Diff View',
  combinedDiffFileTreeVisibleByDefault: 'Default Diff File Tree',
  promptCacheTimerEnabled: 'Prompt Cache Timer',
  promptCacheTtlMs: 'Prompt Cache Duration',
  defaultTuiAgent: 'Default Agent',
  disabledTuiAgents: 'Disabled Agents',
  claudeAgentTeamsDefaultDisabledMigrated: 'Claude Agent Teams Default',
  skipDeleteWorktreeConfirm: 'Delete Workspace Confirmation',
  skipDeleteAutomationConfirm: 'Delete Automation Confirmation',
  defaultTaskViewPreset: 'Default Task View',
  defaultTaskSource: 'Default Task Source',
  visibleTaskProviders: 'Visible Task Providers',
  visibleTaskProvidersDefaultedForJira: 'Visible Task Providers Default',
  geminiCliOAuthEnabled: 'Gemini CLI OAuth',
  agentCmdOverrides: 'Agent Commands',
  agentStatusHooksEnabled: 'Agent Status Hooks',
  tabAutoGenerateTitle: 'Auto-generate Tab Titles',
  keepComputerAwakeWhileAgentsRun: 'Keep Computer Awake',
  experimentalMobile: 'Experimental Mobile',
  mobileEmulatorEnabled: 'Mobile Emulator',
  mobileAutoRestoreFitMs: 'Mobile Auto-restore Fit',
  experimentalPet: 'Pet Overlay',
  experimentalActivity: 'Activity View',
  experimentalActivityDefaultedOffForAllUsers: 'Activity View Default',
  experimentalTerminalAttention: 'Terminal Attention',
  compactWorktreeCards: 'Compact Workspace Cards',
  experimentalWorktreeSymlinks: 'Workspace Symlinks',
  commitMessageAi: 'Commit Message AI',
  sourceControlAi: 'Source Control AI',
  voice: 'Voice Dictation'
}
