import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ColorField, ThemePicker } from './SettingsFormControls';
import { SearchableSetting } from './SearchableSetting';
import { TerminalThemePreview } from './TerminalThemePreview';
export function DarkTerminalThemeSection({ settings, systemPrefersDark, themeSearchDark, setThemeSearchDark, updateSettings, previewProps, darkPreviewAppearance }) {
    return (_jsxs("section", { className: "grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]", children: [_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("h3", { className: "text-sm font-semibold", children: "Dark Theme" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Choose the theme used for terminal panes in dark mode." })] }), _jsx(SearchableSetting, { title: "Dark Theme", description: "Choose the terminal theme used in dark mode.", keywords: ['terminal', 'theme', 'dark', 'preview'], children: _jsx(ThemePicker, { label: "Dark Theme", description: "Choose the terminal theme used in dark mode.", selectedTheme: settings.terminalThemeDark, query: themeSearchDark, onQueryChange: setThemeSearchDark, onSelectTheme: (theme) => updateSettings({ terminalThemeDark: theme }) }) }), _jsx(SearchableSetting, { title: "Dark Divider Color", description: "Controls the split divider line between panes in dark mode.", keywords: ['terminal', 'divider', 'dark', 'color'], children: _jsx(ColorField, { label: "Dark Divider Color", description: "Controls the split divider line between panes in dark mode.", value: settings.terminalDividerColorDark, fallback: "#3f3f46", onChange: (value) => updateSettings({ terminalDividerColorDark: value }) }) })] }), _jsx(TerminalThemePreview, { title: "Dark Mode Preview", description: settings.theme === 'system'
                    ? `System mode is currently ${systemPrefersDark ? 'Dark' : 'Light'}.`
                    : `Orca is currently in ${settings.theme} mode.`, appearance: darkPreviewAppearance, dividerThicknessPx: previewProps.dividerThicknessPx, inactivePaneOpacity: previewProps.inactivePaneOpacity, activePaneOpacity: previewProps.activePaneOpacity })] }));
}
export function LightTerminalThemeSection({ settings, themeSearchLight, setThemeSearchLight, updateSettings, previewProps, lightPreviewAppearance }) {
    return (_jsxs("section", { className: "space-y-4", children: [_jsxs(SearchableSetting, { title: "Use Separate Theme In Light Mode", description: "When disabled, light mode reuses the dark terminal theme.", keywords: ['terminal', 'light mode', 'theme'], className: "flex items-center justify-between gap-4 px-1 py-2", children: [_jsxs("div", { className: "space-y-0.5", children: [_jsx("p", { className: "text-sm font-medium", children: "Use Separate Theme In Light Mode" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "When disabled, light mode reuses the dark terminal theme." })] }), _jsx("button", { role: "switch", "aria-checked": settings.terminalUseSeparateLightTheme, onClick: () => updateSettings({
                            terminalUseSeparateLightTheme: !settings.terminalUseSeparateLightTheme
                        }), className: `relative inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border border-transparent transition-colors ${settings.terminalUseSeparateLightTheme ? 'bg-foreground' : 'bg-muted-foreground/30'}`, children: _jsx("span", { className: `pointer-events-none block size-3.5 rounded-full bg-background shadow-sm transition-transform ${settings.terminalUseSeparateLightTheme ? 'translate-x-4' : 'translate-x-0.5'}` }) })] }), _jsx("div", { className: `grid overflow-hidden transition-all duration-300 ease-out ${settings.terminalUseSeparateLightTheme
                    ? 'grid-rows-[1fr] opacity-100'
                    : 'grid-rows-[0fr] opacity-0'}`, children: _jsx("div", { className: "min-h-0", children: _jsxs("div", { className: "grid gap-6 pt-2 xl:grid-cols-[minmax(0,1fr)_360px]", children: [_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("h3", { className: "text-sm font-semibold", children: "Light Theme" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Configure the optional light-mode terminal appearance." })] }), _jsx(SearchableSetting, { title: "Light Theme", description: "Choose the theme used when Orca is in light mode.", keywords: ['terminal', 'theme', 'light', 'preview'], children: _jsx(ThemePicker, { label: "Light Theme", description: "Choose the theme used when Orca is in light mode.", selectedTheme: settings.terminalThemeLight, query: themeSearchLight, onQueryChange: setThemeSearchLight, onSelectTheme: (theme) => updateSettings({ terminalThemeLight: theme }) }) }), _jsx(SearchableSetting, { title: "Light Divider Color", description: "Controls the split divider line between panes in light mode.", keywords: ['terminal', 'divider', 'light', 'color'], children: _jsx(ColorField, { label: "Light Divider Color", description: "Controls the split divider line between panes in light mode.", value: settings.terminalDividerColorLight, fallback: "#d4d4d8", onChange: (value) => updateSettings({ terminalDividerColorLight: value }) }) })] }), _jsx(TerminalThemePreview, { title: "Light Mode Preview", description: "Updates live as you change the light theme or divider color.", appearance: lightPreviewAppearance, dividerThicknessPx: previewProps.dividerThicknessPx, inactivePaneOpacity: previewProps.inactivePaneOpacity, activePaneOpacity: previewProps.activePaneOpacity })] }) }) })] }));
}
