import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { terminalPalettePreview } from '@/lib/terminal-theme';
export function TerminalThemePreview({ title, description, appearance, dividerThicknessPx = 3, inactivePaneOpacity = 0.9, activePaneOpacity = 1 }) {
    const background = appearance.theme?.background ?? (appearance.mode === 'light' ? '#f8fafc' : '#09090b');
    const foreground = appearance.theme?.foreground ?? (appearance.mode === 'light' ? '#111827' : '#f4f4f5');
    const cursor = appearance.theme?.cursor ?? foreground;
    const selection = appearance.theme?.selectionBackground ??
        (appearance.mode === 'light' ? 'rgba(59, 130, 246, 0.18)' : 'rgba(148, 163, 184, 0.22)');
    const palette = terminalPalettePreview(appearance.theme);
    return (_jsxs(Card, { className: "gap-4 overflow-hidden py-0", children: [_jsxs(CardHeader, { className: "gap-1 border-b border-border/50 py-4", children: [_jsx(CardTitle, { className: "text-sm", children: title }), _jsx(CardDescription, { children: description })] }), _jsxs(CardContent, { className: "space-y-4 px-4 pb-4", children: [_jsxs("div", { className: "flex items-center justify-between rounded-md border border-border/50 bg-muted/40 px-3 py-2 text-xs", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "font-medium text-foreground", children: appearance.themeName }), _jsx("p", { className: "text-muted-foreground", children: appearance.sourceTheme === 'system'
                                            ? `System mode, currently ${appearance.systemPrefersDark ? 'Dark' : 'Light'}`
                                            : `${appearance.mode === 'dark' ? 'Dark' : 'Light'} mode` })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "Divider" }), _jsx("span", { className: "size-4 rounded-sm border border-border/50", style: { backgroundColor: appearance.dividerColor } })] })] }), _jsx("div", { className: "overflow-hidden rounded-lg border border-border/50", style: { backgroundColor: appearance.dividerColor }, children: _jsxs("div", { className: "flex min-h-[220px]", children: [_jsxs("div", { className: "flex-1 p-3 font-mono text-[12px] leading-6", style: { backgroundColor: background, color: foreground, opacity: activePaneOpacity }, children: [_jsxs("div", { className: "flex items-center gap-2 text-[11px] opacity-70", children: [_jsx("span", { className: "size-2 rounded-full bg-emerald-500" }), _jsx("span", { children: "orca preview" })] }), _jsx("div", { className: "mt-3", children: "$ git status --short" }), _jsx("div", { style: { color: palette[1] ?? foreground }, children: "M src/renderer/src/components/Settings.tsx" }), _jsx("div", { style: { color: palette[2] ?? foreground }, children: "A src/renderer/src/lib/terminal-theme.ts" }), _jsx("div", { className: "mt-3", children: _jsx("span", { style: { backgroundColor: selection }, children: "theme preview selected text" }) }), _jsxs("div", { className: "mt-3 flex items-center gap-2", children: [_jsx("span", { children: "$" }), _jsx("span", { children: "echo \"cursor\"" }), _jsx("span", { className: "inline-block h-[1.1em] w-[0.6ch] align-middle", style: { backgroundColor: cursor } })] })] }), _jsx("div", { className: "shrink-0", style: { width: `${dividerThicknessPx}px`, backgroundColor: appearance.dividerColor } }), _jsxs("div", { className: "w-[38%] p-3 font-mono text-[12px] leading-6", style: {
                                        backgroundColor: background,
                                        color: foreground,
                                        opacity: inactivePaneOpacity
                                    }, children: [_jsx("div", { className: "opacity-70", children: "palette" }), _jsx("div", { className: "mt-3 grid grid-cols-4 gap-2", children: (palette.length ? palette : [foreground]).map((swatch, index) => (_jsx("div", { className: "h-6 rounded-sm border border-black/10", style: { backgroundColor: swatch } }, `${swatch}-${index}`))) })] })] }) })] })] }));
}
