export const AGENT_TYPE_MAX_LENGTH = 40
export const AGENT_MODEL_MAX_LENGTH = 120
export const AGENT_STATUS_TOOL_NAME_MAX_LENGTH = 60
export const AGENT_STATUS_TOOL_INPUT_MAX_LENGTH = 160
export const AGENT_STATUS_ASSISTANT_MESSAGE_MAX_LENGTH = 8000
export const AGENT_STATUS_INTERACTIVE_PROMPT_MAX_LENGTH = 16000
