/** Monaco color theme for file/diff editors. Values other than 'auto'/'vs'/'vs-dark'
 * are ids from the editor theme catalog (renderer/src/lib/editor-themes/catalog.ts). */
export type EditorColorTheme =
  | 'auto'
  | 'vs'
  | 'vs-dark'
  | 'dracula'
  | 'one-dark'
  | 'nord'
  | 'monokai'
  | 'tokyo-night'
  | 'gruvbox-dark'
  | 'catppuccin-mocha'
  | 'solarized-dark'
  | 'material-dark'
  | 'ayu-dark'
  | 'nightfox'
  | 'kanagawa'
  | 'rose-pine'
  | 'everforest-dark'
  | 'palenight'
  | 'horizon-dark'
  | 'night-owl'
  | 'solarized-light'
  | 'one-light'
  | 'catppuccin-latte'
  | 'github-light'
  | 'rose-pine-dawn'
  | 'gruvbox-light'
  | 'tokyo-night-light'
  | 'everforest-light'
  | 'ghostty-default-style-dark'
  | 'builtin-tango-light'
  | 'tango-dark'
  | 'homebrew'
  | 'snazzy'
