import type { GlobalSettings } from './types'

export const PORTABLE_SETTINGS_KEYS = [
  'nestWorkspaces',
  'refreshLocalBaseRefOnWorktreeCreate',
  'localBaseRefSuggestionDismissed',
  'autoRenameBranchFromWork',
  'autoRenameBranchFromWorkDefaultedOn',
  'branchPrefix',
  'branchPrefixCustom',
  'enableGitHubAttribution',
  'theme',
  'uiLanguage',
  'appIcon',
  'appFontFamily',
  'editorAutoSave',
  'editorAutoSaveDelayMs',
  'editorMinimapEnabled',
  'markdownReviewToolsEnabled',
  'primarySelectionMiddleClickPaste',
  'primarySelectionMiddleClickPasteDefaultedForLinux',
  'primarySelectionMiddleClickPasteDefaultedForTerminalDefaults',
  'terminalFontSize',
  'terminalFontFamily',
  'terminalFontWeight',
  'terminalLineHeight',
  'terminalGpuAcceleration',
  'terminalLigatures',
  'terminalCursorStyle',
  'terminalCursorStyleDefaultedToBlock',
  'terminalCursorBlink',
  'terminalThemeDark',
  'terminalDividerColorDark',
  'terminalUseSeparateLightTheme',
  'terminalThemeLight',
  'terminalDividerColorLight',
  'terminalInactivePaneOpacity',
  'terminalActivePaneOpacity',
  'terminalPaneOpacityTransitionMs',
  'terminalDividerThicknessPx',
  'terminalBackgroundOpacity',
  'terminalColorOverrides',
  'terminalPaddingX',
  'terminalPaddingY',
  'terminalMouseHideWhileTyping',
  'terminalWordSeparator',
  'terminalCursorOpacity',
  'terminalQuickCommands',
  'windowBackgroundBlur',
  'terminalRightClickToPaste',
  'terminalFocusFollowsMouse',
  'terminalClipboardOnSelect',
  'terminalAllowOsc52Clipboard',
  'claudeAgentTeamsMode',
  'setupScriptLaunchMode',
  'terminalScrollbackBytes',
  'electronHttp1CompatibilityMode',
  'openLinksInApp',
  'rightSidebarOpenByDefault',
  'showGitIgnoredFiles',
  'sourceControlViewMode',
  'showTitlebarAppName',
  'showTasksButton',
  'showAutomationsButton',
  'showMobileButton',
  'ctrlTabOrderMode',
  'terminalShortcutPolicy',
  'floatingTerminalEnabled',
  'floatingTerminalDefaultedForAllUsers',
  'floatingTerminalTriggerLocation',
  'notifications',
  'diffDefaultView',
  'combinedDiffFileTreeVisibleByDefault',
  'promptCacheTimerEnabled',
  'promptCacheTtlMs',
  'terminalScopeHistoryByWorktree',
  'defaultTuiAgent',
  'disabledTuiAgents',
  'claudeAgentTeamsDefaultDisabledMigrated',
  'skipDeleteWorktreeConfirm',
  'skipDeleteAutomationConfirm',
  'defaultTaskViewPreset',
  'defaultTaskSource',
  'visibleTaskProviders',
  'visibleTaskProvidersDefaultedForJira',
  'geminiCliOAuthEnabled',
  'agentCmdOverrides',
  'agentStatusHooksEnabled',
  'tabAutoGenerateTitle',
  'keepComputerAwakeWhileAgentsRun',
  'terminalMacOptionAsAlt',
  'terminalMacOptionAsAltMigrated',
  'terminalJISYenToBackslash',
  'experimentalMobile',
  'mobileEmulatorEnabled',
  'mobileAutoRestoreFitMs',
  'experimentalPet',
  'experimentalActivity',
  'experimentalActivityDefaultedOffForAllUsers',
  'experimentalTerminalAttention',
  'compactWorktreeCards',
  'experimentalWorktreeSymlinks',
  'commitMessageAi',
  'sourceControlAi',
  'voice'
] as const satisfies readonly (keyof GlobalSettings)[]

export const PORTABLE_STRING_ENUM_VALUES: Partial<Record<keyof GlobalSettings, readonly string[]>> =
  {
    branchPrefix: ['git-username', 'custom', 'none'],
    theme: ['system', 'dark', 'light'],
    terminalGpuAcceleration: ['auto', 'on', 'off'],
    terminalLigatures: ['auto', 'on', 'off'],
    terminalCursorStyle: ['bar', 'block', 'underline'],
    claudeAgentTeamsMode: ['off', 'in-process', 'native-panes-shim', 'orca-managed-tmux'],
    setupScriptLaunchMode: ['split-vertical', 'split-horizontal', 'new-tab'],
    sourceControlViewMode: ['list', 'tree'],
    ctrlTabOrderMode: ['mru', 'sequential'],
    terminalShortcutPolicy: ['orca-first', 'terminal-first'],
    floatingTerminalTriggerLocation: ['floating-button', 'status-bar'],
    diffDefaultView: ['inline', 'side-by-side'],
    defaultTaskViewPreset: ['all', 'issues', 'review', 'my-issues', 'my-prs', 'prs'],
    defaultTaskSource: ['github', 'gitlab', 'linear', 'jira'],
    terminalMacOptionAsAlt: ['auto', 'true', 'false', 'left', 'right']
  }
