/** Re-export barrel over the authoritative shared type modules.
 *  Declares nothing itself — every symbol lives in the module that owns it.
 *  New types belong in a domain module, not here. */

export * from './browser-workspace-types'
export * from './classified-error'
export * from './code-search-types'
export * from './commit-message-ai-types'
export * from './diff-comment-types'
export * from './filesystem-entry-types'
export * from './folder-workspace-types'
export * from './git-diff-compare-types'
export * from './github/check-types'
export * from './github/comment-types'
export * from './github/pull-request-refresh-types'
export * from './github/pull-request-types'
export * from './github/rate-limit-types'
export * from './github/work-item-types'
export * from './global-settings-types'
export * from './host-setting-overrides'
export * from './issue-mutation-types'
export * from './linear/issue-types'
export * from './linear/project-types'
export * from './linear/workspace-types'
export * from './managed-account-types'
export * from './notification-settings-types'
export * from './onboarding-state-types'
export * from './orca-yaml-hook-types'
export * from './persisted-state-types'
export * from './persisted-ui-state-types'
export * from './pet-types'
export * from './process-stats-types'
export * from './project-group-types'
export * from './project-types'
export * from './repo-types'
export * from './shell-path-hydration-types'
export * from './tab-types'
export * from './terminal-color-overrides'
export * from './terminal-quick-command-types'
export * from './terminal-tab-types'
export * from './tui-agent'
export * from './ui-chrome-types'
export * from './update-status-types'
export * from './workspace-session-state-types'
export * from './worktree/base-ref-drift-types'
export * from './worktree/create-types'
export * from './worktree/launch-types'
export * from './worktree/lineage-types'
export * from './worktree/meta-types'
export * from './worktree/types'
export * from './git-status-types'
export * from './git-fork-sync'
export * from './task-providers'
export * from './workspace-source'

// Aliased re-export: `export *` cannot rename, so this one stays explicit.
export type { WorkspaceSource as WorkspaceCreateTelemetrySource } from './workspace-source'
