import type { BrowserPage, BrowserWorkspace, Worktree } from '../../../shared/types';
import type { MatchRange } from './worktree-palette-search';
export type SearchableBrowserPage = {
    page: BrowserPage;
    workspace: BrowserWorkspace;
    worktree: Worktree;
    repoName: string;
    worktreeSortIndex: number;
    isCurrentPage: boolean;
    isCurrentWorktree: boolean;
};
export type BrowserPaletteSearchResult = {
    pageId: string;
    workspaceId: string;
    worktreeId: string;
    title: string;
    secondaryText: string;
    workspaceLabel: string | null;
    repoName: string;
    worktreeName: string;
    workspaceRange: MatchRange | null;
    titleRange: MatchRange | null;
    secondaryRange: MatchRange | null;
    repoRange: MatchRange | null;
    worktreeRange: MatchRange | null;
    isCurrentPage: boolean;
    isCurrentWorktree: boolean;
    score: number;
};
export declare function isBlankBrowserUrl(url: string): boolean;
export declare function formatBrowserPaletteUrl(url: string): string;
export declare function searchBrowserPages(entries: SearchableBrowserPage[], query: string): BrowserPaletteSearchResult[];
