import {
  Database,
  FileArchive,
  FileAxis3D,
  FileBraces,
  FileChartColumn,
  FileCode,
  FileCog,
  FileDiff,
  FileImage,
  FileJson,
  FileKey,
  FileLock,
  FileMusic,
  FileSliders,
  FileSpreadsheet,
  FileTerminal,
  FileText,
  FileType,
  FileVideo,
  type LucideIcon
} from 'lucide-react'
import {
  FileCsv,
  FileExcel,
  FileMarkdown,
  FileNotebook,
  FilePdf,
  FileWord
} from './document-file-icons'

export const FILE_ICON_BY_EXTENSION: Record<string, LucideIcon> = {
  '7z': FileArchive,
  aac: FileMusic,
  adoc: FileText,
  ai: FileImage,
  arrow: Database,
  asc: FileKey,
  astro: FileCode,
  avi: FileVideo,
  avif: FileImage,
  avro: Database,
  bash: FileTerminal,
  bat: FileTerminal,
  blend: FileAxis3D,
  bmp: FileImage,
  br: FileArchive,
  bz2: FileArchive,
  c: FileCode,
  cc: FileCode,
  cer: FileKey,
  cfg: FileSliders,
  cjs: FileCode,
  clj: FileCode,
  cmd: FileTerminal,
  conf: FileSliders,
  cpp: FileCode,
  crt: FileKey,
  cs: FileCode,
  css: FileType,
  csv: FileCsv,
  cts: FileCode,
  cxx: FileCode,
  dart: FileCode,
  db: Database,
  diff: FileDiff,
  dmg: FileArchive,
  doc: FileWord,
  docm: FileWord,
  docx: FileWord,
  dotm: FileWord,
  dotx: FileWord,
  dta: Database,
  duckdb: Database,
  eot: FileType,
  eps: FileImage,
  erl: FileCode,
  ex: FileCode,
  exs: FileCode,
  fbx: FileAxis3D,
  feather: Database,
  fish: FileTerminal,
  flac: FileMusic,
  fods: FileSpreadsheet,
  fs: FileCode,
  fsx: FileCode,
  gif: FileImage,
  glb: FileAxis3D,
  gltf: FileAxis3D,
  go: FileCode,
  gpg: FileKey,
  gql: FileBraces,
  gradle: FileCog,
  graphql: FileBraces,
  gz: FileArchive,
  h: FileCode,
  h5: Database,
  hcl: FileSliders,
  hdf5: Database,
  heic: FileImage,
  hpp: FileCode,
  hrl: FileCode,
  hs: FileCode,
  htm: FileCode,
  html: FileCode,
  ico: FileImage,
  ini: FileSliders,
  ipynb: FileNotebook,
  iso: FileArchive,
  java: FileCode,
  jl: FileCode,
  jpeg: FileImage,
  jpg: FileImage,
  js: FileCode,
  json: FileJson,
  json5: FileJson,
  jsonc: FileJson,
  jsonl: FileJson,
  jsx: FileCode,
  key: FileKey,
  kt: FileCode,
  kts: FileCode,
  less: FileType,
  lock: FileLock,
  log: FileText,
  lua: FileCode,
  m4a: FileMusic,
  m4v: FileVideo,
  markdown: FileMarkdown,
  md: FileMarkdown,
  mdx: FileMarkdown,
  mjs: FileCode,
  mkv: FileVideo,
  mmd: FileChartColumn,
  mov: FileVideo,
  mp3: FileMusic,
  mp4: FileVideo,
  mpeg: FileVideo,
  mpg: FileVideo,
  mts: FileCode,
  ndjson: FileJson,
  nim: FileCode,
  npy: Database,
  npz: Database,
  nu: FileTerminal,
  numbers: FileSpreadsheet,
  obj: FileAxis3D,
  odp: FileChartColumn,
  ods: FileSpreadsheet,
  odt: FileText,
  ogg: FileMusic,
  opus: FileMusic,
  otf: FileType,
  otp: FileChartColumn,
  ots: FileSpreadsheet,
  ott: FileText,
  p12: FileLock,
  pages: FileText,
  parquet: Database,
  patch: FileDiff,
  pdf: FilePdf,
  pem: FileKey,
  pfx: FileLock,
  php: FileCode,
  pl: FileCode,
  pm: FileCode,
  png: FileImage,
  potx: FileChartColumn,
  pps: FileChartColumn,
  ppsx: FileChartColumn,
  ppt: FileChartColumn,
  pptm: FileChartColumn,
  pptx: FileChartColumn,
  prisma: Database,
  properties: FileSliders,
  proto: FileBraces,
  ps1: FileTerminal,
  psd: FileImage,
  pub: FileKey,
  py: FileCode,
  qmd: FileNotebook,
  r: FileCode,
  rar: FileArchive,
  rb: FileCode,
  rdata: Database,
  rds: Database,
  rmd: FileNotebook,
  rs: FileCode,
  rst: FileText,
  rtf: FileText,
  sass: FileType,
  scala: FileCode,
  scss: FileType,
  sh: FileTerminal,
  sol: FileCode,
  sql: Database,
  sqlite: Database,
  sqlite3: Database,
  stl: FileAxis3D,
  svelte: FileCode,
  svg: FileImage,
  swift: FileCode,
  tar: FileArchive,
  'tar.bz2': FileArchive,
  'tar.gz': FileArchive,
  'tar.xz': FileArchive,
  tbz2: FileArchive,
  tex: FileText,
  tf: FileSliders,
  tfvars: FileSliders,
  tgz: FileArchive,
  tif: FileImage,
  tiff: FileImage,
  toml: FileSliders,
  ts: FileCode,
  tsv: FileCsv,
  tsx: FileCode,
  ttf: FileType,
  txt: FileText,
  txz: FileArchive,
  vb: FileCode,
  vue: FileCode,
  wav: FileMusic,
  webm: FileVideo,
  webp: FileImage,
  woff: FileType,
  woff2: FileType,
  xhtml: FileCode,
  xls: FileExcel,
  xlsb: FileExcel,
  xlsm: FileExcel,
  xlsx: FileExcel,
  xlt: FileExcel,
  xltm: FileExcel,
  xltx: FileExcel,
  xml: FileCode,
  xz: FileArchive,
  yaml: FileSliders,
  yml: FileSliders,
  zig: FileCode,
  zip: FileArchive,
  zsh: FileTerminal
}

export const COMPOUND_EXTENSIONS = ['tar.bz2', 'tar.gz', 'tar.xz']
