import type React from 'react'
import { AppWindow } from 'lucide-react'
import type { OpenInApplication } from '../../../shared/types'
import { cn } from './utils'
import { translate } from '@/i18n/i18n'
import { createLocalizedCatalog } from '@/i18n/localized-catalog'
import intellijIdeaIcon from '../../../../resources/jetbrains-intellijidea.svg'
import webstormIcon from '../../../../resources/jetbrains-webstorm.svg'
import pycharmIcon from '../../../../resources/jetbrains-pycharm.svg'
import phpstormIcon from '../../../../resources/jetbrains-phpstorm.svg'
import golandIcon from '../../../../resources/jetbrains-goland.svg'
import riderIcon from '../../../../resources/jetbrains-rider.svg'
import clionIcon from '../../../../resources/jetbrains-clion.svg'
import rubymineIcon from '../../../../resources/jetbrains-rubymine.svg'
import datagripIcon from '../../../../resources/jetbrains-datagrip.svg'
import rustroverIcon from '../../../../resources/jetbrains-rustrover.svg'

export type OpenInAppPreset = {
  id: string
  label: string
  command: string
  faviconDomain: string
  /** Bundled icon that takes precedence over the favicon lookup. */
  iconSrc?: string
  iconClassName?: string
  group?: 'jetbrains'
}

/**
 * Built-in apps offered by the "Add app" dropdown. JetBrains entries use the
 * launcher command names generated by JetBrains Toolbox on every platform.
 */
export const getOpenInAppPresets = createLocalizedCatalog((): OpenInAppPreset[] => [
  {
    id: 'vscode',
    label: translate('auto.lib.open.in.app.catalog.173553f73a', 'VS Code'),
    command: 'code',
    faviconDomain: 'code.visualstudio.com'
  },
  {
    id: 'cursor',
    label: translate('auto.lib.open.in.app.catalog.d62b12e98a', 'Cursor'),
    command: 'cursor',
    faviconDomain: 'cursor.com'
  },
  {
    id: 'zed',
    label: translate('auto.lib.open.in.app.catalog.f8b8ca2711', 'Zed'),
    command: 'zed',
    faviconDomain: 'zed.dev',
    // Why: Zed's favicon is a black transparent mark, which disappears on dark menus.
    iconClassName: 'dark:invert'
  },
  // Commands match the launcher scripts generated by JetBrains Toolbox.
  {
    id: 'intellij-idea',
    label: translate('auto.lib.open.in.app.catalog.00451c5ef5', 'IntelliJ IDEA'),
    command: 'idea',
    faviconDomain: 'jetbrains.com',
    iconSrc: intellijIdeaIcon,
    group: 'jetbrains'
  },
  {
    id: 'webstorm',
    label: translate('auto.lib.open.in.app.catalog.20e6751d0c', 'WebStorm'),
    command: 'webstorm',
    faviconDomain: 'jetbrains.com',
    iconSrc: webstormIcon,
    group: 'jetbrains'
  },
  {
    id: 'pycharm',
    label: translate('auto.lib.open.in.app.catalog.ac4b2e2652', 'PyCharm'),
    command: 'pycharm',
    faviconDomain: 'jetbrains.com',
    iconSrc: pycharmIcon,
    group: 'jetbrains'
  },
  {
    id: 'phpstorm',
    label: translate('auto.lib.open.in.app.catalog.520eebd9c1', 'PhpStorm'),
    command: 'phpstorm',
    faviconDomain: 'jetbrains.com',
    iconSrc: phpstormIcon,
    group: 'jetbrains'
  },
  {
    id: 'goland',
    label: translate('auto.lib.open.in.app.catalog.842d2bc8d0', 'GoLand'),
    command: 'goland',
    faviconDomain: 'jetbrains.com',
    iconSrc: golandIcon,
    group: 'jetbrains'
  },
  {
    id: 'rider',
    label: translate('auto.lib.open.in.app.catalog.5016fdc052', 'Rider'),
    command: 'rider',
    faviconDomain: 'jetbrains.com',
    iconSrc: riderIcon,
    group: 'jetbrains'
  },
  {
    id: 'clion',
    label: translate('auto.lib.open.in.app.catalog.d48f6a7431', 'CLion'),
    command: 'clion',
    faviconDomain: 'jetbrains.com',
    iconSrc: clionIcon,
    group: 'jetbrains'
  },
  {
    id: 'rubymine',
    label: translate('auto.lib.open.in.app.catalog.e6db8efa01', 'RubyMine'),
    command: 'rubymine',
    faviconDomain: 'jetbrains.com',
    iconSrc: rubymineIcon,
    group: 'jetbrains'
  },
  {
    id: 'datagrip',
    label: translate('auto.lib.open.in.app.catalog.5fdf7d47cd', 'DataGrip'),
    command: 'datagrip',
    faviconDomain: 'jetbrains.com',
    iconSrc: datagripIcon,
    group: 'jetbrains'
  },
  {
    id: 'rustrover',
    label: translate('auto.lib.open.in.app.catalog.366f2eaebc', 'RustRover'),
    command: 'rustrover',
    faviconDomain: 'jetbrains.com',
    iconSrc: rustroverIcon,
    group: 'jetbrains'
  }
])

/** Resolves the preset matching an application's command, or null for custom apps. */
export function getOpenInAppPreset(
  application: Pick<OpenInApplication, 'command'>
): OpenInAppPreset | null {
  const command = application.command.trim().toLowerCase()
  return getOpenInAppPresets().find((preset) => preset.command === command) ?? null
}

/** True when the user's configured apps already include this preset's command. */
export function isOpenInAppPresetAdded(
  applications: readonly Pick<OpenInApplication, 'command'>[],
  preset: OpenInAppPreset
): boolean {
  return applications.some(
    (application) => application.command.trim().toLowerCase() === preset.command
  )
}

/**
 * Icon for an Open In app: bundled preset icon first, then the favicon
 * service, then a generic window glyph for custom apps.
 */
export function OpenInApplicationIcon({
  application,
  size = 14
}: {
  application: Pick<OpenInApplication, 'command'>
  size?: number
}): React.JSX.Element {
  const preset = getOpenInAppPreset(application)
  if (preset) {
    return (
      <img
        src={
          preset.iconSrc ??
          `https://www.google.com/s2/favicons?domain=${preset.faviconDomain}&sz=64`
        }
        width={size}
        height={size}
        alt=""
        aria-hidden
        className={cn('shrink-0', preset.iconClassName)}
        style={{ borderRadius: 2 }}
      />
    )
  }
  return <AppWindow width={size} height={size} />
}
