import type React from 'react'
import { AppWindow } from 'lucide-react'
import type { OpenInApplication } from '../../../shared/ui-chrome-types'
import { cn } from './utils'
import { translate } from '@/i18n/i18n'
import { createLocalizedCatalog } from '@/i18n/localized-catalog'
import intellijIdeaIcon from '../../../../resources/jetbrains-intellijidea.svg'

export type OpenInAppPreset = {
  id: string
  label: string
  command: string
  faviconDomain: string
  /** Bundled icon that takes precedence over the favicon lookup. */
  iconSrc?: string
  iconClassName?: string
}

/**
 * Built-in apps offered by the "Add app" dropdown. The IntelliJ IDEA command
 * matches the launcher script generated by JetBrains Toolbox on every platform.
 */
export const getOpenInAppPresets = createLocalizedCatalog((): OpenInAppPreset[] => [
  {
    id: 'vscode',
    label: translate('auto.lib.open.in.app.catalog.173553f73a', 'VS Code'),
    command: 'code',
    faviconDomain: 'code.visualstudio.com'
  },
  {
    id: 'cursor',
    label: translate('auto.lib.open.in.app.catalog.d62b12e98a', 'Cursor'),
    command: 'cursor',
    faviconDomain: 'cursor.com'
  },
  {
    id: 'zed',
    label: translate('auto.lib.open.in.app.catalog.f8b8ca2711', 'Zed'),
    command: 'zed',
    faviconDomain: 'zed.dev',
    // Why: Zed's favicon is a black transparent mark, which disappears on dark menus.
    iconClassName: 'dark:invert'
  },
  {
    id: 'intellij-idea',
    label: translate('auto.lib.open.in.app.catalog.00451c5ef5', 'IntelliJ IDEA'),
    command: 'idea',
    faviconDomain: 'jetbrains.com',
    iconSrc: intellijIdeaIcon
  }
])

/** Resolves the preset matching an application's command, or null for custom apps. */
export function getOpenInAppPreset(
  application: Pick<OpenInApplication, 'command'>
): OpenInAppPreset | null {
  const command = application.command.trim().toLowerCase()
  return getOpenInAppPresets().find((preset) => preset.command === command) ?? null
}

/** True when the user's configured apps already include this preset's command. */
export function isOpenInAppPresetAdded(
  applications: readonly Pick<OpenInApplication, 'command'>[],
  preset: OpenInAppPreset
): boolean {
  return applications.some(
    (application) => application.command.trim().toLowerCase() === preset.command
  )
}

/**
 * Icon for an Open In app: bundled preset icon first, then the favicon
 * service, then a generic window glyph for custom apps.
 */
export function OpenInApplicationIcon({
  application,
  size = 14
}: {
  application: Pick<OpenInApplication, 'command'>
  size?: number
}): React.JSX.Element {
  const preset = getOpenInAppPreset(application)
  if (preset) {
    return (
      <img
        src={
          preset.iconSrc ??
          `https://www.google.com/s2/favicons?domain=${preset.faviconDomain}&sz=64`
        }
        width={size}
        height={size}
        alt=""
        aria-hidden
        className={cn('shrink-0', preset.iconClassName)}
        style={{ borderRadius: 2 }}
      />
    )
  }
  return <AppWindow width={size} height={size} />
}
