import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '@/components/ui/badge';
import { HoverCard, HoverCardTrigger, HoverCardContent } from '@/components/ui/hover-card';
import { CircleDot } from 'lucide-react';
import { cn } from '@/lib/utils';
import CommentMarkdown from './CommentMarkdown';
import { PullRequestIcon, prStateLabel, checksLabel } from './WorktreeCardHelpers';
export function IssueSection({ issue, onClick }) {
    return (_jsxs(HoverCard, { openDelay: 300, children: [_jsx(HoverCardTrigger, { asChild: true, children: _jsxs("div", { className: "flex items-center gap-1.5 min-w-0 cursor-pointer group/meta -mx-1.5 px-1.5 py-0.5 rounded transition-colors hover:bg-background/40", onClick: onClick, children: [_jsx(CircleDot, { className: "size-3 shrink-0 text-muted-foreground opacity-60" }), _jsxs("div", { className: "flex-1 min-w-0 flex items-center gap-1.5 text-[11.5px] leading-none", children: [_jsxs("span", { className: "text-foreground opacity-80 font-medium shrink-0", children: ["#", issue.number] }), _jsx("span", { className: "text-muted-foreground truncate group-hover/meta:text-foreground transition-colors", children: issue.title })] })] }) }), _jsxs(HoverCardContent, { side: "right", align: "start", className: "w-72 p-3 text-xs space-y-1.5", children: [_jsxs("div", { className: "font-semibold text-[13px]", children: ["#", issue.number, " ", issue.title] }), _jsxs("div", { className: "text-muted-foreground", children: ["State: ", issue.state === 'open' ? 'Open' : 'Closed'] }), issue.labels.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-1", children: issue.labels.map((l) => (_jsx(Badge, { variant: "outline", className: "h-4 px-1.5 text-[9px]", children: l }, l))) })), _jsx("a", { href: issue.url, target: "_blank", rel: "noreferrer", className: "text-muted-foreground underline underline-offset-2 hover:text-foreground", children: "View on GitHub" })] })] }));
}
export function PrSection({ pr, onClick }) {
    return (_jsxs(HoverCard, { openDelay: 300, children: [_jsx(HoverCardTrigger, { asChild: true, children: _jsxs("div", { className: "flex items-center gap-1.5 min-w-0 cursor-pointer group/meta -mx-1.5 px-1.5 py-0.5 rounded transition-colors hover:bg-background/40", onClick: onClick, children: [_jsx(PullRequestIcon, { className: cn('size-3 shrink-0', pr.state === 'merged' && 'text-purple-600/70 dark:text-purple-400/70', pr.state === 'open' && 'text-emerald-500/80', pr.state === 'closed' && 'text-muted-foreground/60', pr.state === 'draft' && 'text-muted-foreground/50', (!pr.state || !['merged', 'open', 'closed', 'draft'].includes(pr.state)) &&
                                'text-muted-foreground opacity-60') }), _jsxs("div", { className: "flex-1 min-w-0 flex items-center gap-1.5 text-[11.5px] leading-none", children: [_jsxs("a", { href: pr.url, target: "_blank", rel: "noreferrer", className: "text-foreground opacity-80 font-medium shrink-0 hover:text-foreground hover:underline", onClick: (e) => e.stopPropagation(), children: ["PR #", pr.number] }), _jsx("span", { className: "text-muted-foreground truncate group-hover/meta:text-foreground transition-colors", children: pr.title })] })] }) }), _jsxs(HoverCardContent, { side: "right", align: "start", className: "w-72 p-3 text-xs space-y-1.5", children: [_jsxs("div", { className: "font-semibold text-[13px]", children: ["#", pr.number, " ", pr.title] }), _jsxs("div", { className: "flex items-center gap-2 text-muted-foreground", children: [_jsxs("span", { children: ["State: ", prStateLabel(pr.state)] }), pr.checksStatus !== 'neutral' && _jsxs("span", { children: ["Checks: ", checksLabel(pr.checksStatus)] })] }), _jsx("a", { href: pr.url, target: "_blank", rel: "noreferrer", className: "text-muted-foreground underline underline-offset-2 hover:text-foreground", onClick: (e) => e.stopPropagation(), children: "View on GitHub" })] })] }));
}
export function CommentSection({ comment, onDoubleClick }) {
    return (_jsxs(HoverCard, { openDelay: 400, children: [_jsx(HoverCardTrigger, { asChild: true, children: _jsx(CommentMarkdown, { content: comment, className: "text-[11px] text-muted-foreground break-words -mx-1.5 px-1.5 py-0.5 rounded transition-colors leading-normal line-clamp-2 [&_.comment-md-p]:inline [&_.comment-md-p+.comment-md-p]:before:content-['_']", onDoubleClick: onDoubleClick }) }), _jsx(HoverCardContent, { side: "right", align: "start", className: "w-72 max-h-80 overflow-y-auto p-3", children: _jsx(CommentMarkdown, { content: comment, className: "text-[11.5px] text-foreground break-words leading-normal [&_.comment-md-p]:block [&_.comment-md-p+.comment-md-p]:mt-1" }) })] }));
}
