import { quotePosixShell } from '../../shared/wsl-login-shell-command'

export const WSL_SESSION_BRIDGE_TIMEOUT_MS = 30_000

const WSL_CODEX_SESSION_BRIDGE_BODY = [
  'set -u',
  'rollback_manifest=${3-}',
  'rollback_stage_root=${4-}',
  'scan_scope=${5-full}',
  'scan_start=${6-}',
  'scan_end=${7-}',
  'index_pending_root=${index_pending_root-}',
  'if [ -n "$rollback_manifest" ]; then',
  '  [ -n "$rollback_stage_root" ] || exit 1',
  '  mkdir -p -- "$rollback_stage_root" || exit 1',
  '  : > "$rollback_manifest" || exit 1',
  'fi',
  'if [ -n "$index_pending_root" ]; then',
  '  mkdir -p -- "$index_pending_root" || exit 1',
  'fi',
  'scanned_files=0',
  'linked_files=0',
  'bridge_failed=0',
  // Why: pending markers left by an interrupted index heal are still reported without a source.
  'if [ ! -d "$source_sessions_root" ] && [ -z "$index_pending_root" ]; then',
  `  printf '{"scannedFiles":0,"linkedFiles":0}\\n'`,
  '  exit 0',
  'fi',
  'file_list=$(mktemp) || exit 1',
  'day_list="$file_list.days"',
  'pending_list="$file_list.pending"',
  'trap \'rm -f -- "$file_list" "$day_list" "$pending_list"\' EXIT HUP INT TERM',
  'if [ ! -d "$source_sessions_root" ]; then',
  '  scan_scope=none',
  'fi',
  'case "$scan_scope" in',
  '  none) : > "$file_list" || exit 1 ;;',
  `  full) find "$source_sessions_root" -type f -name '*.jsonl' -print0 > "$file_list" || exit 1 ;;`,
  '  recent)',
  '    case "$scan_start" in ????/??/??) ;; *) exit 1 ;; esac',
  '    case "$scan_end" in ????/??/??) ;; *) exit 1 ;; esac',
  '    if [[ "$scan_start" > "$scan_end" ]]; then',
  `      find "$source_sessions_root" -type f -name '*.jsonl' -print0 > "$file_list" || exit 1`,
  '    else',
  '      : > "$file_list" || exit 1',
  '      find "$source_sessions_root" -mindepth 3 -maxdepth 3 -type d -print0 > "$day_list" || exit 1',
  "      while IFS= read -r -d '' session_day_root; do",
  '        session_day=${session_day_root#"$source_sessions_root"/}',
  '        case "$session_day" in ????/??/??) ;; *) continue ;; esac',
  '        [[ "$session_day" < "$scan_start" ]] && continue',
  '        find "$session_day_root" -maxdepth 1 -type f -name \'*.jsonl\' -print0 >> "$file_list" || exit 1',
  '      done < "$day_list"',
  '    fi',
  '    ;;',
  '  *) exit 1 ;;',
  'esac',
  "while IFS= read -r -d '' source_file; do",
  '  scanned_files=$((scanned_files + 1))',
  '  relative_path=${source_file#"$source_sessions_root"/}',
  '  target_file="$managed_sessions_root/$relative_path"',
  '  if [ -e "$target_file" ] || [ -L "$target_file" ]; then',
  '    continue',
  '  fi',
  '  target_dir=${target_file%/*}',
  '  if ! mkdir -p -- "$target_dir"; then',
  '    bridge_failed=1',
  '    continue',
  '  fi',
  '  link_source="$source_file"',
  '  if [ -n "$rollback_manifest" ]; then',
  '    staged_file="$rollback_stage_root/$relative_path"',
  '    staged_dir=${staged_file%/*}',
  '    if ! mkdir -p -- "$staged_dir" || ! ln -- "$source_file" "$staged_file"; then',
  '      bridge_failed=1',
  '      continue',
  '    fi',
  '    target_stage="$target_file.orca-bridge-$$"',
  '    if [ -e "$target_stage" ] || [ -L "$target_stage" ]; then',
  '      bridge_failed=1',
  '      continue',
  '    fi',
  '    if ! ln -- "$staged_file" "$target_stage"; then',
  '      if ! cp -- "$staged_file" "$target_stage" || ! cmp -s -- "$staged_file" "$target_stage"; then',
  '        rm -f -- "$target_stage"',
  '        bridge_failed=1',
  '        continue',
  '      fi',
  '    fi',
  '    if ! printf \'%s\\0%s\\0\' "$target_stage" "$target_file" >> "$rollback_manifest"; then',
  '      rm -f -- "$target_stage"',
  '      bridge_failed=1',
  '      continue',
  '    fi',
  '    link_source="$target_stage"',
  '  fi',
  // Why: the marker is the durable record that Codex still has to index this rollout.
  '  pending_marker=',
  '  case "${index_pending_root:+on}:${source_file##*/}" in',
  '    on:rollout-*.jsonl)',
  '      pending_marker="$index_pending_root/${source_file##*/}"',
  '      if ! : > "$pending_marker"; then',
  '        bridge_failed=1',
  '        continue',
  '      fi',
  '      ;;',
  '  esac',
  // Codex resume ignores symlinked JSONL, so create links inside the distro.
  '  if ln -- "$link_source" "$target_file"; then',
  '    linked_files=$((linked_files + 1))',
  '  elif [ ! -e "$target_file" ] && [ ! -L "$target_file" ]; then',
  '    if [ -n "$rollback_manifest" ]; then',
  '      bridge_failed=1',
  '    else',
  '      target_stage="$target_file.orca-bridge-$$"',
  '      if [ ! -e "$target_stage" ] && [ ! -L "$target_stage" ] && cp -- "$source_file" "$target_stage" && cmp -s -- "$source_file" "$target_stage" && ln -- "$target_stage" "$target_file"; then',
  '        linked_files=$((linked_files + 1))',
  '      else',
  '        bridge_failed=1',
  '      fi',
  '      rm -f -- "$target_stage"',
  '    fi',
  '  fi',
  '  if [ -n "$pending_marker" ] && [ ! -e "$target_file" ]; then',
  '    rm -f -- "$pending_marker"',
  '  fi',
  'done < "$file_list"',
  'if [ -n "$index_pending_root" ]; then',
  '  for pending_marker in "$index_pending_root"/rollout-*; do',
  '    [ -f "$pending_marker" ] && printf \'%s\\n\' "${pending_marker##*/}"',
  '  done | LC_ALL=C sort -r > "$pending_list" || exit 1',
  '  pending_files=$(( $(wc -l < "$pending_list") ))',
  '  cat -- "$pending_list" || exit 1',
  // Why: printed before the failure exit so one unlinkable file cannot strand every pending marker.
  `  printf '{"scannedFiles":%s,"linkedFiles":%s,"pendingFiles":%s}\\n' "$scanned_files" "$linked_files" "$pending_files"`,
  '  [ "$bridge_failed" = 0 ] || exit 1',
  '  exit 0',
  'fi',
  '[ "$bridge_failed" = 0 ] || exit 1',
  `printf '{"scannedFiles":%s,"linkedFiles":%s}\\n' "$scanned_files" "$linked_files"`
].join('\n')

export const WSL_CODEX_SESSION_BRIDGE_SCRIPT = [
  'source_sessions_root="$1"',
  'managed_sessions_root="$2"',
  WSL_CODEX_SESSION_BRIDGE_BODY
].join('\n')

/**
 * The launch-time bridge. With `indexPendingRoot`, every newly linked rollout
 * gets an empty marker there, and the script prints the pending marker names
 * (newest first) before a summary that counts them.
 */
export function buildWslCodexSessionBridgeShellCommand(paths: {
  managedSessionsRoot: string
  systemSessionsRoot: string
  indexPendingRoot?: string
}): string {
  return [
    `source_sessions_root=${quotePosixShell(paths.systemSessionsRoot)}`,
    `managed_sessions_root=${quotePosixShell(paths.managedSessionsRoot)}`,
    ...(paths.indexPendingRoot
      ? [`index_pending_root=${quotePosixShell(paths.indexPendingRoot)}`]
      : []),
    WSL_CODEX_SESSION_BRIDGE_BODY
  ].join('\n')
}
