import { expect, it, vi } from 'vitest'
import { DaemonPtyRouter } from './daemon-pty-router'
import { createAdapter } from './daemon-pty-router-test-adapter'

it('unsubscribes only the retired adapter including existing auxiliary subscriptions', async () => {
  const current = createAdapter('current')
  const legacy = createAdapter('legacy', [], 29)
  vi.mocked(legacy.retireIfIdle).mockResolvedValue(true)
  const router = new DaemonPtyRouter({ current, legacy: [legacy] })
  const data = vi.fn()
  const exit = vi.fn()
  const background = vi.fn()
  const unavailable = vi.fn()
  router.onData(data)
  router.onExit(exit)
  const unsubscribeBackground = router.onBackgroundStreamEvent(background)
  const unsubscribeUnavailable = router.onWriteUnavailable(unavailable)
  await router.discoverLegacySessions()
  legacy.emitData('old', 'ignored')
  legacy.emitExit('old', 0)
  legacy.triggerWriteUnavailable('old')
  legacy.emitBackground({ id: 'old', kind: 'dataGap', droppedChars: 1 })
  expect(data).not.toHaveBeenCalled()
  expect(exit).not.toHaveBeenCalled()
  expect(background).not.toHaveBeenCalled()
  expect(unavailable).not.toHaveBeenCalled()
  current.emitData('current', 'kept')
  current.triggerWriteUnavailable('current')
  expect(data).toHaveBeenCalledOnce()
  expect(unavailable).toHaveBeenCalledOnce()
  unsubscribeBackground()
  unsubscribeUnavailable()
  router.disposeRouterOnly()
})
