import type { SessionState, ShellReadyState, TerminalSnapshot } from './types';
export type SubprocessHandle = {
    pid: number;
    write(data: string): void;
    resize(cols: number, rows: number): void;
    kill(): void;
    forceKill(): void;
    signal(sig: string): void;
    onData(cb: (data: string) => void): void;
    onExit(cb: (code: number) => void): void;
};
export type SessionOptions = {
    sessionId: string;
    cols: number;
    rows: number;
    subprocess: SubprocessHandle;
    shellReadySupported: boolean;
    scrollback?: number;
};
export declare class Session {
    readonly sessionId: string;
    private _state;
    private _shellState;
    private _exitCode;
    private _isTerminating;
    private _disposed;
    private emulator;
    private subprocess;
    private attachedClients;
    private preReadyStdinQueue;
    private markerBuffer;
    private shellReadyTimer;
    private killTimer;
    constructor(opts: SessionOptions);
    get state(): SessionState;
    get shellState(): ShellReadyState;
    get exitCode(): number | null;
    get isAlive(): boolean;
    get isTerminating(): boolean;
    get pid(): number;
    write(data: string): void;
    resize(cols: number, rows: number): void;
    kill(): void;
    signal(sig: string): void;
    attachClient(client: {
        onData: (data: string) => void;
        onExit: (code: number) => void;
    }): symbol;
    detachClient(token: symbol): void;
    detachAllClients(): void;
    getSnapshot(): TerminalSnapshot | null;
    getCwd(): string | null;
    clearScrollback(): void;
    dispose(): void;
    private handleSubprocessData;
    private handleSubprocessExit;
    private scanForShellMarker;
    private transitionToReady;
    private onShellReadyTimeout;
    private flushPreReadyQueue;
    private forceDispose;
}
