/** Allowlisted phone methods the relaying Mac always answers itself; never sent with a target. */
export const PAIRED_DESKTOP_METHODS = [
  // Device and pairing concerns of the phone's own pairing.
  'mobileWeb.bundle.chunk',
  'mobileWeb.bundle.manifest',
  'mobileWeb.bundle.range',
  'notifications.getMissedSince',
  'notifications.registerPush',
  'notifications.subscribe',
  'notifications.testPush',
  'notifications.unregisterPush',
  'notifications.unsubscribe',
  'pairing.getEndpoints',
  'pairing.provisionRelay',
  // The configured servers the desktop shows, and their workspace lists as it last fetched them.
  'mobileRelay.hosts.list',
  'mobileRelay.hosts.worktrees',
  'speech.dictation.cancel',
  'speech.dictation.chunk',
  'speech.dictation.finish',
  'speech.dictation.setup',
  'speech.dictation.start',
  'speech.models.delete',
  'speech.models.download',
  'speech.models.list',
  // The Mac also forwards it to every open server connection of that phone.
  'runtime.clientCapabilities.update',
  // The Mac republishes host changes it already observes.
  'runtime.clientEvents.subscribe',
  'runtime.clientEvents.unsubscribe',
  'diagnostics.memory',
  'stats.summary',
  'ui.get',
  'ui.recordFeatureInteraction',
  'ui.set',
  // The desktop's accounts pane, Linear and project pickers target its active runtime, not a workspace's host.
  'accounts.consumeCodexResetCredit',
  'accounts.list',
  'accounts.selectClaude',
  'accounts.selectCodex',
  'accounts.selectCodexForTarget',
  'accounts.subscribe',
  'accounts.unsubscribe',
  'linear.addIssueComment',
  'linear.agentSearchIssues',
  'linear.connect',
  'linear.createIssue',
  'linear.createProject',
  'linear.getCustomView',
  'linear.getIssue',
  'linear.getProject',
  'linear.issueComments',
  'linear.issueContext',
  'linear.listCustomViewIssues',
  'linear.listCustomViewProjects',
  'linear.listCustomViews',
  'linear.listIssues',
  'linear.listProjectIssues',
  'linear.listProjects',
  'linear.listTeams',
  'linear.mcpListIssues',
  'linear.searchIssues',
  'linear.selectWorkspace',
  'linear.status',
  'linear.teamLabels',
  'linear.teamMembers',
  'linear.teamStates',
  'linear.updateIssue',
  'github.project.addIssueCommentBySlug',
  'github.project.clearItemField',
  'github.project.deleteIssueCommentBySlug',
  'github.project.listAccessible',
  'github.project.listAssignableUsersBySlug',
  'github.project.listIssueTypesBySlug',
  'github.project.listLabelsBySlug',
  'github.project.listViews',
  'github.project.resolveRef',
  'github.project.updateIssueBySlug',
  'github.project.updateIssueCommentBySlug',
  'github.project.updateIssueTypeBySlug',
  'github.project.updateItemField',
  'github.project.updatePullRequestBySlug',
  'github.project.viewTable',
  'github.project.workItemDetailsBySlug',
  // Desktop main federates session history across hosts itself (executionHostId / scope params).
  'aiVault.listSessions',
  'aiVault.prepareSessionResume',
  'aiVault.resolveSessionTitles',
  'aiVault.searchSessions',
  'aiVault.searchStatus',
  // User preferences live on the Mac; the phone's settings screens mirror the desktop's.
  'settings.get',
  'settings.getTerminalQuickCommands',
  'settings.mutateNativeChatSessionOptions',
  'settings.update',
  'settings.updateTerminalQuickCommands',
  'terminal.getAutoRestoreFit',
  'terminal.setAutoRestoreFit',
  // A file opens as a tab in the desktop's window, a server workspace's too; a target names the server.
  'files.open',
  'files.openDiff',
  // SSH targets are configured on the Mac.
  'ssh.connect',
  'ssh.getState',
  'ssh.listRemovedTargetLabels',
  'ssh.listTargetSummaries',
  'ssh.listTargets'
] as const
