import type { UpdateStatus } from '../shared/types';
export declare function resetMacInstallState(): void;
export declare function beginMacUpdateDownload(): void;
export declare function markMacQuitAndInstallInFlight(): void;
export declare function consumeMacInstallGuardBypass(): boolean;
export declare function isMacQuitAndInstallInFlight(): boolean;
export declare function isMacInstallerReady(): boolean;
export declare function isWaitingForMacInstallerReadiness(currentStatus: UpdateStatus, hasNewerDownloadedVersion: boolean): boolean;
export declare function deferMacQuitUntilInstallerReady(currentStatus: UpdateStatus, hasNewerDownloadedVersion: boolean, getPendingInstallVersion: () => string, sendStatus: (status: UpdateStatus) => void): boolean;
export declare function handleMacInstallerReady(hasNewerDownloadedVersion: boolean, onReadyToInstall: () => void, onReadyToReportDownloaded: () => void): void;
