import type { UpdateStatus } from '../shared/types';
type UpdaterHandlerContext = {
    clearAvailableUpdateContext: () => void;
    getCurrentStatus: () => UpdateStatus;
    getKnownReleaseUrl: () => string | undefined;
    getPendingInstallVersion: () => string;
    getUserInitiatedCheck: () => boolean;
    hasNewerDownloadedVersion: () => boolean;
    performQuitAndInstall: () => void;
    recordCompletedUpdateCheck: () => void;
    sendCheckFailureStatus: (message: string, userInitiated?: boolean) => Promise<void>;
    sendErrorStatus: (message: string, userInitiated?: boolean) => void;
    sendStatus: (status: UpdateStatus) => void;
    scheduleAutomaticUpdateCheck: (delayMs: number) => void;
    setAvailableReleaseUrl: (releaseUrl: string | null) => void;
    setAvailableVersion: (version: string | null) => void;
    setUserInitiatedCheck: (value: boolean) => void;
};
export declare function registerAutoUpdaterHandlers({ clearAvailableUpdateContext, getCurrentStatus, getKnownReleaseUrl, getPendingInstallVersion, getUserInitiatedCheck, hasNewerDownloadedVersion, performQuitAndInstall, recordCompletedUpdateCheck, sendCheckFailureStatus, sendErrorStatus, sendStatus, scheduleAutomaticUpdateCheck, setAvailableReleaseUrl, setAvailableVersion, setUserInitiatedCheck }: UpdaterHandlerContext): void;
export {};
