import { type Session } from 'electron';
import type { BrowserSessionProfile, BrowserSessionProfileScope } from '../../shared/types';
declare class BrowserSessionRegistry {
    private readonly profiles;
    constructor();
    private get metadataPath();
    private loadPersistedSource;
    private persistMeta;
    private persistSource;
    private loadPersistedMeta;
    restorePersistedUserAgent(): void;
    setupClientHintsOverride(sess: Session, ua: string): void;
    applyPendingCookieImport(): void;
    setPendingCookieImport(stagingDbPath: string): void;
    persistUserAgent(userAgent: string | null): void;
    getDefaultProfile(): BrowserSessionProfile;
    getProfile(profileId: string): BrowserSessionProfile | null;
    listProfiles(): BrowserSessionProfile[];
    isAllowedPartition(partition: string): boolean;
    resolvePartition(profileId: string | null | undefined): string;
    createProfile(scope: BrowserSessionProfileScope, label: string): BrowserSessionProfile;
    updateProfileSource(profileId: string, source: BrowserSessionProfile['source']): BrowserSessionProfile | null;
    deleteProfile(profileId: string): Promise<boolean>;
    clearDefaultSessionCookies(): Promise<boolean>;
    hydrateFromPersisted(profiles: BrowserSessionProfile[]): void;
    private readonly configuredPartitions;
    private setupSessionPolicies;
}
export declare const browserSessionRegistry: BrowserSessionRegistry;
export {};
