import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import {
  buildTerminalDocumentFactoryBody,
  buildTerminalDocumentFactoryModule,
  buildTerminalDocumentScript,
  TERMINAL_DOCUMENT_FACTORY_MODULE_PATH
} from '../../../scripts/build-terminal-document-script.mjs'

/**
 * The two artifacts the generator writes, held to one body (ruling 23).
 *
 * The WebView gets a string it loads; the page gets a module it imports, because building a
 * function from that string needs `eval` and the page's policy refuses it. Two files is the cost of
 * that, and the risk is the obvious one: they drift, and the terminal on the page stops being the
 * terminal on the phone while every other test stays green. So the wrappers are stripped and the
 * remainder compared byte for byte, which is also what makes the byte golden pin the page's file.
 */

/**
 * Each wrapper as literal lines, not as the generator's own template.
 *
 * The body is what the two artifacts share, so the wrappers are all that is left to get wrong, and
 * both of them are a public surface: the page's signature is the one line a caller reads and the
 * native script's trailing call is what starts the phone's terminal. Restating the generator's
 * constants here would only agree with whatever it emits, so these are the exact lines, and a
 * wrapper that drifts on either side reds rather than being stripped as if it had not.
 */
const PAGE_WRAPPER_HEAD = [
  '// Generated by scripts/build-terminal-document-script.mjs. Do not edit.',
  '// The source is mobile/src/terminal/document/, in the order',
  '// scripts/terminal-document-module-order.mjs pins.',
  '// @ts-nocheck -- ruling 23: the body is emitted text, type-checked at each source module.',
  "import type { TerminalDocument, TerminalDocumentHost } from './document/document-host-seams'",
  '',
  'export function createTerminalDocument(',
  '  host: TerminalDocumentHost',
  '): TerminalDocument {'
]

/** The closing brace and the trailing newline the module ends on. */
const PAGE_WRAPPER_TAIL = ['}', '']

const NATIVE_WRAPPER_HEAD = ['function createTerminalDocument(host) {']

/** The closing brace and the one call, with no newline after it. */
const NATIVE_WRAPPER_TAIL = ['}', 'createTerminalDocument();']

/** The artifact's lines between its two wrappers, with the wrappers held to the letter. */
function bodyInsideWrapper(artifact: string, head: string[], tail: string[], what: string): string {
  const lines = artifact.split('\n')
  expect(lines.slice(0, head.length), `the ${what} opens with its wrapper`).toEqual(head)
  expect(lines.slice(lines.length - tail.length), `the ${what} closes with its wrapper`).toEqual(
    tail
  )
  return lines.slice(head.length, lines.length - tail.length).join('\n')
}

describe('the two terminal document artifacts', () => {
  it('carry the same factory body, byte for byte', async () => {
    const body = await buildTerminalDocumentFactoryBody()
    const script = await buildTerminalDocumentScript()
    const module = await buildTerminalDocumentFactoryModule()
    expect(
      bodyInsideWrapper(script, NATIVE_WRAPPER_HEAD, NATIVE_WRAPPER_TAIL, 'native script')
    ).toBe(body)
    expect(bodyInsideWrapper(module, PAGE_WRAPPER_HEAD, PAGE_WRAPPER_TAIL, 'page module')).toBe(
      body
    )
  })

  it('is on disk as the generator would write it now', async () => {
    // The page's file is gitignored and built by postinstall, so a tree whose modules moved after
    // the last build would import yesterday's document. The native script's staleness is already
    // caught by the byte golden; this is the same reading for the file beside it.
    const onDisk = await readFile(TERMINAL_DOCUMENT_FACTORY_MODULE_PATH, 'utf8')
    expect(onDisk).toBe(await buildTerminalDocumentFactoryModule())
  })

  it('gives the page a factory it can call and no call of its own', async () => {
    // A trailing call would start a document as the module was imported, which is the parse-time
    // work ruling 20 removed — and on the page it would run before any host element existed.
    const module = await buildTerminalDocumentFactoryModule()
    expect(module).toContain('export function createTerminalDocument(')
    expect(module).not.toContain('\ncreateTerminalDocument();')
  })
})
