import { createHash } from 'node:crypto'
import { readFileSync, statSync } from 'node:fs'
import type { AgentStatusIpcPayload } from '../../../../shared/agent-status-types'
import { isTuiAgent } from '../../../../shared/tui-agent-config'
import type { OrchestrationDb } from '../db'
import { exposeUtcTimestamp } from '../db/utc-timestamp'
import type { DispatchContextRow } from '../types'
import type { RouteIdentity } from './route-registry-types'
import { readDispatchLaunchEffort, readDispatchLaunchRoutes } from './route-runtime-events'

/** Blocker 8 — the provider's own answer about which model is running.
 *
 *  `effective_model_identity` had no production writer, so no route could be
 *  certified. The launch receipt only ever held what Orca ASKED for, and a
 *  receipt that copies the request proves nothing about what the provider ran.
 *  Claude's hook does not report a model either, so there was nothing to read.
 *
 *  There is one place the provider states its own model: the transcript it
 *  writes itself. Every `assistant` record carries `message.model`, generated by
 *  the provider, not by Orca. That is the observation.
 *
 *  Every binding below exists to stop a transcript describing something else:
 *  the session must be the one this exact Dispatch is running (pane, terminal,
 *  launch token, process incarnation), and the model must have been written
 *  after the Dispatch began, so an older session's file cannot answer for it.
 */

export type ProviderSessionObservation = {
  identity: RouteIdentity
  sessionId: string
  transcriptPath: string
  observedAtMs: number
}

export type ProviderSessionRejection =
  | 'no_status_for_dispatch'
  | 'no_provider_session'
  | 'session_not_this_dispatch'
  | 'no_transcript'
  | 'no_provider_model'
  | 'stale_transcript'

export type ProviderSessionVerdict =
  | { ok: true; observation: ProviderSessionObservation }
  | { ok: false; code: ProviderSessionRejection; reason: string }

/** The newest model the PROVIDER wrote into its own transcript, with the time it
 *  wrote it. A hook-reported model wins when a harness supplies one. */
export function readProviderModelFromTranscript(
  transcriptPath: string
): { model: string; atMs: number } | null {
  let raw: string
  try {
    if (!statSync(transcriptPath).isFile()) {
      return null
    }
    raw = readFileSync(transcriptPath, 'utf8')
  } catch {
    return null
  }
  let newest: { model: string; atMs: number } | null = null
  for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed.startsWith('{')) {
      continue
    }
    let record: { type?: unknown; timestamp?: unknown; message?: { model?: unknown } }
    try {
      record = JSON.parse(trimmed)
    } catch {
      continue
    }
    if (record.type !== 'assistant' || typeof record.message?.model !== 'string') {
      continue
    }
    const atMs = typeof record.timestamp === 'string' ? Date.parse(record.timestamp) : Number.NaN
    const stamped = Number.isFinite(atMs) ? atMs : 0
    if (!newest || stamped >= newest.atMs) {
      newest = { model: record.message.model, atMs: stamped }
    }
  }
  return newest
}

/** True when this status report belongs to the Dispatch's own live session.
 *
 *  The pane key is the anchor: Orca mints it and the provider's hook echoes it
 *  back, so a report carrying it came from the pane this Dispatch occupies.
 *
 *  Terminal and launch token are checked WHEN THE REPORT CARRIES THEM. Claude's
 *  hook does not populate either, and demanding a field the provider never sends
 *  would mean no identity is ever observed — the failure this writer exists to
 *  end. A report carrying a DIFFERENT terminal or token is still refused, which
 *  is the case that actually distinguishes sessions. */
function isThisDispatchsSession(
  dispatch: DispatchContextRow,
  entry: AgentStatusIpcPayload
): boolean {
  if (entry.paneKey !== dispatch.assignee_pane_key) {
    return false
  }
  if (
    dispatch.assignee_handle &&
    entry.terminalHandle &&
    entry.terminalHandle !== dispatch.assignee_handle
  ) {
    return false
  }
  if (dispatch.launch_token_hash && entry.launchToken) {
    return (
      createHash('sha256').update(entry.launchToken).digest('hex') === dispatch.launch_token_hash
    )
  }
  return true
}

export function observeProviderSessionIdentity(args: {
  dispatch: DispatchContextRow
  snapshot: readonly AgentStatusIpcPayload[]
  /** Agent and effort are Orca's own launch parameters, read back from the
   *  worker record rather than taken from the provider's report. */
  agent: string | undefined
  reasoning: string | null
}): ProviderSessionVerdict {
  const { dispatch, snapshot } = args
  const entry = snapshot.find((candidate) => isThisDispatchsSession(dispatch, candidate))
  if (!entry) {
    return {
      ok: false,
      code: 'no_status_for_dispatch',
      reason: `No agent status belongs to Dispatch ${dispatch.id}'s own pane, terminal and launch.`
    }
  }
  const session = entry.providerSession
  if (!session?.id) {
    return {
      ok: false,
      code: 'no_provider_session',
      reason: `Dispatch ${dispatch.id} has no provider session id reported by its hook.`
    }
  }
  // The AGENT is Orca's own launch record, not the provider's word for it: Orca
  // chose which launcher to run. Only the MODEL has to come from the provider,
  // because only the provider knows what it actually loaded.
  const agent = args.agent
  if (!isTuiAgent(agent)) {
    return {
      ok: false,
      code: 'session_not_this_dispatch',
      reason: `Dispatch ${dispatch.id} has no agent on its own launch record.`
    }
  }
  // A hook-reported model is preferred where a harness supplies one; otherwise
  // the provider's own transcript is read.
  const hookModel = typeof entry.model === 'string' && entry.model ? entry.model : null
  const transcriptPath = session.transcriptPath
  const fromTranscript = transcriptPath ? readProviderModelFromTranscript(transcriptPath) : null
  if (!hookModel && !transcriptPath) {
    return {
      ok: false,
      code: 'no_transcript',
      reason: `Dispatch ${dispatch.id} reported session ${session.id} with no transcript to read a model from.`
    }
  }
  if (!hookModel && !fromTranscript) {
    return {
      ok: false,
      code: 'no_provider_model',
      reason: `Session ${session.id} has written no assistant record naming a model, so the provider has not said what it is running.`
    }
  }
  const dispatchedAtMs = Date.parse(exposeUtcTimestamp(dispatch.dispatched_at) ?? '')
  const observedAtMs = hookModel ? entry.receivedAt : (fromTranscript?.atMs ?? 0)
  // A model written before this Dispatch began describes an earlier session in
  // the same file, not this one.
  if (Number.isFinite(dispatchedAtMs) && observedAtMs > 0 && observedAtMs < dispatchedAtMs) {
    return {
      ok: false,
      code: 'stale_transcript',
      reason: `The newest model in session ${session.id} predates Dispatch ${dispatch.id}, so it describes an earlier run.`
    }
  }
  return {
    ok: true,
    observation: {
      identity: {
        agent,
        model: hookModel ?? (fromTranscript as { model: string }).model,
        reasoning: args.reasoning
      },
      sessionId: session.id,
      transcriptPath: transcriptPath ?? '',
      observedAtMs
    }
  }
}

/** Stamps the launch receipt as OBSERVED. Until this runs, the receipt holds only
 *  what Orca asked for, and `readObservedLaunchIdentity` correctly returns null. */
export function persistObservedLaunchReceipt(
  db: OrchestrationDb,
  args: { dispatchId: string; identity: RouteIdentity; sessionId: string; observedAtIso: string }
): boolean {
  const worker = db.getWorkerDispatch(args.dispatchId)
  if (!worker) {
    return false
  }
  let options: Record<string, unknown>
  try {
    const parsed = JSON.parse(worker.start_options)
    options = parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : {}
  } catch {
    return false
  }
  const launch = (options.launch as Record<string, unknown> | undefined) ?? {}
  options.launch = {
    ...launch,
    effective: {
      agent: args.identity.agent,
      model: args.identity.model,
      effort: args.identity.reasoning
    },
    effectiveProvenance: 'observed',
    observedProviderSessionId: args.sessionId,
    observedAt: args.observedAtIso
  }
  db.db
    .prepare('UPDATE worker_dispatches SET start_options = ? WHERE dispatch_id = ?')
    .run(JSON.stringify(options), args.dispatchId)
  return true
}

/** Observes the provider's identity for one Dispatch and persists it, returning
 *  what was observed. The single entry point both the liveness sweep and
 *  certification use, so they cannot disagree about what was seen. */
export function observeAndPersistProviderIdentity(args: {
  db: OrchestrationDb
  dispatchId: string
  snapshot: readonly AgentStatusIpcPayload[]
}): RouteIdentity | null {
  const dispatch = args.db.getDispatchContextById(args.dispatchId)
  if (!dispatch) {
    return null
  }
  const worker = args.db.getWorkerDispatch(args.dispatchId)
  const launched = readDispatchLaunchRoutes(worker?.start_options)
  const verdict = observeProviderSessionIdentity({
    dispatch,
    snapshot: args.snapshot,
    agent: launched.effective?.agent ?? launched.requested?.agent,
    reasoning: readDispatchLaunchEffort(worker?.start_options)
  })
  if (!verdict.ok) {
    return null
  }
  persistObservedLaunchReceipt(args.db, {
    dispatchId: args.dispatchId,
    identity: verdict.observation.identity,
    sessionId: verdict.observation.sessionId,
    observedAtIso: new Date(verdict.observation.observedAtMs || Date.now()).toISOString()
  })
  return verdict.observation.identity
}
