export const DEFAULT_SOURCE_CONTROL_GENERATION_TIMEOUT_MS = 60_000
// Backward-compatible alias; consumers should migrate to DEFAULT_SOURCE_CONTROL_GENERATION_TIMEOUT_MS
export const SOURCE_CONTROL_GENERATION_TIMEOUT_MS = DEFAULT_SOURCE_CONTROL_GENERATION_TIMEOUT_MS
export const MAX_SOURCE_CONTROL_AGENT_OUTPUT_BYTES = 4 * 1024 * 1024
