import { useEffect, useRef, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { translate } from '@/i18n/i18n'
import { openConversationKnowledgeSourceHistory } from '@/lib/conversation-knowledge-source-history'
import {
  conversationKnowledgeEvidenceMessageIds,
  type ConversationKnowledgeItem
} from '../../../../shared/conversation-knowledge-items'
import { SessionTime } from './ai-vault-session-time'

export function ConversationKnowledgeDetail({
  item,
  highlightEvidenceId,
  sourceHistoryScope
}: {
  item: ConversationKnowledgeItem
  highlightEvidenceId?: string | null
  sourceHistoryScope: 'all' | 'project'
}): React.JSX.Element {
  useTranslation()

  const openSourceHistory = (): void => {
    openConversationKnowledgeSourceHistory(item, sourceHistoryScope)
  }

  return (
    <article className="space-y-4 p-4">
      <div>
        <h2 className="text-base font-medium">{item.knowledge.title ?? item.source.title}</h2>
        <p className="mt-1 text-xs text-muted-foreground">
          {translate(
            'conversationKnowledge.detail.generatedBy',
            'Generated by {{agent}} · {{model}}',
            { agent: item.generator.agent, model: item.generator.model }
          )}
        </p>
        <div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
          <span className="inline-flex items-center gap-1">
            {translate('conversationKnowledge.detail.created', 'Created')}
            <SessionTime value={item.source.createdAt} />
          </span>
          <span className="inline-flex items-center gap-1">
            {translate('conversationKnowledge.detail.modified', 'Last modified')}
            <SessionTime value={item.source.updatedAt ?? item.source.modifiedAt} />
          </span>
        </div>
      </div>
      <DetailSection title={translate('conversationKnowledge.detail.summary', 'Summary')}>
        <p className="text-sm leading-6">{item.knowledge.summary}</p>
      </DetailSection>
      <DetailList
        title={translate('conversationKnowledge.detail.conclusions', 'Key conclusions')}
        values={item.knowledge.conclusions}
      />
      <DetailList
        title={translate('conversationKnowledge.detail.topics', 'Topics')}
        values={item.knowledge.topics}
        inline
      />
      <DetailList
        title={translate('conversationKnowledge.detail.entities', 'Entities')}
        values={item.knowledge.entities}
        inline
      />
      <HandoffList
        entries={item.knowledge.handoff ?? []}
        highlightEvidenceId={highlightEvidenceId}
      />
      <DetailSection title={translate('conversationKnowledge.detail.source', 'Source')}>
        <p className="text-xs text-muted-foreground">
          {item.source.agent} · {item.source.sessionId}
        </p>
        <Button className="mt-2" size="sm" variant="outline" onClick={openSourceHistory}>
          {translate(
            'conversationKnowledge.detail.openSessionHistory',
            'Open Agent Session History'
          )}
        </Button>
      </DetailSection>
    </article>
  )
}

function HandoffList({
  entries,
  highlightEvidenceId
}: {
  entries: NonNullable<ConversationKnowledgeItem['knowledge']['handoff']>
  highlightEvidenceId?: string | null
}): React.JSX.Element | null {
  const highlightedEntry = useRef<HTMLLIElement | null>(null)
  useEffect(() => {
    highlightedEntry.current?.scrollIntoView({ block: 'nearest' })
  }, [highlightEvidenceId])
  if (!entries.length) {
    return null
  }
  return (
    <DetailSection title={translate('conversationKnowledge.detail.handoff', 'Agent handoff')}>
      <ul className="space-y-2">
        {entries.map((entry) => {
          const active =
            entry.lifecycle?.status === undefined || entry.lifecycle.status === 'active'
          const included = entry.reliability === 'user-confirmed' && active
          return (
            <li
              key={`${entry.evidence.messageId}:${entry.text}`}
              ref={highlightEvidenceId === entry.evidence.messageId ? highlightedEntry : null}
              className={`rounded-md border p-2 ${highlightEvidenceId === entry.evidence.messageId ? 'border-ring' : 'border-border'}`}
            >
              <div className="flex flex-wrap items-center gap-1.5">
                <Badge variant={included ? 'outline' : 'secondary'}>
                  {handoffReliabilityLabel(entry.reliability)}
                </Badge>
                {!active ? (
                  <Badge variant="secondary">
                    {handoffLifecycleLabel(entry.lifecycle?.status)}
                  </Badge>
                ) : null}
                {included ? (
                  <span className="text-[11px] text-muted-foreground">
                    {translate(
                      'conversationKnowledge.detail.handoffIncluded',
                      'Included in agent context'
                    )}
                  </span>
                ) : null}
                {!active ? (
                  <span className="text-[11px] text-muted-foreground">
                    {translate(
                      'conversationKnowledge.detail.handoffExcluded',
                      'Excluded from agent context'
                    )}
                  </span>
                ) : null}
              </div>
              <p className="mt-1 text-sm leading-5">{entry.text}</p>
              <p className="mt-1 text-[11px] text-muted-foreground">
                {conversationKnowledgeEvidenceMessageIds(entry).join(' · ')}
              </p>
            </li>
          )
        })}
      </ul>
    </DetailSection>
  )
}

function handoffLifecycleLabel(
  status: 'superseded' | 'conflicted' | 'expired' | 'active' | undefined
): string {
  switch (status) {
    case 'superseded':
      return translate('conversationKnowledge.detail.handoffSuperseded', 'Superseded')
    case 'conflicted':
      return translate('conversationKnowledge.detail.handoffConflicted', 'Conflicted')
    case 'expired':
      return translate('conversationKnowledge.detail.handoffExpired', 'Expired')
    case 'active':
    case undefined:
      return translate('conversationKnowledge.detail.handoffActive', 'Active')
  }
}

function handoffReliabilityLabel(
  reliability: NonNullable<ConversationKnowledgeItem['knowledge']['handoff']>[number]['reliability']
): string {
  switch (reliability) {
    case 'user-confirmed':
      return translate('conversationKnowledge.detail.handoffUserConfirmed', 'User confirmed')
    case 'verified':
      return translate('conversationKnowledge.detail.handoffVerified', 'Verified')
    case 'inferred':
      return translate('conversationKnowledge.detail.handoffInferred', 'Inferred')
    case 'proposal':
      return translate('conversationKnowledge.detail.handoffProposal', 'Proposal')
  }
}

function DetailSection({
  title,
  children
}: {
  title: string
  children: ReactNode
}): React.JSX.Element {
  return (
    <section>
      <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
        {title}
      </h3>
      {children}
    </section>
  )
}

function DetailList({
  title,
  values,
  inline = false
}: {
  title: string
  values: string[]
  inline?: boolean
}): React.JSX.Element | null {
  if (!values.length) {
    return null
  }
  return (
    <DetailSection title={title}>
      <ul className={inline ? 'flex flex-wrap gap-1.5' : 'space-y-1.5'}>
        {values.map((value) => (
          <li
            key={value}
            className={
              inline
                ? 'rounded-md border border-border px-2 py-1 text-xs'
                : 'text-sm leading-5 before:mr-2 before:text-muted-foreground before:content-["•"]'
            }
          >
            {value}
          </li>
        ))}
      </ul>
    </DetailSection>
  )
}
