import React from 'react';
import type { Virtualizer } from '@tanstack/react-virtual';
import type { GitFileStatus } from '../../../../shared/types';
import { type InlineInput } from './FileExplorerRow';
import type { DirCache, TreeNode } from './file-explorer-types';
type FileExplorerVirtualRowsProps = {
    virtualizer: Virtualizer<HTMLDivElement, Element>;
    inlineInputIndex: number;
    flatRows: TreeNode[];
    inlineInput: InlineInput | null;
    handleInlineSubmit: (value: string) => void;
    dismissInlineInput: () => void;
    folderStatusByRelativePath: Map<string, GitFileStatus | null>;
    statusByRelativePath: Map<string, GitFileStatus>;
    expanded: Set<string>;
    dirCache: Record<string, DirCache>;
    selectedPath: string | null;
    activeFileId: string | null;
    flashingPath: string | null;
    deleteShortcutLabel: string;
    onClick: (node: TreeNode) => void;
    onDoubleClick: (node: TreeNode) => void;
    onSelectPath: (path: string) => void;
    onStartNew: (type: 'file' | 'folder', parentPath: string, depth: number) => void;
    onStartRename: (node: TreeNode) => void;
    onDuplicate: (node: TreeNode) => void;
    onRequestDelete: (node: TreeNode) => void;
    onMoveDrop: (sourcePath: string, destDir: string) => void;
    onDragTargetChange: (dir: string | null) => void;
    onDragSourceChange: (path: string | null) => void;
    onDragExpandDir: (dirPath: string) => void;
    onNativeDragTargetChange: (dir: string | null) => void;
    onNativeDragExpandDir: (dirPath: string) => void;
    dropTargetDir: string | null;
    dragSourcePath: string | null;
    nativeDropTargetDir: string | null;
};
export declare function FileExplorerVirtualRows(props: FileExplorerVirtualRowsProps): React.JSX.Element;
export {};
