import React from 'react';
import type { GitFileStatus } from '../../../../shared/types';
import type { TreeNode } from './file-explorer-types';
export type InlineInput = {
    parentPath: string;
    type: 'file' | 'folder' | 'rename';
    depth: number;
    existingName?: string;
    existingPath?: string;
};
export declare function InlineInputRow({ depth, inlineInput, onSubmit, onCancel }: {
    depth: number;
    inlineInput: InlineInput;
    onSubmit: (value: string) => void;
    onCancel: () => void;
}): React.JSX.Element;
type FileExplorerRowProps = {
    node: TreeNode;
    isExpanded: boolean;
    isLoading: boolean;
    isSelected: boolean;
    isFlashing: boolean;
    nodeStatus: GitFileStatus | null;
    statusColor: string | null;
    deleteShortcutLabel: string;
    targetDir: string;
    targetDepth: number;
    onClick: () => void;
    onDoubleClick: () => void;
    onSelect: () => void;
    onStartNew: (type: 'file' | 'folder', dir: string, depth: number) => void;
    onStartRename: (node: TreeNode) => void;
    onDuplicate: (node: TreeNode) => void;
    onRequestDelete: () => void;
    onMoveDrop: (sourcePath: string, destDir: string) => void;
    onDragTargetChange: (dir: string | null) => void;
    onDragSourceChange: (path: string | null) => void;
    onDragExpandDir: (dirPath: string) => void;
    onNativeDragTargetChange: (dir: string | null) => void;
    onNativeDragExpandDir: (dirPath: string) => void;
};
export declare function FileExplorerRow({ node, isExpanded, isLoading, isSelected, isFlashing, nodeStatus, statusColor, deleteShortcutLabel, targetDir, targetDepth, onClick, onDoubleClick, onSelect, onStartNew, onStartRename, onDuplicate, onRequestDelete, onMoveDrop, onDragTargetChange, onDragSourceChange, onDragExpandDir, onNativeDragTargetChange, onNativeDragExpandDir }: FileExplorerRowProps): React.JSX.Element;
export {};
