import React from 'react';
type SearchHeaderProps = {
    inputRef: React.RefObject<HTMLInputElement | null>;
    includeInputRef: React.RefObject<HTMLInputElement | null>;
    excludeInputRef: React.RefObject<HTMLInputElement | null>;
    query: string;
    loading: boolean;
    detailsVisible: boolean;
    caseSensitive: boolean;
    wholeWord: boolean;
    useRegex: boolean;
    includePattern: string;
    excludePattern: string;
    onQueryChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onKeyDown: (e: React.KeyboardEvent) => void;
    onClearSearch: () => void;
    onToggleSearchDetails: () => void;
    onToggleCaseSensitive: () => void;
    onToggleWholeWord: () => void;
    onToggleRegex: () => void;
    onIncludeChange: (value: string) => void;
    onExcludeChange: (value: string) => void;
};
export declare function SearchHeader({ inputRef, includeInputRef, excludeInputRef, query, loading, detailsVisible, caseSensitive, wholeWord, useRegex, includePattern, excludePattern, onQueryChange, onKeyDown, onClearSearch, onToggleSearchDetails, onToggleCaseSensitive, onToggleWholeWord, onToggleRegex, onIncludeChange, onExcludeChange }: SearchHeaderProps): React.JSX.Element;
export {};
