import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search as SearchIcon, CaseSensitive, WholeWord, Regex, X, Loader2, Ellipsis } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SearchFilters } from './SearchFilters';
import { ToggleButton } from './SearchResultItems';
export function SearchHeader({ inputRef, includeInputRef, excludeInputRef, query, loading, detailsVisible, caseSensitive, wholeWord, useRegex, includePattern, excludePattern, onQueryChange, onKeyDown, onClearSearch, onToggleSearchDetails, onToggleCaseSensitive, onToggleWholeWord, onToggleRegex, onIncludeChange, onExcludeChange }) {
    return (_jsxs("div", { className: "flex flex-col gap-1.5 p-2 border-b border-border", children: [_jsxs("div", { className: "flex items-center gap-1 bg-input/50 border border-border rounded-sm px-1.5 focus-within:border-ring", children: [_jsx(SearchIcon, { size: 14, className: "text-muted-foreground flex-shrink-0" }), _jsx("input", { ref: inputRef, type: "text", className: "flex-1 bg-transparent text-xs py-1.5 outline-none text-foreground placeholder:text-muted-foreground/50 min-w-0", placeholder: "Search", value: query, onChange: onQueryChange, onKeyDown: onKeyDown, spellCheck: false }), loading && (_jsx(Loader2, { size: 12, className: "text-muted-foreground animate-spin flex-shrink-0" })), query && (_jsx(Button, { type: "button", variant: "ghost", size: "icon-xs", className: "h-auto w-auto rounded-sm p-0.5 text-muted-foreground hover:text-foreground", onClick: onClearSearch, children: _jsx(X, { size: 12 }) })), _jsx(ToggleButton, { active: detailsVisible, onClick: onToggleSearchDetails, title: "Toggle Search Details", ariaExpanded: detailsVisible, children: _jsx(Ellipsis, { size: 14 }) }), _jsx(ToggleButton, { active: caseSensitive, onClick: onToggleCaseSensitive, title: "Match Case", children: _jsx(CaseSensitive, { size: 14 }) }), _jsx(ToggleButton, { active: wholeWord, onClick: onToggleWholeWord, title: "Match Whole Word", children: _jsx(WholeWord, { size: 14 }) }), _jsx(ToggleButton, { active: useRegex, onClick: onToggleRegex, title: "Use Regular Expression", children: _jsx(Regex, { size: 14 }) })] }), detailsVisible && (
            // Why: VS Code keeps include/exclude scope controls tucked behind a
            // dedicated details toggle so the default search UI stays compact
            // until the user asks for extra filtering options.
            _jsx(SearchFilters, { includePattern: includePattern, excludePattern: excludePattern, includeInputRef: includeInputRef, excludeInputRef: excludeInputRef, onIncludeChange: onIncludeChange, onExcludeChange: onExcludeChange }))] }));
}
